#include "common.h"

INCLUDE_RODATA("rooms/nonmatchings/dryfield_night_motel_balcony/dryfield_night_motel_balcony", D_dryfield_night_motel_balcony_8017D5C0);

INCLUDE_ASM("rooms/nonmatchings/dryfield_night_motel_balcony/dryfield_night_motel_balcony", func_dryfield_night_motel_balcony_8017D7F8);

INCLUDE_ASM("rooms/nonmatchings/dryfield_night_motel_balcony/dryfield_night_motel_balcony", func_dryfield_night_motel_balcony_8017D968);

INCLUDE_RODATA("rooms/nonmatchings/dryfield_night_motel_balcony/dryfield_night_motel_balcony", RoomsShared8017d878Table);

INCLUDE_RODATA("rooms/nonmatchings/dryfield_night_motel_balcony/dryfield_night_motel_balcony", jtbl_dryfield_night_motel_balcony_8017D5E8);
