#include "common.h"

INCLUDE_ASM("rooms/nonmatchings/dryfield_night_general_store/dryfield_night_general_store_2", func_dryfield_night_general_store_8017DE24);

INCLUDE_ASM("rooms/nonmatchings/dryfield_night_general_store/dryfield_night_general_store_2", func_dryfield_night_general_store_8017DE2C);

INCLUDE_ASM("rooms/nonmatchings/dryfield_night_general_store/dryfield_night_general_store_2", func_dryfield_night_general_store_8017DE34);

void func_dryfield_night_general_store_8017DE80(void)
{
}

INCLUDE_ASM("rooms/nonmatchings/dryfield_night_general_store/dryfield_night_general_store_2", func_dryfield_night_general_store_8017DE88);
