#include "common.h"

INCLUDE_ASM("rooms/nonmatchings/dryfield_night_general_store/dryfield_night_general_store", func_dryfield_night_general_store_8017D630);

INCLUDE_RODATA("rooms/nonmatchings/dryfield_night_general_store/dryfield_night_general_store", D_dryfield_night_general_store_8017D5C0);

INCLUDE_ASM("rooms/nonmatchings/dryfield_night_general_store/dryfield_night_general_store", func_dryfield_night_general_store_8017D794);

INCLUDE_ASM("rooms/nonmatchings/dryfield_night_general_store/dryfield_night_general_store", func_dryfield_night_general_store_8017D904);

INCLUDE_ASM("rooms/nonmatchings/dryfield_night_general_store/dryfield_night_general_store", func_dryfield_night_general_store_8017DAF0);

INCLUDE_ASM("rooms/nonmatchings/dryfield_night_general_store/dryfield_night_general_store", func_dryfield_night_general_store_8017DCA8);

INCLUDE_ASM("rooms/nonmatchings/dryfield_night_general_store/dryfield_night_general_store", func_dryfield_night_general_store_8017DD88);

INCLUDE_RODATA("rooms/nonmatchings/dryfield_night_general_store/dryfield_night_general_store", D_dryfield_night_general_store_8017D5F4);

INCLUDE_RODATA("rooms/nonmatchings/dryfield_night_general_store/dryfield_night_general_store", jtbl_dryfield_night_general_store_8017D600);
