#include "common.h"

INCLUDE_ASM("rooms/dryfield_night_motel_room_2/nonmatchings/dryfield_night_motel_room_2", func_dryfield_night_motel_room_2_8017D5D8);

INCLUDE_ASM("rooms/dryfield_night_motel_room_2/nonmatchings/dryfield_night_motel_room_2", func_dryfield_night_motel_room_2_8017D660);

INCLUDE_ASM("rooms/dryfield_night_motel_room_2/nonmatchings/dryfield_night_motel_room_2", func_dryfield_night_motel_room_2_8017D668);

INCLUDE_ASM("rooms/dryfield_night_motel_room_2/nonmatchings/dryfield_night_motel_room_2", func_dryfield_night_motel_room_2_8017D670);

void func_dryfield_night_motel_room_2_8017D6B4(void) {
}

INCLUDE_RODATA("rooms/dryfield_night_motel_room_2/nonmatchings/dryfield_night_motel_room_2", D_dryfield_night_motel_room_2_8017D5C0);

INCLUDE_ASM("rooms/dryfield_night_motel_room_2/nonmatchings/dryfield_night_motel_room_2", func_dryfield_night_motel_room_2_8017D6BC);

INCLUDE_ASM("rooms/dryfield_night_motel_room_2/nonmatchings/dryfield_night_motel_room_2", func_dryfield_night_motel_room_2_8017D714);

INCLUDE_ASM("rooms/dryfield_night_motel_room_2/nonmatchings/dryfield_night_motel_room_2", func_dryfield_night_motel_room_2_8017D990);
