.include "macro.inc"

.set noat
.set noreorder

/*
 * Fs_DecompressImage  (VRAM 0x80010398 / ROM 0xB98)
 * ------------------------------------------------------------
 * Permanent handwritten assembly (splat type: hasm).
 *
 * Role
 *   Non-resumable LZ / bit-stream unpacker for image payloads (same family
 *   as Fs_DecompressChunk, without CD-sector suspend/resume). Called from
 *   Fs_LoadImageChunk before LoadImage2; writes through Fs_ChunkWritePtr
 *   into a scratch buffer (typically D5B498_8006D870) using a 256-byte
 *   ring at scratchpad 0x1F800000.
 *
 * Why this stays handwritten assembly
 *   Same reasons as Fs_DecompressChunk (minus mid-function resume):
 *     - signed MIPS `sub` / `addi` that GCC 2.8.1 never emits
 *     - early-image placement (linker_section_order: .rodata)
 *     - tight register machine / delay-slot packing
 *   Do not convert to type: c or INCLUDE_ASM from a regular TU.
 */

.section .text, "ax"

/* Generated by spimdisasm 1.42.3 */

glabel Fs_DecompressImage
    /* B98 80010398 801F073C */  lui        $a3, (0x1F800000 >> 16)
    /* B9C 8001039C 21280000 */  addu       $a1, $zero, $zero
    /* BA0 800103A0 FC03E584 */  lh         $a1, (0x1F8003FC & 0xFFFF)($a3)
    /* BA4 800103A4 00010424 */  addiu      $a0, $zero, 0x100
    /* BA8 800103A8 2230A400 */  sub        $a2, $a1, $a0 /* handwritten instruction */
    /* BAC 800103AC 0500C01C */  bgtz       $a2, .L800103C4
    /* BB0 800103B0 FFFF0434 */   ori       $a0, $zero, 0xFFFF
    /* BB4 800103B4 0780013C */  lui        $at, %hi(D5B498_8006D748)
    /* BB8 800103B8 48D724A4 */  sh         $a0, %lo(D5B498_8006D748)($at)
    /* BBC 800103BC 0800E003 */  jr         $ra
    /* BC0 800103C0 00000000 */   nop
  .L800103C4:
    /* BC4 800103C4 0780083C */  lui        $t0, %hi(Fs_ChunkReadPtr)
    /* BC8 800103C8 2CC2088D */  lw         $t0, %lo(Fs_ChunkReadPtr)($t0)
    /* BCC 800103CC 0780093C */  lui        $t1, %hi(Fs_ChunkWritePtr)
    /* BD0 800103D0 D8D4298D */  lw         $t1, %lo(Fs_ChunkWritePtr)($t1)
    /* BD4 800103D4 21500000 */  addu       $t2, $zero, $zero
    /* BD8 800103D8 21580000 */  addu       $t3, $zero, $zero
    /* BDC 800103DC 21300000 */  addu       $a2, $zero, $zero
    /* BE0 800103E0 01000C24 */  addiu      $t4, $zero, 0x1
  .L800103E4:
    /* BE4 800103E4 05004015 */  bnez       $t2, .L800103FC
    /* BE8 800103E8 00000000 */   nop
    /* BEC 800103EC FF000A24 */  addiu      $t2, $zero, 0xFF
    /* BF0 800103F0 08000624 */  addiu      $a2, $zero, 0x8
    /* BF4 800103F4 00000B91 */  lbu        $t3, 0x0($t0)
    /* BF8 800103F8 01000825 */  addiu      $t0, $t0, 0x1
  .L800103FC:
    /* BFC 800103FC 24684B01 */  and        $t5, $t2, $t3
    /* C00 80010400 42500A00 */  srl        $t2, $t2, 1
    /* C04 80010404 FFFFC620 */  addi       $a2, $a2, -0x1 /* handwritten instruction */
    /* C08 80010408 FF004439 */  xori       $a0, $t2, 0xFF
    /* C0C 8001040C 2468A401 */  and        $t5, $t5, $a0
    /* C10 80010410 1F00A019 */  blez       $t5, .L80010490
    /* C14 80010414 08000E24 */   addiu     $t6, $zero, 0x8
    /* C18 80010418 00000D24 */  addiu      $t5, $zero, 0x0
    /* C1C 8001041C 05004015 */  bnez       $t2, .L80010434
    /* C20 80010420 00000000 */   nop
    /* C24 80010424 FF000A24 */  addiu      $t2, $zero, 0xFF
    /* C28 80010428 08000624 */  addiu      $a2, $zero, 0x8
    /* C2C 8001042C 00000B91 */  lbu        $t3, 0x0($t0)
    /* C30 80010430 01000825 */  addiu      $t0, $t0, 0x1
  .L80010434:
    /* C34 80010434 24284B01 */  and        $a1, $t2, $t3
    /* C38 80010438 2168A000 */  addu       $t5, $a1, $zero
    /* C3C 8001043C 2270C601 */  sub        $t6, $t6, $a2 /* handwritten instruction */
    /* C40 80010440 FF000A24 */  addiu      $t2, $zero, 0xFF
    /* C44 80010444 08000624 */  addiu      $a2, $zero, 0x8
    /* C48 80010448 00000B91 */  lbu        $t3, 0x0($t0)
    /* C4C 8001044C 01000825 */  addiu      $t0, $t0, 0x1
    /* C50 80010450 0800C011 */  beqz       $t6, .L80010474
    /* C54 80010454 00000000 */   nop
    /* C58 80010458 0650CA01 */  srlv       $t2, $t2, $t6
    /* C5C 8001045C 2230CE00 */  sub        $a2, $a2, $t6 /* handwritten instruction */
    /* C60 80010460 FF004539 */  xori       $a1, $t2, 0xFF
    /* C64 80010464 2428AB00 */  and        $a1, $a1, $t3
    /* C68 80010468 0468CD01 */  sllv       $t5, $t5, $t6
    /* C6C 8001046C 0628C500 */  srlv       $a1, $a1, $a2
    /* C70 80010470 2568A501 */  or         $t5, $t5, $a1
  .L80010474:
    /* C74 80010474 2110EC00 */  addu       $v0, $a3, $t4
    /* C78 80010478 00004DA0 */  sb         $t5, (0x1F800000 & 0xFFFF)($v0)
    /* C7C 8001047C 00002DA1 */  sb         $t5, 0x0($t1)
    /* C80 80010480 01008C25 */  addiu      $t4, $t4, 0x1
    /* C84 80010484 FF008C31 */  andi       $t4, $t4, 0xFF
    /* C88 80010488 01002925 */  addiu      $t1, $t1, 0x1
    /* C8C 8001048C F9400008 */  j          .L800103E4
  .L80010490:
    /* C90 80010490 08000E24 */   addiu     $t6, $zero, 0x8
    /* C94 80010494 00000F24 */  addiu      $t7, $zero, 0x0
    /* C98 80010498 05004015 */  bnez       $t2, .L800104B0
    /* C9C 8001049C 00000000 */   nop
    /* CA0 800104A0 FF000A24 */  addiu      $t2, $zero, 0xFF
    /* CA4 800104A4 08000624 */  addiu      $a2, $zero, 0x8
    /* CA8 800104A8 00000B91 */  lbu        $t3, 0x0($t0)
    /* CAC 800104AC 01000825 */  addiu      $t0, $t0, 0x1
  .L800104B0:
    /* CB0 800104B0 24284B01 */  and        $a1, $t2, $t3
    /* CB4 800104B4 2178A000 */  addu       $t7, $a1, $zero
    /* CB8 800104B8 2270C601 */  sub        $t6, $t6, $a2 /* handwritten instruction */
    /* CBC 800104BC FF000A24 */  addiu      $t2, $zero, 0xFF
    /* CC0 800104C0 08000624 */  addiu      $a2, $zero, 0x8
    /* CC4 800104C4 00000B91 */  lbu        $t3, 0x0($t0)
    /* CC8 800104C8 01000825 */  addiu      $t0, $t0, 0x1
    /* CCC 800104CC 0800C011 */  beqz       $t6, .L800104F0
    /* CD0 800104D0 00000000 */   nop
    /* CD4 800104D4 0650CA01 */  srlv       $t2, $t2, $t6
    /* CD8 800104D8 2230CE00 */  sub        $a2, $a2, $t6 /* handwritten instruction */
    /* CDC 800104DC FF004539 */  xori       $a1, $t2, 0xFF
    /* CE0 800104E0 2428AB00 */  and        $a1, $a1, $t3
    /* CE4 800104E4 0478CF01 */  sllv       $t7, $t7, $t6
    /* CE8 800104E8 0628C500 */  srlv       $a1, $a1, $a2
    /* CEC 800104EC 2578E501 */  or         $t7, $t7, $a1
  .L800104F0:
    /* CF0 800104F0 2900E011 */  beqz       $t7, .L80010598
    /* CF4 800104F4 04000E24 */   addiu     $t6, $zero, 0x4
    /* CF8 800104F8 00000D24 */  addiu      $t5, $zero, 0x0
    /* CFC 800104FC 05004015 */  bnez       $t2, .L80010514
    /* D00 80010500 00000000 */   nop
    /* D04 80010504 FF000A24 */  addiu      $t2, $zero, 0xFF
    /* D08 80010508 08000624 */  addiu      $a2, $zero, 0x8
    /* D0C 8001050C 00000B91 */  lbu        $t3, 0x0($t0)
    /* D10 80010510 01000825 */  addiu      $t0, $t0, 0x1
  .L80010514:
    /* D14 80010514 2220C601 */  sub        $a0, $t6, $a2 /* handwritten instruction */
    /* D18 80010518 07008018 */  blez       $a0, .L80010538
    /* D1C 8001051C 00000000 */   nop
    /* D20 80010520 21708000 */  addu       $t6, $a0, $zero
    /* D24 80010524 24684B01 */  and        $t5, $t2, $t3
    /* D28 80010528 FF000A24 */  addiu      $t2, $zero, 0xFF
    /* D2C 8001052C 08000624 */  addiu      $a2, $zero, 0x8
    /* D30 80010530 00000B91 */  lbu        $t3, 0x0($t0)
    /* D34 80010534 01000825 */  addiu      $t0, $t0, 0x1
  .L80010538:
    /* D38 80010538 24284B01 */  and        $a1, $t2, $t3
    /* D3C 8001053C 0650CA01 */  srlv       $t2, $t2, $t6
    /* D40 80010540 2230CE00 */  sub        $a2, $a2, $t6 /* handwritten instruction */
    /* D44 80010544 FF004439 */  xori       $a0, $t2, 0xFF
    /* D48 80010548 2428A400 */  and        $a1, $a1, $a0
    /* D4C 8001054C 0468CD01 */  sllv       $t5, $t5, $t6
    /* D50 80010550 0628C500 */  srlv       $a1, $a1, $a2
    /* D54 80010554 2568A501 */  or         $t5, $t5, $a1
    /* D58 80010558 0100A325 */  addiu      $v1, $t5, 0x1
  .L8001055C:
    /* D5C 8001055C FF00E431 */  andi       $a0, $t7, 0xFF
    /* D60 80010560 2110E400 */  addu       $v0, $a3, $a0
    /* D64 80010564 00004D90 */  lbu        $t5, 0x0($v0)
    /* D68 80010568 2110EC00 */  addu       $v0, $a3, $t4
    /* D6C 8001056C 00004DA0 */  sb         $t5, 0x0($v0)
    /* D70 80010570 00002DA1 */  sb         $t5, 0x0($t1)
    /* D74 80010574 01008C25 */  addiu      $t4, $t4, 0x1
    /* D78 80010578 FF008C31 */  andi       $t4, $t4, 0xFF
    /* D7C 8001057C 01002925 */  addiu      $t1, $t1, 0x1
    /* D80 80010580 0100EF25 */  addiu      $t7, $t7, 0x1
    /* D84 80010584 FFFF6320 */  addi       $v1, $v1, -0x1 /* handwritten instruction */
    /* D88 80010588 F4FF6104 */  bgez       $v1, .L8001055C
    /* D8C 8001058C 00000000 */   nop
    /* D90 80010590 F9400008 */  j          .L800103E4
    /* D94 80010594 00000000 */   nop
  .L80010598:
    /* D98 80010598 01000424 */  addiu      $a0, $zero, 0x1
    /* D9C 8001059C 0780013C */  lui        $at, %hi(D5B498_8006D748)
    /* DA0 800105A0 48D724A4 */  sh         $a0, %lo(D5B498_8006D748)($at)
    /* DA4 800105A4 0800E003 */  jr         $ra
    /* DA8 800105A8 00000000 */   nop
endlabel Fs_DecompressImage
