#include "common.h"

INCLUDE_ASM("rooms/nonmatchings/shelter_b3_garbage_incinerator/shelter_b3_garbage_incinerator_5", func_shelter_b3_garbage_incinerator_80183E78);

INCLUDE_ASM("rooms/nonmatchings/shelter_b3_garbage_incinerator/shelter_b3_garbage_incinerator_5", func_shelter_b3_garbage_incinerator_801842A4);

void func_shelter_b3_garbage_incinerator_80184D7C(void)
{
}

INCLUDE_ASM("rooms/nonmatchings/shelter_b3_garbage_incinerator/shelter_b3_garbage_incinerator_5", func_shelter_b3_garbage_incinerator_80184D84);
