#include "common.h"

INCLUDE_ASM("rooms/shelter_b1_control_room/nonmatchings/shelter_b1_control_room", func_shelter_b1_control_room_8017D600);

INCLUDE_ASM("rooms/shelter_b1_control_room/nonmatchings/shelter_b1_control_room", func_shelter_b1_control_room_8017D7B8);

INCLUDE_ASM("rooms/shelter_b1_control_room/nonmatchings/shelter_b1_control_room", func_shelter_b1_control_room_8017ECCC);

INCLUDE_ASM("rooms/shelter_b1_control_room/nonmatchings/shelter_b1_control_room", func_shelter_b1_control_room_8017ECD4);

INCLUDE_ASM("rooms/shelter_b1_control_room/nonmatchings/shelter_b1_control_room", func_shelter_b1_control_room_8017ED68);

INCLUDE_ASM("rooms/shelter_b1_control_room/nonmatchings/shelter_b1_control_room", func_shelter_b1_control_room_8017EE24);

INCLUDE_ASM("rooms/shelter_b1_control_room/nonmatchings/shelter_b1_control_room", func_shelter_b1_control_room_8017EE2C);

INCLUDE_ASM("rooms/shelter_b1_control_room/nonmatchings/shelter_b1_control_room", func_shelter_b1_control_room_8017EEBC);

INCLUDE_RODATA("rooms/shelter_b1_control_room/nonmatchings/shelter_b1_control_room", D_shelter_b1_control_room_8017D5C0);

INCLUDE_ASM("rooms/shelter_b1_control_room/nonmatchings/shelter_b1_control_room", func_shelter_b1_control_room_8017EECC);

INCLUDE_ASM("rooms/shelter_b1_control_room/nonmatchings/shelter_b1_control_room", func_shelter_b1_control_room_8017EF24);

INCLUDE_ASM("rooms/shelter_b1_control_room/nonmatchings/shelter_b1_control_room", func_shelter_b1_control_room_8017F100);

INCLUDE_ASM("rooms/shelter_b1_control_room/nonmatchings/shelter_b1_control_room", func_shelter_b1_control_room_8017F150);

INCLUDE_ASM("rooms/shelter_b1_control_room/nonmatchings/shelter_b1_control_room", func_shelter_b1_control_room_8017F39C);

INCLUDE_ASM("rooms/shelter_b1_control_room/nonmatchings/shelter_b1_control_room", func_shelter_b1_control_room_8017FBE0);

INCLUDE_ASM("rooms/shelter_b1_control_room/nonmatchings/shelter_b1_control_room", func_shelter_b1_control_room_8017FF80);

INCLUDE_ASM("rooms/shelter_b1_control_room/nonmatchings/shelter_b1_control_room", func_shelter_b1_control_room_801804D8);

INCLUDE_ASM("rooms/shelter_b1_control_room/nonmatchings/shelter_b1_control_room", func_shelter_b1_control_room_801806FC);

INCLUDE_ASM("rooms/shelter_b1_control_room/nonmatchings/shelter_b1_control_room", func_shelter_b1_control_room_80180980);

INCLUDE_ASM("rooms/shelter_b1_control_room/nonmatchings/shelter_b1_control_room", func_shelter_b1_control_room_80180DA4);

INCLUDE_ASM("rooms/shelter_b1_control_room/nonmatchings/shelter_b1_control_room", func_shelter_b1_control_room_80181138);

INCLUDE_ASM("rooms/shelter_b1_control_room/nonmatchings/shelter_b1_control_room", func_shelter_b1_control_room_801812E4);

INCLUDE_ASM("rooms/shelter_b1_control_room/nonmatchings/shelter_b1_control_room", func_shelter_b1_control_room_80181810);
