#include "common.h"

INCLUDE_ASM("rooms/nonmatchings/dryfield_night_motel_room_6/dryfield_night_motel_room_6_2", func_dryfield_night_motel_room_6_8017EE38);

INCLUDE_ASM("rooms/nonmatchings/dryfield_night_motel_room_6/dryfield_night_motel_room_6_2", func_dryfield_night_motel_room_6_8017EF2C);

INCLUDE_RODATA("rooms/nonmatchings/dryfield_night_motel_room_6/dryfield_night_motel_room_6_2", jtbl_dryfield_night_motel_room_6_8017D654);
