#include "common.h"

INCLUDE_ASM("rooms/nonmatchings/dryfield_night_motel_room_6/dryfield_night_motel_room_6_3", func_dryfield_night_motel_room_6_8017F498);

INCLUDE_ASM("rooms/nonmatchings/dryfield_night_motel_room_6/dryfield_night_motel_room_6_3", func_dryfield_night_motel_room_6_8017F64C);

INCLUDE_ASM("rooms/nonmatchings/dryfield_night_motel_room_6/dryfield_night_motel_room_6_3", func_dryfield_night_motel_room_6_80180FD0);

INCLUDE_ASM("rooms/nonmatchings/dryfield_night_motel_room_6/dryfield_night_motel_room_6_3", func_dryfield_night_motel_room_6_801811A0);
