#include "common.h"

INCLUDE_ASM("rooms/nonmatchings/dryfield_night_motel_room_6/dryfield_night_motel_room_6_3", func_dryfield_night_motel_room_6_8017F120);

INCLUDE_ASM("rooms/nonmatchings/dryfield_night_motel_room_6/dryfield_night_motel_room_6_3", func_dryfield_night_motel_room_6_8017F204);

INCLUDE_ASM("rooms/nonmatchings/dryfield_night_motel_room_6/dryfield_night_motel_room_6_3", func_dryfield_night_motel_room_6_8017F2CC);

INCLUDE_ASM("rooms/nonmatchings/dryfield_night_motel_room_6/dryfield_night_motel_room_6_3", func_dryfield_night_motel_room_6_8017F394);
