#include "common.h"

INCLUDE_ASM("rooms/nonmatchings/dryfield_night_motel_room_4/dryfield_night_motel_room_4", func_dryfield_night_motel_room_4_8017D5D8);

INCLUDE_ASM("rooms/nonmatchings/dryfield_night_motel_room_4/dryfield_night_motel_room_4", func_dryfield_night_motel_room_4_8017D660);

INCLUDE_ASM("rooms/nonmatchings/dryfield_night_motel_room_4/dryfield_night_motel_room_4", func_dryfield_night_motel_room_4_8017D668);

INCLUDE_ASM("rooms/nonmatchings/dryfield_night_motel_room_4/dryfield_night_motel_room_4", func_dryfield_night_motel_room_4_8017D670);

void func_dryfield_night_motel_room_4_8017D6B4(void)
{
}

INCLUDE_RODATA("rooms/nonmatchings/dryfield_night_motel_room_4/dryfield_night_motel_room_4", D_dryfield_night_motel_room_4_8017D5C0);

INCLUDE_ASM("rooms/nonmatchings/dryfield_night_motel_room_4/dryfield_night_motel_room_4", func_dryfield_night_motel_room_4_8017D6BC);

INCLUDE_ASM("rooms/nonmatchings/dryfield_night_motel_room_4/dryfield_night_motel_room_4", func_dryfield_night_motel_room_4_8017D714);

INCLUDE_ASM("rooms/nonmatchings/dryfield_night_motel_room_4/dryfield_night_motel_room_4", func_dryfield_night_motel_room_4_8017D990);
