#include "common.h"

s32 func_shelter_b1_control_room_access_tunnel_8017D630(void)
{
    return 0;
}

s32 func_shelter_b1_control_room_access_tunnel_8017D638(void)
{
    return 0;
}

INCLUDE_ASM("rooms/nonmatchings/shelter_b1_control_room_access_tunnel/shelter_b1_control_room_access_tunnel", func_shelter_b1_control_room_access_tunnel_8017D640);

void func_shelter_b1_control_room_access_tunnel_8017D684(void)
{
}

INCLUDE_RODATA("rooms/nonmatchings/shelter_b1_control_room_access_tunnel/shelter_b1_control_room_access_tunnel", D_shelter_b1_control_room_access_tunnel_8017D5C0);

INCLUDE_ASM("rooms/nonmatchings/shelter_b1_control_room_access_tunnel/shelter_b1_control_room_access_tunnel", func_shelter_b1_control_room_access_tunnel_8017D68C);

INCLUDE_RODATA("rooms/nonmatchings/shelter_b1_control_room_access_tunnel/shelter_b1_control_room_access_tunnel", jtbl_shelter_b1_control_room_access_tunnel_8017D5D0);

INCLUDE_RODATA("rooms/nonmatchings/shelter_b1_control_room_access_tunnel/shelter_b1_control_room_access_tunnel", D_shelter_b1_control_room_access_tunnel_8017D5E4);
