#include "common.h"

INCLUDE_ASM("rooms/nonmatchings/shelter_b1_control_room_access_tunnel/shelter_b1_control_room_access_tunnel_2", func_shelter_b1_control_room_access_tunnel_8017E1BC);

INCLUDE_ASM("rooms/nonmatchings/shelter_b1_control_room_access_tunnel/shelter_b1_control_room_access_tunnel_2", func_shelter_b1_control_room_access_tunnel_8017E2D8);
