#include "common.h"

INCLUDE_ASM("rooms/nonmatchings/shelter_b1_control_room_access_tunnel/shelter_b1_control_room_access_tunnel_2", func_shelter_b1_control_room_access_tunnel_8018026C);

INCLUDE_ASM("rooms/nonmatchings/shelter_b1_control_room_access_tunnel/shelter_b1_control_room_access_tunnel_2", func_shelter_b1_control_room_access_tunnel_801807C4);

INCLUDE_ASM("rooms/nonmatchings/shelter_b1_control_room_access_tunnel/shelter_b1_control_room_access_tunnel_2", func_shelter_b1_control_room_access_tunnel_801809E8);

INCLUDE_ASM("rooms/nonmatchings/shelter_b1_control_room_access_tunnel/shelter_b1_control_room_access_tunnel_2", func_shelter_b1_control_room_access_tunnel_80180C6C);

INCLUDE_ASM("rooms/nonmatchings/shelter_b1_control_room_access_tunnel/shelter_b1_control_room_access_tunnel_2", func_shelter_b1_control_room_access_tunnel_80181090);

INCLUDE_ASM("rooms/nonmatchings/shelter_b1_control_room_access_tunnel/shelter_b1_control_room_access_tunnel_2", func_shelter_b1_control_room_access_tunnel_80181424);

INCLUDE_ASM("rooms/nonmatchings/shelter_b1_control_room_access_tunnel/shelter_b1_control_room_access_tunnel_2", func_shelter_b1_control_room_access_tunnel_801815D0);

INCLUDE_ASM("rooms/nonmatchings/shelter_b1_control_room_access_tunnel/shelter_b1_control_room_access_tunnel_2", func_shelter_b1_control_room_access_tunnel_80181AFC);
