#include "common.h"

INCLUDE_ASM("rooms/nonmatchings/shelter_b1_control_room_access_tunnel/shelter_b1_control_room_access_tunnel_5", func_shelter_b1_control_room_access_tunnel_8018026C);

INCLUDE_ASM("rooms/nonmatchings/shelter_b1_control_room_access_tunnel/shelter_b1_control_room_access_tunnel_5", func_shelter_b1_control_room_access_tunnel_801807C4);
