#include "common.h"

INCLUDE_ASM("rooms/nonmatchings/shelter_b1_control_room_access_tunnel/shelter_b1_control_room_access_tunnel", func_shelter_b1_control_room_access_tunnel_8017D5EC);

INCLUDE_ASM("rooms/nonmatchings/shelter_b1_control_room_access_tunnel/shelter_b1_control_room_access_tunnel", func_shelter_b1_control_room_access_tunnel_8017D630);

INCLUDE_ASM("rooms/nonmatchings/shelter_b1_control_room_access_tunnel/shelter_b1_control_room_access_tunnel", func_shelter_b1_control_room_access_tunnel_8017D638);

INCLUDE_ASM("rooms/nonmatchings/shelter_b1_control_room_access_tunnel/shelter_b1_control_room_access_tunnel", func_shelter_b1_control_room_access_tunnel_8017D640);

void func_shelter_b1_control_room_access_tunnel_8017D684(void)
{
}

INCLUDE_RODATA("rooms/nonmatchings/shelter_b1_control_room_access_tunnel/shelter_b1_control_room_access_tunnel", D_shelter_b1_control_room_access_tunnel_8017D5C0);

INCLUDE_ASM("rooms/nonmatchings/shelter_b1_control_room_access_tunnel/shelter_b1_control_room_access_tunnel", func_shelter_b1_control_room_access_tunnel_8017D68C);

INCLUDE_ASM("rooms/nonmatchings/shelter_b1_control_room_access_tunnel/shelter_b1_control_room_access_tunnel", func_shelter_b1_control_room_access_tunnel_8017D6E4);

INCLUDE_ASM("rooms/nonmatchings/shelter_b1_control_room_access_tunnel/shelter_b1_control_room_access_tunnel", func_shelter_b1_control_room_access_tunnel_8017DE60);

INCLUDE_ASM("rooms/nonmatchings/shelter_b1_control_room_access_tunnel/shelter_b1_control_room_access_tunnel", func_shelter_b1_control_room_access_tunnel_8017E1BC);

INCLUDE_ASM("rooms/nonmatchings/shelter_b1_control_room_access_tunnel/shelter_b1_control_room_access_tunnel", func_shelter_b1_control_room_access_tunnel_8017E2D8);

INCLUDE_ASM("rooms/nonmatchings/shelter_b1_control_room_access_tunnel/shelter_b1_control_room_access_tunnel", func_shelter_b1_control_room_access_tunnel_8017E57C);

INCLUDE_ASM("rooms/nonmatchings/shelter_b1_control_room_access_tunnel/shelter_b1_control_room_access_tunnel", func_shelter_b1_control_room_access_tunnel_8017E9A8);

INCLUDE_ASM("rooms/nonmatchings/shelter_b1_control_room_access_tunnel/shelter_b1_control_room_access_tunnel", func_shelter_b1_control_room_access_tunnel_8017ED3C);

INCLUDE_ASM("rooms/nonmatchings/shelter_b1_control_room_access_tunnel/shelter_b1_control_room_access_tunnel", func_shelter_b1_control_room_access_tunnel_8017F22C);

INCLUDE_ASM("rooms/nonmatchings/shelter_b1_control_room_access_tunnel/shelter_b1_control_room_access_tunnel", func_shelter_b1_control_room_access_tunnel_8017F624);

INCLUDE_RODATA("rooms/nonmatchings/shelter_b1_control_room_access_tunnel/shelter_b1_control_room_access_tunnel", jtbl_shelter_b1_control_room_access_tunnel_8017D5D0);

INCLUDE_RODATA("rooms/nonmatchings/shelter_b1_control_room_access_tunnel/shelter_b1_control_room_access_tunnel", D_shelter_b1_control_room_access_tunnel_8017D5E4);
