#include "common.h"

INCLUDE_RODATA("rooms/nonmatchings/shelter_b2_north_maintenance_walkway/shelter_b2_north_maintenance_walkway", D_shelter_b2_north_maintenance_walkway_8017D5C0);

INCLUDE_ASM("rooms/nonmatchings/shelter_b2_north_maintenance_walkway/shelter_b2_north_maintenance_walkway", func_shelter_b2_north_maintenance_walkway_8017D61C);
