#include "common.h"

INCLUDE_RODATA("rooms/shelter_b2_north_maintenance_walkway/nonmatchings/shelter_b2_north_maintenance_walkway", D_shelter_b2_north_maintenance_walkway_8017D5C0);

INCLUDE_ASM("rooms/shelter_b2_north_maintenance_walkway/nonmatchings/shelter_b2_north_maintenance_walkway", func_shelter_b2_north_maintenance_walkway_8017D61C);

INCLUDE_ASM("rooms/shelter_b2_north_maintenance_walkway/nonmatchings/shelter_b2_north_maintenance_walkway", func_shelter_b2_north_maintenance_walkway_8017D7B4);

INCLUDE_ASM("rooms/shelter_b2_north_maintenance_walkway/nonmatchings/shelter_b2_north_maintenance_walkway", func_shelter_b2_north_maintenance_walkway_8017D918);

INCLUDE_ASM("rooms/shelter_b2_north_maintenance_walkway/nonmatchings/shelter_b2_north_maintenance_walkway", func_shelter_b2_north_maintenance_walkway_8017DA88);

INCLUDE_ASM("rooms/shelter_b2_north_maintenance_walkway/nonmatchings/shelter_b2_north_maintenance_walkway", func_shelter_b2_north_maintenance_walkway_8017DC44);

INCLUDE_ASM("rooms/shelter_b2_north_maintenance_walkway/nonmatchings/shelter_b2_north_maintenance_walkway", func_shelter_b2_north_maintenance_walkway_8017DC4C);

INCLUDE_ASM("rooms/shelter_b2_north_maintenance_walkway/nonmatchings/shelter_b2_north_maintenance_walkway", func_shelter_b2_north_maintenance_walkway_8017DC54);

INCLUDE_ASM("rooms/shelter_b2_north_maintenance_walkway/nonmatchings/shelter_b2_north_maintenance_walkway", func_shelter_b2_north_maintenance_walkway_8017DCE4);

INCLUDE_ASM("rooms/shelter_b2_north_maintenance_walkway/nonmatchings/shelter_b2_north_maintenance_walkway", func_shelter_b2_north_maintenance_walkway_8017DD18);

INCLUDE_ASM("rooms/shelter_b2_north_maintenance_walkway/nonmatchings/shelter_b2_north_maintenance_walkway", func_shelter_b2_north_maintenance_walkway_8017DD80);

INCLUDE_ASM("rooms/shelter_b2_north_maintenance_walkway/nonmatchings/shelter_b2_north_maintenance_walkway", func_shelter_b2_north_maintenance_walkway_8017DD90);

INCLUDE_ASM("rooms/shelter_b2_north_maintenance_walkway/nonmatchings/shelter_b2_north_maintenance_walkway", func_shelter_b2_north_maintenance_walkway_8017DDE8);

INCLUDE_ASM("rooms/shelter_b2_north_maintenance_walkway/nonmatchings/shelter_b2_north_maintenance_walkway", func_shelter_b2_north_maintenance_walkway_8017E0DC);

INCLUDE_ASM("rooms/shelter_b2_north_maintenance_walkway/nonmatchings/shelter_b2_north_maintenance_walkway", func_shelter_b2_north_maintenance_walkway_8017E858);

INCLUDE_ASM("rooms/shelter_b2_north_maintenance_walkway/nonmatchings/shelter_b2_north_maintenance_walkway", func_shelter_b2_north_maintenance_walkway_8017EBB4);

INCLUDE_ASM("rooms/shelter_b2_north_maintenance_walkway/nonmatchings/shelter_b2_north_maintenance_walkway", func_shelter_b2_north_maintenance_walkway_8017F590);

INCLUDE_ASM("rooms/shelter_b2_north_maintenance_walkway/nonmatchings/shelter_b2_north_maintenance_walkway", func_shelter_b2_north_maintenance_walkway_8017F85C);

INCLUDE_ASM("rooms/shelter_b2_north_maintenance_walkway/nonmatchings/shelter_b2_north_maintenance_walkway", func_shelter_b2_north_maintenance_walkway_8017FB20);

INCLUDE_ASM("rooms/shelter_b2_north_maintenance_walkway/nonmatchings/shelter_b2_north_maintenance_walkway", func_shelter_b2_north_maintenance_walkway_8017FF44);

INCLUDE_ASM("rooms/shelter_b2_north_maintenance_walkway/nonmatchings/shelter_b2_north_maintenance_walkway", func_shelter_b2_north_maintenance_walkway_801802D8);

INCLUDE_ASM("rooms/shelter_b2_north_maintenance_walkway/nonmatchings/shelter_b2_north_maintenance_walkway", func_shelter_b2_north_maintenance_walkway_80180670);

INCLUDE_ASM("rooms/shelter_b2_north_maintenance_walkway/nonmatchings/shelter_b2_north_maintenance_walkway", func_shelter_b2_north_maintenance_walkway_8018081C);

INCLUDE_ASM("rooms/shelter_b2_north_maintenance_walkway/nonmatchings/shelter_b2_north_maintenance_walkway", func_shelter_b2_north_maintenance_walkway_80180D48);

INCLUDE_ASM("rooms/shelter_b2_north_maintenance_walkway/nonmatchings/shelter_b2_north_maintenance_walkway", func_shelter_b2_north_maintenance_walkway_801810C0);

INCLUDE_ASM("rooms/shelter_b2_north_maintenance_walkway/nonmatchings/shelter_b2_north_maintenance_walkway", func_shelter_b2_north_maintenance_walkway_80181A80);

INCLUDE_ASM("rooms/shelter_b2_north_maintenance_walkway/nonmatchings/shelter_b2_north_maintenance_walkway", func_shelter_b2_north_maintenance_walkway_80181BB4);

INCLUDE_ASM("rooms/shelter_b2_north_maintenance_walkway/nonmatchings/shelter_b2_north_maintenance_walkway", func_shelter_b2_north_maintenance_walkway_80181E58);

INCLUDE_ASM("rooms/shelter_b2_north_maintenance_walkway/nonmatchings/shelter_b2_north_maintenance_walkway", func_shelter_b2_north_maintenance_walkway_80182284);

INCLUDE_ASM("rooms/shelter_b2_north_maintenance_walkway/nonmatchings/shelter_b2_north_maintenance_walkway", func_shelter_b2_north_maintenance_walkway_80182618);

INCLUDE_ASM("rooms/shelter_b2_north_maintenance_walkway/nonmatchings/shelter_b2_north_maintenance_walkway", func_shelter_b2_north_maintenance_walkway_80182B08);

INCLUDE_ASM("rooms/shelter_b2_north_maintenance_walkway/nonmatchings/shelter_b2_north_maintenance_walkway", func_shelter_b2_north_maintenance_walkway_80182F00);

INCLUDE_ASM("rooms/shelter_b2_north_maintenance_walkway/nonmatchings/shelter_b2_north_maintenance_walkway", func_shelter_b2_north_maintenance_walkway_80183188);
