#include "common.h"

INCLUDE_ASM("rooms/nonmatchings/shelter_b2_north_maintenance_walkway/shelter_b2_north_maintenance_walkway_5", func_shelter_b2_north_maintenance_walkway_801810C0);

INCLUDE_ASM("rooms/nonmatchings/shelter_b2_north_maintenance_walkway/shelter_b2_north_maintenance_walkway_5", func_shelter_b2_north_maintenance_walkway_80181A80);

INCLUDE_ASM("rooms/nonmatchings/shelter_b2_north_maintenance_walkway/shelter_b2_north_maintenance_walkway_5", func_shelter_b2_north_maintenance_walkway_80181BB4);
