#include "common.h"

INCLUDE_ASM("rooms/nonmatchings/shelter_b2_north_maintenance_walkway/shelter_b2_north_maintenance_walkway_4", func_shelter_b2_north_maintenance_walkway_8017FF44);

INCLUDE_ASM("rooms/nonmatchings/shelter_b2_north_maintenance_walkway/shelter_b2_north_maintenance_walkway_4", func_shelter_b2_north_maintenance_walkway_801802D8);

INCLUDE_ASM("rooms/nonmatchings/shelter_b2_north_maintenance_walkway/shelter_b2_north_maintenance_walkway_4", func_shelter_b2_north_maintenance_walkway_80180670);

INCLUDE_ASM("rooms/nonmatchings/shelter_b2_north_maintenance_walkway/shelter_b2_north_maintenance_walkway_4", func_shelter_b2_north_maintenance_walkway_8018081C);
