#include "common.h"

INCLUDE_ASM("rooms/nonmatchings/shelter_b2_north_maintenance_walkway/shelter_b2_north_maintenance_walkway_6", func_shelter_b2_north_maintenance_walkway_80182284);

INCLUDE_ASM("rooms/nonmatchings/shelter_b2_north_maintenance_walkway/shelter_b2_north_maintenance_walkway_6", func_shelter_b2_north_maintenance_walkway_80182618);
