#include "common.h"

INCLUDE_ASM("rooms/nonmatchings/dryfield_night_dilapidated_house/dryfield_night_dilapidated_house_4", func_dryfield_night_dilapidated_house_8017DD30);

INCLUDE_ASM("rooms/nonmatchings/dryfield_night_dilapidated_house/dryfield_night_dilapidated_house_4", func_dryfield_night_dilapidated_house_8017E670);
