#include "common.h"

INCLUDE_RODATA("rooms/shelter_b1_pod_service_gantry/nonmatchings/shelter_b1_pod_service_gantry", D_shelter_b1_pod_service_gantry_8017D5C0);

INCLUDE_RODATA("rooms/shelter_b1_pod_service_gantry/nonmatchings/shelter_b1_pod_service_gantry", D_shelter_b1_pod_service_gantry_8017D5C4);

INCLUDE_ASM("rooms/shelter_b1_pod_service_gantry/nonmatchings/shelter_b1_pod_service_gantry", func_shelter_b1_pod_service_gantry_8017D628);

INCLUDE_ASM("rooms/shelter_b1_pod_service_gantry/nonmatchings/shelter_b1_pod_service_gantry", func_shelter_b1_pod_service_gantry_8017D7C0);

INCLUDE_ASM("rooms/shelter_b1_pod_service_gantry/nonmatchings/shelter_b1_pod_service_gantry", func_shelter_b1_pod_service_gantry_8017D7C8);

INCLUDE_ASM("rooms/shelter_b1_pod_service_gantry/nonmatchings/shelter_b1_pod_service_gantry", func_shelter_b1_pod_service_gantry_8017D80C);

INCLUDE_ASM("rooms/shelter_b1_pod_service_gantry/nonmatchings/shelter_b1_pod_service_gantry", func_shelter_b1_pod_service_gantry_8017D814);

INCLUDE_ASM("rooms/shelter_b1_pod_service_gantry/nonmatchings/shelter_b1_pod_service_gantry", func_shelter_b1_pod_service_gantry_8017D81C);

INCLUDE_ASM("rooms/shelter_b1_pod_service_gantry/nonmatchings/shelter_b1_pod_service_gantry", func_shelter_b1_pod_service_gantry_8017D89C);

INCLUDE_ASM("rooms/shelter_b1_pod_service_gantry/nonmatchings/shelter_b1_pod_service_gantry", func_shelter_b1_pod_service_gantry_8017D8F4);

INCLUDE_ASM("rooms/shelter_b1_pod_service_gantry/nonmatchings/shelter_b1_pod_service_gantry", func_shelter_b1_pod_service_gantry_8017DF70);

INCLUDE_ASM("rooms/shelter_b1_pod_service_gantry/nonmatchings/shelter_b1_pod_service_gantry", func_shelter_b1_pod_service_gantry_8017E400);

INCLUDE_ASM("rooms/shelter_b1_pod_service_gantry/nonmatchings/shelter_b1_pod_service_gantry", func_shelter_b1_pod_service_gantry_8017E880);

INCLUDE_ASM("rooms/shelter_b1_pod_service_gantry/nonmatchings/shelter_b1_pod_service_gantry", func_shelter_b1_pod_service_gantry_8017ED3C);

INCLUDE_ASM("rooms/shelter_b1_pod_service_gantry/nonmatchings/shelter_b1_pod_service_gantry", func_shelter_b1_pod_service_gantry_8017F160);

INCLUDE_ASM("rooms/shelter_b1_pod_service_gantry/nonmatchings/shelter_b1_pod_service_gantry", func_shelter_b1_pod_service_gantry_8017F450);

INCLUDE_ASM("rooms/shelter_b1_pod_service_gantry/nonmatchings/shelter_b1_pod_service_gantry", func_shelter_b1_pod_service_gantry_8017F8C8);

INCLUDE_ASM("rooms/shelter_b1_pod_service_gantry/nonmatchings/shelter_b1_pod_service_gantry", func_shelter_b1_pod_service_gantry_8017FA7C);
