#include "common.h"

INCLUDE_ASM("rooms/dryfield_night_water_tank/nonmatchings/dryfield_night_water_tank", func_dryfield_night_water_tank_8017D5D0);

INCLUDE_ASM("rooms/dryfield_night_water_tank/nonmatchings/dryfield_night_water_tank", func_dryfield_night_water_tank_8017D70C);

INCLUDE_ASM("rooms/dryfield_night_water_tank/nonmatchings/dryfield_night_water_tank", func_dryfield_night_water_tank_8017D714);

INCLUDE_ASM("rooms/dryfield_night_water_tank/nonmatchings/dryfield_night_water_tank", func_dryfield_night_water_tank_8017D73C);

INCLUDE_ASM("rooms/dryfield_night_water_tank/nonmatchings/dryfield_night_water_tank", func_dryfield_night_water_tank_8017D76C);

INCLUDE_ASM("rooms/dryfield_night_water_tank/nonmatchings/dryfield_night_water_tank", func_dryfield_night_water_tank_8017D870);

INCLUDE_ASM("rooms/dryfield_night_water_tank/nonmatchings/dryfield_night_water_tank", func_dryfield_night_water_tank_8017D94C);

INCLUDE_RODATA("rooms/dryfield_night_water_tank/nonmatchings/dryfield_night_water_tank", D_dryfield_night_water_tank_8017D5C0);

INCLUDE_ASM("rooms/dryfield_night_water_tank/nonmatchings/dryfield_night_water_tank", func_dryfield_night_water_tank_8017D984);

INCLUDE_ASM("rooms/dryfield_night_water_tank/nonmatchings/dryfield_night_water_tank", func_dryfield_night_water_tank_8017D9DC);

INCLUDE_ASM("rooms/dryfield_night_water_tank/nonmatchings/dryfield_night_water_tank", func_dryfield_night_water_tank_8017DB8C);

void func_dryfield_night_water_tank_8017DD8C(void) {
}
