#include "common.h"

INCLUDE_ASM("rooms/nonmatchings/shelter_b2_south_maintenance_walkway/shelter_b2_south_maintenance_walkway_3", func_shelter_b2_south_maintenance_walkway_80181AE8);

INCLUDE_ASM("rooms/nonmatchings/shelter_b2_south_maintenance_walkway/shelter_b2_south_maintenance_walkway_3", func_shelter_b2_south_maintenance_walkway_80181C94);
