#include "common.h"

INCLUDE_ASM("rooms/nonmatchings/shelter_b2_south_maintenance_walkway/shelter_b2_south_maintenance_walkway_2", func_shelter_b2_south_maintenance_walkway_80180930);

INCLUDE_ASM("rooms/nonmatchings/shelter_b2_south_maintenance_walkway/shelter_b2_south_maintenance_walkway_2", func_shelter_b2_south_maintenance_walkway_80180E88);

INCLUDE_ASM("rooms/nonmatchings/shelter_b2_south_maintenance_walkway/shelter_b2_south_maintenance_walkway_2", func_shelter_b2_south_maintenance_walkway_801810AC);

INCLUDE_ASM("rooms/nonmatchings/shelter_b2_south_maintenance_walkway/shelter_b2_south_maintenance_walkway_2", func_shelter_b2_south_maintenance_walkway_80181330);

INCLUDE_ASM("rooms/nonmatchings/shelter_b2_south_maintenance_walkway/shelter_b2_south_maintenance_walkway_2", func_shelter_b2_south_maintenance_walkway_80181754);

INCLUDE_ASM("rooms/nonmatchings/shelter_b2_south_maintenance_walkway/shelter_b2_south_maintenance_walkway_2", func_shelter_b2_south_maintenance_walkway_80181AE8);

INCLUDE_ASM("rooms/nonmatchings/shelter_b2_south_maintenance_walkway/shelter_b2_south_maintenance_walkway_2", func_shelter_b2_south_maintenance_walkway_80181C94);

INCLUDE_ASM("rooms/nonmatchings/shelter_b2_south_maintenance_walkway/shelter_b2_south_maintenance_walkway_2", func_shelter_b2_south_maintenance_walkway_801821C0);
