#include "common.h"

INCLUDE_ASM("rooms/nonmatchings/shelter_b2_south_maintenance_walkway/shelter_b2_south_maintenance_walkway", func_shelter_b2_south_maintenance_walkway_8017D610);

INCLUDE_RODATA("rooms/nonmatchings/shelter_b2_south_maintenance_walkway/shelter_b2_south_maintenance_walkway", D_shelter_b2_south_maintenance_walkway_8017D5C0);

INCLUDE_ASM("rooms/nonmatchings/shelter_b2_south_maintenance_walkway/shelter_b2_south_maintenance_walkway", func_shelter_b2_south_maintenance_walkway_8017D774);

INCLUDE_ASM("rooms/nonmatchings/shelter_b2_south_maintenance_walkway/shelter_b2_south_maintenance_walkway", func_shelter_b2_south_maintenance_walkway_8017D8E4);

INCLUDE_ASM("rooms/nonmatchings/shelter_b2_south_maintenance_walkway/shelter_b2_south_maintenance_walkway", func_shelter_b2_south_maintenance_walkway_8017DA7C);

s32 func_shelter_b2_south_maintenance_walkway_8017DC08(void)
{
    return 0;
}

INCLUDE_ASM("rooms/nonmatchings/shelter_b2_south_maintenance_walkway/shelter_b2_south_maintenance_walkway", func_shelter_b2_south_maintenance_walkway_8017DC10);

s32 func_shelter_b2_south_maintenance_walkway_8017DC18(void)
{
    return 0;
}

INCLUDE_ASM("rooms/nonmatchings/shelter_b2_south_maintenance_walkway/shelter_b2_south_maintenance_walkway", func_shelter_b2_south_maintenance_walkway_8017DC20);

void func_shelter_b2_south_maintenance_walkway_8017DC64(void)
{
}

INCLUDE_ASM("rooms/nonmatchings/shelter_b2_south_maintenance_walkway/shelter_b2_south_maintenance_walkway", func_shelter_b2_south_maintenance_walkway_8017DC6C);

INCLUDE_ASM("rooms/nonmatchings/shelter_b2_south_maintenance_walkway/shelter_b2_south_maintenance_walkway", func_shelter_b2_south_maintenance_walkway_8017DCC4);

INCLUDE_RODATA("rooms/nonmatchings/shelter_b2_south_maintenance_walkway/shelter_b2_south_maintenance_walkway", jtbl_shelter_b2_south_maintenance_walkway_8017D5FC);
