#include "common.h"

INCLUDE_ASM("rooms/shelter_b2_south_maintenance_walkway/nonmatchings/shelter_b2_south_maintenance_walkway", func_shelter_b2_south_maintenance_walkway_8017D610);

INCLUDE_RODATA("rooms/shelter_b2_south_maintenance_walkway/nonmatchings/shelter_b2_south_maintenance_walkway", D_shelter_b2_south_maintenance_walkway_8017D5C0);

INCLUDE_ASM("rooms/shelter_b2_south_maintenance_walkway/nonmatchings/shelter_b2_south_maintenance_walkway", func_shelter_b2_south_maintenance_walkway_8017D774);

INCLUDE_ASM("rooms/shelter_b2_south_maintenance_walkway/nonmatchings/shelter_b2_south_maintenance_walkway", func_shelter_b2_south_maintenance_walkway_8017D8E4);

INCLUDE_ASM("rooms/shelter_b2_south_maintenance_walkway/nonmatchings/shelter_b2_south_maintenance_walkway", func_shelter_b2_south_maintenance_walkway_8017DA7C);

INCLUDE_ASM("rooms/shelter_b2_south_maintenance_walkway/nonmatchings/shelter_b2_south_maintenance_walkway", func_shelter_b2_south_maintenance_walkway_8017DC08);

INCLUDE_ASM("rooms/shelter_b2_south_maintenance_walkway/nonmatchings/shelter_b2_south_maintenance_walkway", func_shelter_b2_south_maintenance_walkway_8017DC10);

INCLUDE_ASM("rooms/shelter_b2_south_maintenance_walkway/nonmatchings/shelter_b2_south_maintenance_walkway", func_shelter_b2_south_maintenance_walkway_8017DC18);

INCLUDE_ASM("rooms/shelter_b2_south_maintenance_walkway/nonmatchings/shelter_b2_south_maintenance_walkway", func_shelter_b2_south_maintenance_walkway_8017DC20);

void func_shelter_b2_south_maintenance_walkway_8017DC64(void) {
}

INCLUDE_ASM("rooms/shelter_b2_south_maintenance_walkway/nonmatchings/shelter_b2_south_maintenance_walkway", func_shelter_b2_south_maintenance_walkway_8017DC6C);

INCLUDE_ASM("rooms/shelter_b2_south_maintenance_walkway/nonmatchings/shelter_b2_south_maintenance_walkway", func_shelter_b2_south_maintenance_walkway_8017DCC4);

INCLUDE_ASM("rooms/shelter_b2_south_maintenance_walkway/nonmatchings/shelter_b2_south_maintenance_walkway", func_shelter_b2_south_maintenance_walkway_8017DEC4);

INCLUDE_ASM("rooms/shelter_b2_south_maintenance_walkway/nonmatchings/shelter_b2_south_maintenance_walkway", func_shelter_b2_south_maintenance_walkway_8017E640);

INCLUDE_ASM("rooms/shelter_b2_south_maintenance_walkway/nonmatchings/shelter_b2_south_maintenance_walkway", func_shelter_b2_south_maintenance_walkway_8017E99C);

INCLUDE_ASM("rooms/shelter_b2_south_maintenance_walkway/nonmatchings/shelter_b2_south_maintenance_walkway", func_shelter_b2_south_maintenance_walkway_8017EC40);

INCLUDE_ASM("rooms/shelter_b2_south_maintenance_walkway/nonmatchings/shelter_b2_south_maintenance_walkway", func_shelter_b2_south_maintenance_walkway_8017F06C);

INCLUDE_ASM("rooms/shelter_b2_south_maintenance_walkway/nonmatchings/shelter_b2_south_maintenance_walkway", func_shelter_b2_south_maintenance_walkway_8017F400);

INCLUDE_ASM("rooms/shelter_b2_south_maintenance_walkway/nonmatchings/shelter_b2_south_maintenance_walkway", func_shelter_b2_south_maintenance_walkway_8017F8F0);

INCLUDE_ASM("rooms/shelter_b2_south_maintenance_walkway/nonmatchings/shelter_b2_south_maintenance_walkway", func_shelter_b2_south_maintenance_walkway_8017FCE8);

INCLUDE_ASM("rooms/shelter_b2_south_maintenance_walkway/nonmatchings/shelter_b2_south_maintenance_walkway", func_shelter_b2_south_maintenance_walkway_8017FF70);

INCLUDE_ASM("rooms/shelter_b2_south_maintenance_walkway/nonmatchings/shelter_b2_south_maintenance_walkway", func_shelter_b2_south_maintenance_walkway_80180930);

INCLUDE_ASM("rooms/shelter_b2_south_maintenance_walkway/nonmatchings/shelter_b2_south_maintenance_walkway", func_shelter_b2_south_maintenance_walkway_80180E88);

INCLUDE_ASM("rooms/shelter_b2_south_maintenance_walkway/nonmatchings/shelter_b2_south_maintenance_walkway", func_shelter_b2_south_maintenance_walkway_801810AC);

INCLUDE_ASM("rooms/shelter_b2_south_maintenance_walkway/nonmatchings/shelter_b2_south_maintenance_walkway", func_shelter_b2_south_maintenance_walkway_80181330);

INCLUDE_ASM("rooms/shelter_b2_south_maintenance_walkway/nonmatchings/shelter_b2_south_maintenance_walkway", func_shelter_b2_south_maintenance_walkway_80181754);

INCLUDE_ASM("rooms/shelter_b2_south_maintenance_walkway/nonmatchings/shelter_b2_south_maintenance_walkway", func_shelter_b2_south_maintenance_walkway_80181AE8);

INCLUDE_ASM("rooms/shelter_b2_south_maintenance_walkway/nonmatchings/shelter_b2_south_maintenance_walkway", func_shelter_b2_south_maintenance_walkway_80181C94);

INCLUDE_ASM("rooms/shelter_b2_south_maintenance_walkway/nonmatchings/shelter_b2_south_maintenance_walkway", func_shelter_b2_south_maintenance_walkway_801821C0);
