categories:
  - id: main
    name: Main Executable
    paths:
      - main
  - id: title
    name: Title Overlay
    paths:
      - title

expected_paths:
  ALL: expected/
  USA: expected/USA

ignored_files:
  - main/header
  - main/psyq/libsn/snmain

output: ./objdiff.json
