#include "common.h"

INCLUDE_ASM("rooms/nonmatchings/shelter_b1_transfer_tunnel/shelter_b1_transfer_tunnel_3", func_shelter_b1_transfer_tunnel_8017ECBC);

INCLUDE_ASM("rooms/nonmatchings/shelter_b1_transfer_tunnel/shelter_b1_transfer_tunnel_3", func_shelter_b1_transfer_tunnel_8017F050);

INCLUDE_ASM("rooms/nonmatchings/shelter_b1_transfer_tunnel/shelter_b1_transfer_tunnel_3", func_shelter_b1_transfer_tunnel_8017F3E8);

INCLUDE_ASM("rooms/nonmatchings/shelter_b1_transfer_tunnel/shelter_b1_transfer_tunnel_3", func_shelter_b1_transfer_tunnel_8017F594);
