#include "common.h"

INCLUDE_ASM("rooms/nonmatchings/shelter_b1_north_maintenance_walkway/shelter_b1_north_maintenance_walkway_6", func_shelter_b1_north_maintenance_walkway_80184028);

INCLUDE_ASM("rooms/nonmatchings/shelter_b1_north_maintenance_walkway/shelter_b1_north_maintenance_walkway_6", func_shelter_b1_north_maintenance_walkway_801841D4);

INCLUDE_ASM("rooms/nonmatchings/shelter_b1_north_maintenance_walkway/shelter_b1_north_maintenance_walkway_6", func_shelter_b1_north_maintenance_walkway_80184700);
