#include "common.h"

INCLUDE_RODATA("rooms/shelter_b1_north_maintenance_walkway/nonmatchings/shelter_b1_north_maintenance_walkway", D_shelter_b1_north_maintenance_walkway_8017D5C0);

INCLUDE_ASM("rooms/shelter_b1_north_maintenance_walkway/nonmatchings/shelter_b1_north_maintenance_walkway", func_shelter_b1_north_maintenance_walkway_8017D60C);

INCLUDE_ASM("rooms/shelter_b1_north_maintenance_walkway/nonmatchings/shelter_b1_north_maintenance_walkway", func_shelter_b1_north_maintenance_walkway_8017D7A4);

INCLUDE_ASM("rooms/shelter_b1_north_maintenance_walkway/nonmatchings/shelter_b1_north_maintenance_walkway", func_shelter_b1_north_maintenance_walkway_8017D918);

INCLUDE_ASM("rooms/shelter_b1_north_maintenance_walkway/nonmatchings/shelter_b1_north_maintenance_walkway", func_shelter_b1_north_maintenance_walkway_8017DA34);

INCLUDE_ASM("rooms/shelter_b1_north_maintenance_walkway/nonmatchings/shelter_b1_north_maintenance_walkway", func_shelter_b1_north_maintenance_walkway_8017DA3C);

INCLUDE_ASM("rooms/shelter_b1_north_maintenance_walkway/nonmatchings/shelter_b1_north_maintenance_walkway", func_shelter_b1_north_maintenance_walkway_8017DA44);

INCLUDE_ASM("rooms/shelter_b1_north_maintenance_walkway/nonmatchings/shelter_b1_north_maintenance_walkway", func_shelter_b1_north_maintenance_walkway_8017DA4C);

void func_shelter_b1_north_maintenance_walkway_8017DAF4(void) {
}

INCLUDE_ASM("rooms/shelter_b1_north_maintenance_walkway/nonmatchings/shelter_b1_north_maintenance_walkway", func_shelter_b1_north_maintenance_walkway_8017DAFC);

INCLUDE_ASM("rooms/shelter_b1_north_maintenance_walkway/nonmatchings/shelter_b1_north_maintenance_walkway", func_shelter_b1_north_maintenance_walkway_8017DB54);

INCLUDE_ASM("rooms/shelter_b1_north_maintenance_walkway/nonmatchings/shelter_b1_north_maintenance_walkway", func_shelter_b1_north_maintenance_walkway_8017DBC8);

INCLUDE_ASM("rooms/shelter_b1_north_maintenance_walkway/nonmatchings/shelter_b1_north_maintenance_walkway", func_shelter_b1_north_maintenance_walkway_8017DDE0);

INCLUDE_ASM("rooms/shelter_b1_north_maintenance_walkway/nonmatchings/shelter_b1_north_maintenance_walkway", func_shelter_b1_north_maintenance_walkway_8017E55C);

INCLUDE_ASM("rooms/shelter_b1_north_maintenance_walkway/nonmatchings/shelter_b1_north_maintenance_walkway", func_shelter_b1_north_maintenance_walkway_8017E8B8);

INCLUDE_ASM("rooms/shelter_b1_north_maintenance_walkway/nonmatchings/shelter_b1_north_maintenance_walkway", func_shelter_b1_north_maintenance_walkway_8017EB84);

INCLUDE_ASM("rooms/shelter_b1_north_maintenance_walkway/nonmatchings/shelter_b1_north_maintenance_walkway", func_shelter_b1_north_maintenance_walkway_8017EE48);

INCLUDE_ASM("rooms/shelter_b1_north_maintenance_walkway/nonmatchings/shelter_b1_north_maintenance_walkway", func_shelter_b1_north_maintenance_walkway_8017F26C);

INCLUDE_ASM("rooms/shelter_b1_north_maintenance_walkway/nonmatchings/shelter_b1_north_maintenance_walkway", func_shelter_b1_north_maintenance_walkway_8017F600);

INCLUDE_ASM("rooms/shelter_b1_north_maintenance_walkway/nonmatchings/shelter_b1_north_maintenance_walkway", func_shelter_b1_north_maintenance_walkway_8017F998);

INCLUDE_ASM("rooms/shelter_b1_north_maintenance_walkway/nonmatchings/shelter_b1_north_maintenance_walkway", func_shelter_b1_north_maintenance_walkway_8017FB44);

INCLUDE_ASM("rooms/shelter_b1_north_maintenance_walkway/nonmatchings/shelter_b1_north_maintenance_walkway", func_shelter_b1_north_maintenance_walkway_80180070);

INCLUDE_ASM("rooms/shelter_b1_north_maintenance_walkway/nonmatchings/shelter_b1_north_maintenance_walkway", func_shelter_b1_north_maintenance_walkway_801803E8);

INCLUDE_ASM("rooms/shelter_b1_north_maintenance_walkway/nonmatchings/shelter_b1_north_maintenance_walkway", func_shelter_b1_north_maintenance_walkway_80180DA8);

INCLUDE_ASM("rooms/shelter_b1_north_maintenance_walkway/nonmatchings/shelter_b1_north_maintenance_walkway", func_shelter_b1_north_maintenance_walkway_80180EDC);

INCLUDE_ASM("rooms/shelter_b1_north_maintenance_walkway/nonmatchings/shelter_b1_north_maintenance_walkway", func_shelter_b1_north_maintenance_walkway_80181180);

INCLUDE_ASM("rooms/shelter_b1_north_maintenance_walkway/nonmatchings/shelter_b1_north_maintenance_walkway", func_shelter_b1_north_maintenance_walkway_801815AC);

INCLUDE_ASM("rooms/shelter_b1_north_maintenance_walkway/nonmatchings/shelter_b1_north_maintenance_walkway", func_shelter_b1_north_maintenance_walkway_80181940);

INCLUDE_ASM("rooms/shelter_b1_north_maintenance_walkway/nonmatchings/shelter_b1_north_maintenance_walkway", func_shelter_b1_north_maintenance_walkway_80181E30);

INCLUDE_ASM("rooms/shelter_b1_north_maintenance_walkway/nonmatchings/shelter_b1_north_maintenance_walkway", func_shelter_b1_north_maintenance_walkway_80182228);

INCLUDE_ASM("rooms/shelter_b1_north_maintenance_walkway/nonmatchings/shelter_b1_north_maintenance_walkway", func_shelter_b1_north_maintenance_walkway_801824B0);

INCLUDE_ASM("rooms/shelter_b1_north_maintenance_walkway/nonmatchings/shelter_b1_north_maintenance_walkway", func_shelter_b1_north_maintenance_walkway_80182E70);

INCLUDE_ASM("rooms/shelter_b1_north_maintenance_walkway/nonmatchings/shelter_b1_north_maintenance_walkway", func_shelter_b1_north_maintenance_walkway_801833C8);

INCLUDE_ASM("rooms/shelter_b1_north_maintenance_walkway/nonmatchings/shelter_b1_north_maintenance_walkway", func_shelter_b1_north_maintenance_walkway_801835EC);

INCLUDE_ASM("rooms/shelter_b1_north_maintenance_walkway/nonmatchings/shelter_b1_north_maintenance_walkway", func_shelter_b1_north_maintenance_walkway_80183870);

INCLUDE_ASM("rooms/shelter_b1_north_maintenance_walkway/nonmatchings/shelter_b1_north_maintenance_walkway", func_shelter_b1_north_maintenance_walkway_80183C94);

INCLUDE_ASM("rooms/shelter_b1_north_maintenance_walkway/nonmatchings/shelter_b1_north_maintenance_walkway", func_shelter_b1_north_maintenance_walkway_80184028);

INCLUDE_ASM("rooms/shelter_b1_north_maintenance_walkway/nonmatchings/shelter_b1_north_maintenance_walkway", func_shelter_b1_north_maintenance_walkway_801841D4);

INCLUDE_ASM("rooms/shelter_b1_north_maintenance_walkway/nonmatchings/shelter_b1_north_maintenance_walkway", func_shelter_b1_north_maintenance_walkway_80184700);
