#include "common.h"

INCLUDE_ASM("rooms/nonmatchings/shelter_b1_north_maintenance_walkway/shelter_b1_north_maintenance_walkway_5", func_shelter_b1_north_maintenance_walkway_801824B0);

INCLUDE_ASM("rooms/nonmatchings/shelter_b1_north_maintenance_walkway/shelter_b1_north_maintenance_walkway_5", func_shelter_b1_north_maintenance_walkway_80182E70);

INCLUDE_ASM("rooms/nonmatchings/shelter_b1_north_maintenance_walkway/shelter_b1_north_maintenance_walkway_5", func_shelter_b1_north_maintenance_walkway_801833C8);
