#include "common.h"

INCLUDE_ASM("rooms/nonmatchings/shelter_b1_north_maintenance_walkway/shelter_b1_north_maintenance_walkway_4", func_shelter_b1_north_maintenance_walkway_8017F26C);

INCLUDE_ASM("rooms/nonmatchings/shelter_b1_north_maintenance_walkway/shelter_b1_north_maintenance_walkway_4", func_shelter_b1_north_maintenance_walkway_8017F600);

INCLUDE_ASM("rooms/nonmatchings/shelter_b1_north_maintenance_walkway/shelter_b1_north_maintenance_walkway_4", func_shelter_b1_north_maintenance_walkway_8017F998);

INCLUDE_ASM("rooms/nonmatchings/shelter_b1_north_maintenance_walkway/shelter_b1_north_maintenance_walkway_4", func_shelter_b1_north_maintenance_walkway_8017FB44);

INCLUDE_ASM("rooms/nonmatchings/shelter_b1_north_maintenance_walkway/shelter_b1_north_maintenance_walkway_4", func_shelter_b1_north_maintenance_walkway_80180070);

INCLUDE_ASM("rooms/nonmatchings/shelter_b1_north_maintenance_walkway/shelter_b1_north_maintenance_walkway_4", func_shelter_b1_north_maintenance_walkway_801803E8);

INCLUDE_ASM("rooms/nonmatchings/shelter_b1_north_maintenance_walkway/shelter_b1_north_maintenance_walkway_4", func_shelter_b1_north_maintenance_walkway_80180DA8);

INCLUDE_ASM("rooms/nonmatchings/shelter_b1_north_maintenance_walkway/shelter_b1_north_maintenance_walkway_4", func_shelter_b1_north_maintenance_walkway_80180EDC);
