#include "common.h"

INCLUDE_ASM("rooms/nonmatchings/shelter_b1_sleeping_quarters/shelter_b1_sleeping_quarters_4", func_shelter_b1_sleeping_quarters_8017F894);

INCLUDE_ASM("rooms/nonmatchings/shelter_b1_sleeping_quarters/shelter_b1_sleeping_quarters_4", func_shelter_b1_sleeping_quarters_8017FA40);
