#ifndef SRC_ROOMS_DRYFIELD_NIGHT_MOTEL_ROOM_1_DRYFIELD_NIGHT_MOTEL_ROOM_1_PRIVATE_H
#define SRC_ROOMS_DRYFIELD_NIGHT_MOTEL_ROOM_1_DRYFIELD_NIGHT_MOTEL_ROOM_1_PRIVATE_H

#include <psyq/sys/types.h>
#include <psyq/libgte.h>

#include "types.h"

void func_dryfield_night_motel_room_1_8017D734(SVECTOR* arg0, s32 arg1, s32 arg2);

#endif // SRC_ROOMS_DRYFIELD_NIGHT_MOTEL_ROOM_1_DRYFIELD_NIGHT_MOTEL_ROOM_1_PRIVATE_H
