#ifndef SRC_ROOMS_DRYFIELD_NIGHT_MOTEL_ROOM_1_DRYFIELD_NIGHT_MOTEL_ROOM_1_PRIVATE_H
#define SRC_ROOMS_DRYFIELD_NIGHT_MOTEL_ROOM_1_DRYFIELD_NIGHT_MOTEL_ROOM_1_PRIVATE_H

#include <psyq/sys/types.h>
#include <psyq/libgte.h>

#include "types.h"

#endif // SRC_ROOMS_DRYFIELD_NIGHT_MOTEL_ROOM_1_DRYFIELD_NIGHT_MOTEL_ROOM_1_PRIVATE_H
