#include "common.h"

INCLUDE_RODATA("rooms/shelter_b3_incinerator_control_room/nonmatchings/shelter_b3_incinerator_control_room", D_shelter_b3_incinerator_control_room_8017D5C0);

INCLUDE_ASM("rooms/shelter_b3_incinerator_control_room/nonmatchings/shelter_b3_incinerator_control_room", func_shelter_b3_incinerator_control_room_8017D6CC);

INCLUDE_RODATA("rooms/shelter_b3_incinerator_control_room/nonmatchings/shelter_b3_incinerator_control_room", D_shelter_b3_incinerator_control_room_8017D610);

INCLUDE_ASM("rooms/shelter_b3_incinerator_control_room/nonmatchings/shelter_b3_incinerator_control_room", func_shelter_b3_incinerator_control_room_8017DE98);

INCLUDE_ASM("rooms/shelter_b3_incinerator_control_room/nonmatchings/shelter_b3_incinerator_control_room", func_shelter_b3_incinerator_control_room_8017E294);

INCLUDE_ASM("rooms/shelter_b3_incinerator_control_room/nonmatchings/shelter_b3_incinerator_control_room", func_shelter_b3_incinerator_control_room_8017E590);

INCLUDE_ASM("rooms/shelter_b3_incinerator_control_room/nonmatchings/shelter_b3_incinerator_control_room", func_shelter_b3_incinerator_control_room_8017E8B0);

INCLUDE_ASM("rooms/shelter_b3_incinerator_control_room/nonmatchings/shelter_b3_incinerator_control_room", func_shelter_b3_incinerator_control_room_8017EA64);

INCLUDE_ASM("rooms/shelter_b3_incinerator_control_room/nonmatchings/shelter_b3_incinerator_control_room", func_shelter_b3_incinerator_control_room_8017ED5C);

INCLUDE_ASM("rooms/shelter_b3_incinerator_control_room/nonmatchings/shelter_b3_incinerator_control_room", func_shelter_b3_incinerator_control_room_8017EDB8);

INCLUDE_ASM("rooms/shelter_b3_incinerator_control_room/nonmatchings/shelter_b3_incinerator_control_room", func_shelter_b3_incinerator_control_room_8017EE28);

INCLUDE_ASM("rooms/shelter_b3_incinerator_control_room/nonmatchings/shelter_b3_incinerator_control_room", func_shelter_b3_incinerator_control_room_8017EF1C);

INCLUDE_ASM("rooms/shelter_b3_incinerator_control_room/nonmatchings/shelter_b3_incinerator_control_room", func_shelter_b3_incinerator_control_room_8017F00C);

INCLUDE_ASM("rooms/shelter_b3_incinerator_control_room/nonmatchings/shelter_b3_incinerator_control_room", func_shelter_b3_incinerator_control_room_8017F110);

INCLUDE_ASM("rooms/shelter_b3_incinerator_control_room/nonmatchings/shelter_b3_incinerator_control_room", func_shelter_b3_incinerator_control_room_8017F1F4);

INCLUDE_ASM("rooms/shelter_b3_incinerator_control_room/nonmatchings/shelter_b3_incinerator_control_room", func_shelter_b3_incinerator_control_room_8017F2BC);

INCLUDE_ASM("rooms/shelter_b3_incinerator_control_room/nonmatchings/shelter_b3_incinerator_control_room", func_shelter_b3_incinerator_control_room_8017F384);

INCLUDE_ASM("rooms/shelter_b3_incinerator_control_room/nonmatchings/shelter_b3_incinerator_control_room", func_shelter_b3_incinerator_control_room_8017F44C);

INCLUDE_ASM("rooms/shelter_b3_incinerator_control_room/nonmatchings/shelter_b3_incinerator_control_room", func_shelter_b3_incinerator_control_room_8017F488);

INCLUDE_ASM("rooms/shelter_b3_incinerator_control_room/nonmatchings/shelter_b3_incinerator_control_room", func_shelter_b3_incinerator_control_room_8017F9F4);

INCLUDE_ASM("rooms/shelter_b3_incinerator_control_room/nonmatchings/shelter_b3_incinerator_control_room", func_shelter_b3_incinerator_control_room_8017FA84);

INCLUDE_ASM("rooms/shelter_b3_incinerator_control_room/nonmatchings/shelter_b3_incinerator_control_room", func_shelter_b3_incinerator_control_room_8017FA8C);

INCLUDE_ASM("rooms/shelter_b3_incinerator_control_room/nonmatchings/shelter_b3_incinerator_control_room", func_shelter_b3_incinerator_control_room_8017FB20);

INCLUDE_ASM("rooms/shelter_b3_incinerator_control_room/nonmatchings/shelter_b3_incinerator_control_room", func_shelter_b3_incinerator_control_room_8017FBE0);

INCLUDE_ASM("rooms/shelter_b3_incinerator_control_room/nonmatchings/shelter_b3_incinerator_control_room", func_shelter_b3_incinerator_control_room_8017FBE8);

INCLUDE_ASM("rooms/shelter_b3_incinerator_control_room/nonmatchings/shelter_b3_incinerator_control_room", func_shelter_b3_incinerator_control_room_8017FC1C);

INCLUDE_ASM("rooms/shelter_b3_incinerator_control_room/nonmatchings/shelter_b3_incinerator_control_room", func_shelter_b3_incinerator_control_room_8017FCA8);

INCLUDE_ASM("rooms/shelter_b3_incinerator_control_room/nonmatchings/shelter_b3_incinerator_control_room", func_shelter_b3_incinerator_control_room_8017FCB8);

INCLUDE_ASM("rooms/shelter_b3_incinerator_control_room/nonmatchings/shelter_b3_incinerator_control_room", func_shelter_b3_incinerator_control_room_8017FD10);

INCLUDE_ASM("rooms/shelter_b3_incinerator_control_room/nonmatchings/shelter_b3_incinerator_control_room", func_shelter_b3_incinerator_control_room_8017FEB4);

INCLUDE_ASM("rooms/shelter_b3_incinerator_control_room/nonmatchings/shelter_b3_incinerator_control_room", func_shelter_b3_incinerator_control_room_801806F8);

INCLUDE_ASM("rooms/shelter_b3_incinerator_control_room/nonmatchings/shelter_b3_incinerator_control_room", func_shelter_b3_incinerator_control_room_80180B6C);
