#include "common.h"

INCLUDE_RODATA("rooms/nonmatchings/shelter_b3_incinerator_control_room/shelter_b3_incinerator_control_room", D_shelter_b3_incinerator_control_room_8017D610);

INCLUDE_ASM("rooms/nonmatchings/shelter_b3_incinerator_control_room/shelter_b3_incinerator_control_room", func_shelter_b3_incinerator_control_room_8017DE98);

INCLUDE_ASM("rooms/nonmatchings/shelter_b3_incinerator_control_room/shelter_b3_incinerator_control_room", func_shelter_b3_incinerator_control_room_8017E294);

INCLUDE_ASM("rooms/nonmatchings/shelter_b3_incinerator_control_room/shelter_b3_incinerator_control_room", func_shelter_b3_incinerator_control_room_8017E590);

INCLUDE_ASM("rooms/nonmatchings/shelter_b3_incinerator_control_room/shelter_b3_incinerator_control_room", func_shelter_b3_incinerator_control_room_8017E8B0);

INCLUDE_ASM("rooms/nonmatchings/shelter_b3_incinerator_control_room/shelter_b3_incinerator_control_room", func_shelter_b3_incinerator_control_room_8017EA64);

INCLUDE_ASM("rooms/nonmatchings/shelter_b3_incinerator_control_room/shelter_b3_incinerator_control_room", func_shelter_b3_incinerator_control_room_8017ED5C);
