#include "common.h"

INCLUDE_ASM("rooms/nonmatchings/shelter_b3_incinerator_control_room/shelter_b3_incinerator_control_room_3", func_shelter_b3_incinerator_control_room_8017F9F4);

INCLUDE_ASM("rooms/nonmatchings/shelter_b3_incinerator_control_room/shelter_b3_incinerator_control_room_3", func_shelter_b3_incinerator_control_room_8017FA84);

INCLUDE_ASM("rooms/nonmatchings/shelter_b3_incinerator_control_room/shelter_b3_incinerator_control_room_3", func_shelter_b3_incinerator_control_room_8017FA8C);

INCLUDE_ASM("rooms/nonmatchings/shelter_b3_incinerator_control_room/shelter_b3_incinerator_control_room_3", func_shelter_b3_incinerator_control_room_8017FB20);

INCLUDE_ASM("rooms/nonmatchings/shelter_b3_incinerator_control_room/shelter_b3_incinerator_control_room_3", func_shelter_b3_incinerator_control_room_8017FBE0);

INCLUDE_ASM("rooms/nonmatchings/shelter_b3_incinerator_control_room/shelter_b3_incinerator_control_room_3", func_shelter_b3_incinerator_control_room_8017FBE8);

INCLUDE_ASM("rooms/nonmatchings/shelter_b3_incinerator_control_room/shelter_b3_incinerator_control_room_3", func_shelter_b3_incinerator_control_room_8017FC1C);

INCLUDE_ASM("rooms/nonmatchings/shelter_b3_incinerator_control_room/shelter_b3_incinerator_control_room_3", func_shelter_b3_incinerator_control_room_8017FCA8);

INCLUDE_ASM("rooms/nonmatchings/shelter_b3_incinerator_control_room/shelter_b3_incinerator_control_room_3", func_shelter_b3_incinerator_control_room_8017FCB8);

INCLUDE_ASM("rooms/nonmatchings/shelter_b3_incinerator_control_room/shelter_b3_incinerator_control_room_3", func_shelter_b3_incinerator_control_room_8017FD10);

INCLUDE_ASM("rooms/nonmatchings/shelter_b3_incinerator_control_room/shelter_b3_incinerator_control_room_3", func_shelter_b3_incinerator_control_room_8017FEB4);

INCLUDE_ASM("rooms/nonmatchings/shelter_b3_incinerator_control_room/shelter_b3_incinerator_control_room_3", func_shelter_b3_incinerator_control_room_801806F8);

INCLUDE_ASM("rooms/nonmatchings/shelter_b3_incinerator_control_room/shelter_b3_incinerator_control_room_3", func_shelter_b3_incinerator_control_room_80180B6C);
