#include "common.h"

INCLUDE_ASM("rooms/nonmatchings/shelter_b3_incinerator_control_room/shelter_b3_incinerator_control_room_6", func_shelter_b3_incinerator_control_room_8017FCB8);

INCLUDE_ASM("rooms/nonmatchings/shelter_b3_incinerator_control_room/shelter_b3_incinerator_control_room_6", func_shelter_b3_incinerator_control_room_8017FD10);
