#include "common.h"

INCLUDE_RODATA("rooms/shelter_b1_underground_parking/nonmatchings/shelter_b1_underground_parking", D_shelter_b1_underground_parking_8017D5C0);

INCLUDE_ASM("rooms/shelter_b1_underground_parking/nonmatchings/shelter_b1_underground_parking", func_shelter_b1_underground_parking_8017DA50);

INCLUDE_RODATA("rooms/shelter_b1_underground_parking/nonmatchings/shelter_b1_underground_parking", D_shelter_b1_underground_parking_8017D610);

INCLUDE_ASM("rooms/shelter_b1_underground_parking/nonmatchings/shelter_b1_underground_parking", func_shelter_b1_underground_parking_8017E21C);

INCLUDE_ASM("rooms/shelter_b1_underground_parking/nonmatchings/shelter_b1_underground_parking", func_shelter_b1_underground_parking_8017E618);

INCLUDE_ASM("rooms/shelter_b1_underground_parking/nonmatchings/shelter_b1_underground_parking", func_shelter_b1_underground_parking_8017E914);

INCLUDE_ASM("rooms/shelter_b1_underground_parking/nonmatchings/shelter_b1_underground_parking", func_shelter_b1_underground_parking_8017EC34);

INCLUDE_ASM("rooms/shelter_b1_underground_parking/nonmatchings/shelter_b1_underground_parking", func_shelter_b1_underground_parking_8017EDE8);

INCLUDE_ASM("rooms/shelter_b1_underground_parking/nonmatchings/shelter_b1_underground_parking", func_shelter_b1_underground_parking_8017F0E0);

INCLUDE_ASM("rooms/shelter_b1_underground_parking/nonmatchings/shelter_b1_underground_parking", func_shelter_b1_underground_parking_8017F13C);

INCLUDE_ASM("rooms/shelter_b1_underground_parking/nonmatchings/shelter_b1_underground_parking", func_shelter_b1_underground_parking_8017F1AC);

INCLUDE_ASM("rooms/shelter_b1_underground_parking/nonmatchings/shelter_b1_underground_parking", func_shelter_b1_underground_parking_8017F2A0);

INCLUDE_ASM("rooms/shelter_b1_underground_parking/nonmatchings/shelter_b1_underground_parking", func_shelter_b1_underground_parking_8017F390);

INCLUDE_ASM("rooms/shelter_b1_underground_parking/nonmatchings/shelter_b1_underground_parking", func_shelter_b1_underground_parking_8017F494);

INCLUDE_ASM("rooms/shelter_b1_underground_parking/nonmatchings/shelter_b1_underground_parking", func_shelter_b1_underground_parking_8017F578);

INCLUDE_ASM("rooms/shelter_b1_underground_parking/nonmatchings/shelter_b1_underground_parking", func_shelter_b1_underground_parking_8017F640);

INCLUDE_ASM("rooms/shelter_b1_underground_parking/nonmatchings/shelter_b1_underground_parking", func_shelter_b1_underground_parking_8017F708);

INCLUDE_ASM("rooms/shelter_b1_underground_parking/nonmatchings/shelter_b1_underground_parking", func_shelter_b1_underground_parking_8017F7D0);

INCLUDE_ASM("rooms/shelter_b1_underground_parking/nonmatchings/shelter_b1_underground_parking", func_shelter_b1_underground_parking_8017F80C);

INCLUDE_ASM("rooms/shelter_b1_underground_parking/nonmatchings/shelter_b1_underground_parking", func_shelter_b1_underground_parking_8017FE7C);

INCLUDE_ASM("rooms/shelter_b1_underground_parking/nonmatchings/shelter_b1_underground_parking", func_shelter_b1_underground_parking_80180308);

INCLUDE_ASM("rooms/shelter_b1_underground_parking/nonmatchings/shelter_b1_underground_parking", func_shelter_b1_underground_parking_80180454);

INCLUDE_ASM("rooms/shelter_b1_underground_parking/nonmatchings/shelter_b1_underground_parking", func_shelter_b1_underground_parking_80180820);

INCLUDE_ASM("rooms/shelter_b1_underground_parking/nonmatchings/shelter_b1_underground_parking", func_shelter_b1_underground_parking_80180A70);

INCLUDE_RODATA("rooms/shelter_b1_underground_parking/nonmatchings/shelter_b1_underground_parking", D_shelter_b1_underground_parking_8017D758);

INCLUDE_ASM("rooms/shelter_b1_underground_parking/nonmatchings/shelter_b1_underground_parking", func_shelter_b1_underground_parking_80180C90);

INCLUDE_ASM("rooms/shelter_b1_underground_parking/nonmatchings/shelter_b1_underground_parking", func_shelter_b1_underground_parking_80180E38);

INCLUDE_ASM("rooms/shelter_b1_underground_parking/nonmatchings/shelter_b1_underground_parking", func_shelter_b1_underground_parking_8018101C);

INCLUDE_ASM("rooms/shelter_b1_underground_parking/nonmatchings/shelter_b1_underground_parking", func_shelter_b1_underground_parking_80181230);

INCLUDE_ASM("rooms/shelter_b1_underground_parking/nonmatchings/shelter_b1_underground_parking", func_shelter_b1_underground_parking_801813B0);

INCLUDE_ASM("rooms/shelter_b1_underground_parking/nonmatchings/shelter_b1_underground_parking", func_shelter_b1_underground_parking_80181678);

INCLUDE_ASM("rooms/shelter_b1_underground_parking/nonmatchings/shelter_b1_underground_parking", func_shelter_b1_underground_parking_8018184C);

INCLUDE_ASM("rooms/shelter_b1_underground_parking/nonmatchings/shelter_b1_underground_parking", func_shelter_b1_underground_parking_80181CCC);

INCLUDE_ASM("rooms/shelter_b1_underground_parking/nonmatchings/shelter_b1_underground_parking", func_shelter_b1_underground_parking_80181D88);

INCLUDE_ASM("rooms/shelter_b1_underground_parking/nonmatchings/shelter_b1_underground_parking", func_shelter_b1_underground_parking_80181EB0);

INCLUDE_ASM("rooms/shelter_b1_underground_parking/nonmatchings/shelter_b1_underground_parking", func_shelter_b1_underground_parking_80181FE4);

INCLUDE_ASM("rooms/shelter_b1_underground_parking/nonmatchings/shelter_b1_underground_parking", func_shelter_b1_underground_parking_80182154);

INCLUDE_ASM("rooms/shelter_b1_underground_parking/nonmatchings/shelter_b1_underground_parking", func_shelter_b1_underground_parking_801826C0);

INCLUDE_RODATA("rooms/shelter_b1_underground_parking/nonmatchings/shelter_b1_underground_parking", D_shelter_b1_underground_parking_8017D7F4);

INCLUDE_ASM("rooms/shelter_b1_underground_parking/nonmatchings/shelter_b1_underground_parking", func_shelter_b1_underground_parking_80182830);

INCLUDE_ASM("rooms/shelter_b1_underground_parking/nonmatchings/shelter_b1_underground_parking", func_shelter_b1_underground_parking_80182A60);

INCLUDE_ASM("rooms/shelter_b1_underground_parking/nonmatchings/shelter_b1_underground_parking", func_shelter_b1_underground_parking_80182DB4);

INCLUDE_ASM("rooms/shelter_b1_underground_parking/nonmatchings/shelter_b1_underground_parking", func_shelter_b1_underground_parking_80182FC8);

INCLUDE_ASM("rooms/shelter_b1_underground_parking/nonmatchings/shelter_b1_underground_parking", func_shelter_b1_underground_parking_80183124);

INCLUDE_ASM("rooms/shelter_b1_underground_parking/nonmatchings/shelter_b1_underground_parking", func_shelter_b1_underground_parking_801831F4);

INCLUDE_ASM("rooms/shelter_b1_underground_parking/nonmatchings/shelter_b1_underground_parking", func_shelter_b1_underground_parking_80183284);

INCLUDE_ASM("rooms/shelter_b1_underground_parking/nonmatchings/shelter_b1_underground_parking", func_shelter_b1_underground_parking_80183360);

INCLUDE_ASM("rooms/shelter_b1_underground_parking/nonmatchings/shelter_b1_underground_parking", func_shelter_b1_underground_parking_801833DC);

INCLUDE_ASM("rooms/shelter_b1_underground_parking/nonmatchings/shelter_b1_underground_parking", func_shelter_b1_underground_parking_80183410);

INCLUDE_ASM("rooms/shelter_b1_underground_parking/nonmatchings/shelter_b1_underground_parking", func_shelter_b1_underground_parking_801834D4);

INCLUDE_ASM("rooms/shelter_b1_underground_parking/nonmatchings/shelter_b1_underground_parking", func_shelter_b1_underground_parking_80183560);

INCLUDE_ASM("rooms/shelter_b1_underground_parking/nonmatchings/shelter_b1_underground_parking", func_shelter_b1_underground_parking_8018363C);

INCLUDE_ASM("rooms/shelter_b1_underground_parking/nonmatchings/shelter_b1_underground_parking", func_shelter_b1_underground_parking_801836D8);

INCLUDE_ASM("rooms/shelter_b1_underground_parking/nonmatchings/shelter_b1_underground_parking", func_shelter_b1_underground_parking_80183714);

INCLUDE_ASM("rooms/shelter_b1_underground_parking/nonmatchings/shelter_b1_underground_parking", func_shelter_b1_underground_parking_801837D8);

INCLUDE_ASM("rooms/shelter_b1_underground_parking/nonmatchings/shelter_b1_underground_parking", func_shelter_b1_underground_parking_80183804);

INCLUDE_ASM("rooms/shelter_b1_underground_parking/nonmatchings/shelter_b1_underground_parking", func_shelter_b1_underground_parking_80183810);

INCLUDE_ASM("rooms/shelter_b1_underground_parking/nonmatchings/shelter_b1_underground_parking", func_shelter_b1_underground_parking_801838B4);

INCLUDE_ASM("rooms/shelter_b1_underground_parking/nonmatchings/shelter_b1_underground_parking", func_shelter_b1_underground_parking_8018390C);

INCLUDE_ASM("rooms/shelter_b1_underground_parking/nonmatchings/shelter_b1_underground_parking", func_shelter_b1_underground_parking_80183958);

INCLUDE_ASM("rooms/shelter_b1_underground_parking/nonmatchings/shelter_b1_underground_parking", func_shelter_b1_underground_parking_80183B9C);

INCLUDE_RODATA("rooms/shelter_b1_underground_parking/nonmatchings/shelter_b1_underground_parking", D_shelter_b1_underground_parking_8017D9A4);

INCLUDE_ASM("rooms/shelter_b1_underground_parking/nonmatchings/shelter_b1_underground_parking", func_shelter_b1_underground_parking_80183CEC);

INCLUDE_ASM("rooms/shelter_b1_underground_parking/nonmatchings/shelter_b1_underground_parking", func_shelter_b1_underground_parking_8018414C);

INCLUDE_ASM("rooms/shelter_b1_underground_parking/nonmatchings/shelter_b1_underground_parking", func_shelter_b1_underground_parking_80184234);

INCLUDE_ASM("rooms/shelter_b1_underground_parking/nonmatchings/shelter_b1_underground_parking", func_shelter_b1_underground_parking_80184284);

INCLUDE_ASM("rooms/shelter_b1_underground_parking/nonmatchings/shelter_b1_underground_parking", func_shelter_b1_underground_parking_80184304);

INCLUDE_ASM("rooms/shelter_b1_underground_parking/nonmatchings/shelter_b1_underground_parking", func_shelter_b1_underground_parking_801843F0);

INCLUDE_ASM("rooms/shelter_b1_underground_parking/nonmatchings/shelter_b1_underground_parking", func_shelter_b1_underground_parking_80184468);

INCLUDE_ASM("rooms/shelter_b1_underground_parking/nonmatchings/shelter_b1_underground_parking", func_shelter_b1_underground_parking_80184594);

INCLUDE_ASM("rooms/shelter_b1_underground_parking/nonmatchings/shelter_b1_underground_parking", func_shelter_b1_underground_parking_801845F8);

INCLUDE_ASM("rooms/shelter_b1_underground_parking/nonmatchings/shelter_b1_underground_parking", func_shelter_b1_underground_parking_801846EC);

INCLUDE_ASM("rooms/shelter_b1_underground_parking/nonmatchings/shelter_b1_underground_parking", func_shelter_b1_underground_parking_80184778);

INCLUDE_ASM("rooms/shelter_b1_underground_parking/nonmatchings/shelter_b1_underground_parking", func_shelter_b1_underground_parking_801847D0);

INCLUDE_ASM("rooms/shelter_b1_underground_parking/nonmatchings/shelter_b1_underground_parking", func_shelter_b1_underground_parking_801848A4);

INCLUDE_ASM("rooms/shelter_b1_underground_parking/nonmatchings/shelter_b1_underground_parking", func_shelter_b1_underground_parking_801848BC);

INCLUDE_ASM("rooms/shelter_b1_underground_parking/nonmatchings/shelter_b1_underground_parking", func_shelter_b1_underground_parking_8018491C);

INCLUDE_ASM("rooms/shelter_b1_underground_parking/nonmatchings/shelter_b1_underground_parking", func_shelter_b1_underground_parking_80184964);

INCLUDE_ASM("rooms/shelter_b1_underground_parking/nonmatchings/shelter_b1_underground_parking", func_shelter_b1_underground_parking_80184A18);

INCLUDE_ASM("rooms/shelter_b1_underground_parking/nonmatchings/shelter_b1_underground_parking", func_shelter_b1_underground_parking_80184C54);

INCLUDE_ASM("rooms/shelter_b1_underground_parking/nonmatchings/shelter_b1_underground_parking", func_shelter_b1_underground_parking_8018543C);

INCLUDE_ASM("rooms/shelter_b1_underground_parking/nonmatchings/shelter_b1_underground_parking", func_shelter_b1_underground_parking_801857E0);

INCLUDE_ASM("rooms/shelter_b1_underground_parking/nonmatchings/shelter_b1_underground_parking", func_shelter_b1_underground_parking_80185A94);

INCLUDE_ASM("rooms/shelter_b1_underground_parking/nonmatchings/shelter_b1_underground_parking", func_shelter_b1_underground_parking_80185F08);

INCLUDE_ASM("rooms/shelter_b1_underground_parking/nonmatchings/shelter_b1_underground_parking", func_shelter_b1_underground_parking_80186890);
