#include "common.h"

INCLUDE_ASM("rooms/nonmatchings/shelter_b1_underground_parking/shelter_b1_underground_parking_11", func_shelter_b1_underground_parking_8018491C);

INCLUDE_RODATA("rooms/nonmatchings/shelter_b1_underground_parking/shelter_b1_underground_parking_11", jtbl_shelter_b1_underground_parking_8017D9F4);
