#include "common.h"

INCLUDE_ASM("rooms/nonmatchings/dryfield_night_saloon_g_r/dryfield_night_saloon_g_r_3", func_dryfield_night_saloon_g_r_8017E050);

INCLUDE_ASM("rooms/nonmatchings/dryfield_night_saloon_g_r/dryfield_night_saloon_g_r_3", func_dryfield_night_saloon_g_r_8017E0A8);

INCLUDE_ASM("rooms/nonmatchings/dryfield_night_saloon_g_r/dryfield_night_saloon_g_r_3", func_dryfield_night_saloon_g_r_8017E0C0);

INCLUDE_ASM("rooms/nonmatchings/dryfield_night_saloon_g_r/dryfield_night_saloon_g_r_3", func_dryfield_night_saloon_g_r_8017E28C);

INCLUDE_ASM("rooms/nonmatchings/dryfield_night_saloon_g_r/dryfield_night_saloon_g_r_3", func_dryfield_night_saloon_g_r_8017E564);

INCLUDE_ASM("rooms/nonmatchings/dryfield_night_saloon_g_r/dryfield_night_saloon_g_r_3", func_dryfield_night_saloon_g_r_8017E698);

INCLUDE_ASM("rooms/nonmatchings/dryfield_night_saloon_g_r/dryfield_night_saloon_g_r_3", func_dryfield_night_saloon_g_r_8017E6C8);
