#include "common.h"

INCLUDE_RODATA("rooms/shelter_b1_south_maintenance_walkway/nonmatchings/shelter_b1_south_maintenance_walkway", D_shelter_b1_south_maintenance_walkway_8017D5C0);

INCLUDE_ASM("rooms/shelter_b1_south_maintenance_walkway/nonmatchings/shelter_b1_south_maintenance_walkway", func_shelter_b1_south_maintenance_walkway_8017D5F8);

INCLUDE_ASM("rooms/shelter_b1_south_maintenance_walkway/nonmatchings/shelter_b1_south_maintenance_walkway", func_shelter_b1_south_maintenance_walkway_8017D790);

INCLUDE_ASM("rooms/shelter_b1_south_maintenance_walkway/nonmatchings/shelter_b1_south_maintenance_walkway", func_shelter_b1_south_maintenance_walkway_8017D9D0);

INCLUDE_ASM("rooms/shelter_b1_south_maintenance_walkway/nonmatchings/shelter_b1_south_maintenance_walkway", func_shelter_b1_south_maintenance_walkway_8017D9D8);

INCLUDE_ASM("rooms/shelter_b1_south_maintenance_walkway/nonmatchings/shelter_b1_south_maintenance_walkway", func_shelter_b1_south_maintenance_walkway_8017D9E0);

INCLUDE_ASM("rooms/shelter_b1_south_maintenance_walkway/nonmatchings/shelter_b1_south_maintenance_walkway", func_shelter_b1_south_maintenance_walkway_8017D9E8);

void func_shelter_b1_south_maintenance_walkway_8017DA2C(void) {
}

INCLUDE_ASM("rooms/shelter_b1_south_maintenance_walkway/nonmatchings/shelter_b1_south_maintenance_walkway", func_shelter_b1_south_maintenance_walkway_8017DA34);

INCLUDE_ASM("rooms/shelter_b1_south_maintenance_walkway/nonmatchings/shelter_b1_south_maintenance_walkway", func_shelter_b1_south_maintenance_walkway_8017DA8C);

INCLUDE_ASM("rooms/shelter_b1_south_maintenance_walkway/nonmatchings/shelter_b1_south_maintenance_walkway", func_shelter_b1_south_maintenance_walkway_8017DC88);

INCLUDE_ASM("rooms/shelter_b1_south_maintenance_walkway/nonmatchings/shelter_b1_south_maintenance_walkway", func_shelter_b1_south_maintenance_walkway_8017E404);

INCLUDE_ASM("rooms/shelter_b1_south_maintenance_walkway/nonmatchings/shelter_b1_south_maintenance_walkway", func_shelter_b1_south_maintenance_walkway_8017E760);

INCLUDE_ASM("rooms/shelter_b1_south_maintenance_walkway/nonmatchings/shelter_b1_south_maintenance_walkway", func_shelter_b1_south_maintenance_walkway_8017EA04);

INCLUDE_ASM("rooms/shelter_b1_south_maintenance_walkway/nonmatchings/shelter_b1_south_maintenance_walkway", func_shelter_b1_south_maintenance_walkway_8017EE30);

INCLUDE_ASM("rooms/shelter_b1_south_maintenance_walkway/nonmatchings/shelter_b1_south_maintenance_walkway", func_shelter_b1_south_maintenance_walkway_8017F1C4);

INCLUDE_ASM("rooms/shelter_b1_south_maintenance_walkway/nonmatchings/shelter_b1_south_maintenance_walkway", func_shelter_b1_south_maintenance_walkway_8017F6B4);

INCLUDE_ASM("rooms/shelter_b1_south_maintenance_walkway/nonmatchings/shelter_b1_south_maintenance_walkway", func_shelter_b1_south_maintenance_walkway_8017FAAC);

INCLUDE_ASM("rooms/shelter_b1_south_maintenance_walkway/nonmatchings/shelter_b1_south_maintenance_walkway", func_shelter_b1_south_maintenance_walkway_8017FD34);

INCLUDE_ASM("rooms/shelter_b1_south_maintenance_walkway/nonmatchings/shelter_b1_south_maintenance_walkway", func_shelter_b1_south_maintenance_walkway_801806F4);

INCLUDE_ASM("rooms/shelter_b1_south_maintenance_walkway/nonmatchings/shelter_b1_south_maintenance_walkway", func_shelter_b1_south_maintenance_walkway_80180C4C);

INCLUDE_ASM("rooms/shelter_b1_south_maintenance_walkway/nonmatchings/shelter_b1_south_maintenance_walkway", func_shelter_b1_south_maintenance_walkway_80180E70);

INCLUDE_ASM("rooms/shelter_b1_south_maintenance_walkway/nonmatchings/shelter_b1_south_maintenance_walkway", func_shelter_b1_south_maintenance_walkway_801810F4);

INCLUDE_ASM("rooms/shelter_b1_south_maintenance_walkway/nonmatchings/shelter_b1_south_maintenance_walkway", func_shelter_b1_south_maintenance_walkway_80181518);

INCLUDE_ASM("rooms/shelter_b1_south_maintenance_walkway/nonmatchings/shelter_b1_south_maintenance_walkway", func_shelter_b1_south_maintenance_walkway_801818AC);

INCLUDE_ASM("rooms/shelter_b1_south_maintenance_walkway/nonmatchings/shelter_b1_south_maintenance_walkway", func_shelter_b1_south_maintenance_walkway_80181A58);

INCLUDE_ASM("rooms/shelter_b1_south_maintenance_walkway/nonmatchings/shelter_b1_south_maintenance_walkway", func_shelter_b1_south_maintenance_walkway_80181F84);
