#include "common.h"

INCLUDE_ASM("rooms/nonmatchings/shelter_b1_south_maintenance_walkway/shelter_b1_south_maintenance_walkway_5", func_shelter_b1_south_maintenance_walkway_801818AC);

INCLUDE_ASM("rooms/nonmatchings/shelter_b1_south_maintenance_walkway/shelter_b1_south_maintenance_walkway_5", func_shelter_b1_south_maintenance_walkway_80181A58);
