#include "common.h"

INCLUDE_ASM("rooms/nonmatchings/dryfield_night_trailer_coach/dryfield_night_trailer_coach_5", func_dryfield_night_trailer_coach_80181DB0);

INCLUDE_RODATA("rooms/nonmatchings/dryfield_night_trailer_coach/dryfield_night_trailer_coach_5", D_dryfield_night_trailer_coach_8017D7DC);
