#include "common.h"

INCLUDE_ASM("rooms/nonmatchings/dryfield_night_trailer_coach/dryfield_night_trailer_coach_4", func_dryfield_night_trailer_coach_80181A38);

INCLUDE_ASM("rooms/nonmatchings/dryfield_night_trailer_coach/dryfield_night_trailer_coach_4", func_dryfield_night_trailer_coach_80181B1C);

INCLUDE_ASM("rooms/nonmatchings/dryfield_night_trailer_coach/dryfield_night_trailer_coach_4", func_dryfield_night_trailer_coach_80181BE4);

INCLUDE_ASM("rooms/nonmatchings/dryfield_night_trailer_coach/dryfield_night_trailer_coach_4", func_dryfield_night_trailer_coach_80181CAC);
