#include "common.h"

INCLUDE_ASM("rooms/nonmatchings/dryfield_night_motel_lobby/dryfield_night_motel_lobby_9", func_dryfield_night_motel_lobby_80180D08);

INCLUDE_ASM("rooms/nonmatchings/dryfield_night_motel_lobby/dryfield_night_motel_lobby_9", func_dryfield_night_motel_lobby_80180D58);

INCLUDE_ASM("rooms/nonmatchings/dryfield_night_motel_lobby/dryfield_night_motel_lobby_9", func_dryfield_night_motel_lobby_80180DE4);

INCLUDE_ASM("rooms/nonmatchings/dryfield_night_motel_lobby/dryfield_night_motel_lobby_9", func_dryfield_night_motel_lobby_80180E98);
