#include "common.h"

INCLUDE_ASM("rooms/nonmatchings/dryfield_night_motel_lobby/dryfield_night_motel_lobby_3", func_dryfield_night_motel_lobby_8017F18C);

INCLUDE_ASM("rooms/nonmatchings/dryfield_night_motel_lobby/dryfield_night_motel_lobby_3", func_dryfield_night_motel_lobby_8017F270);

INCLUDE_ASM("rooms/nonmatchings/dryfield_night_motel_lobby/dryfield_night_motel_lobby_3", func_dryfield_night_motel_lobby_8017F338);

INCLUDE_ASM("rooms/nonmatchings/dryfield_night_motel_lobby/dryfield_night_motel_lobby_3", func_dryfield_night_motel_lobby_8017F400);

INCLUDE_RODATA("rooms/nonmatchings/dryfield_night_motel_lobby/dryfield_night_motel_lobby_3", D_dryfield_night_motel_lobby_8017D6A4);

INCLUDE_RODATA("rooms/nonmatchings/dryfield_night_motel_lobby/dryfield_night_motel_lobby_3", D_dryfield_night_motel_lobby_8017D6B0);

INCLUDE_RODATA("rooms/nonmatchings/dryfield_night_motel_lobby/dryfield_night_motel_lobby_3", jtbl_dryfield_night_motel_lobby_8017D6E0);

INCLUDE_RODATA("rooms/nonmatchings/dryfield_night_motel_lobby/dryfield_night_motel_lobby_3", jtbl_dryfield_night_motel_lobby_8017D718);
