#include "common.h"

INCLUDE_ASM("rooms/nonmatchings/shelter_b2_pod_access_tunnel/shelter_b2_pod_access_tunnel_5", func_shelter_b2_pod_access_tunnel_80181138);

INCLUDE_ASM("rooms/nonmatchings/shelter_b2_pod_access_tunnel/shelter_b2_pod_access_tunnel_5", func_shelter_b2_pod_access_tunnel_80181AF8);

INCLUDE_ASM("rooms/nonmatchings/shelter_b2_pod_access_tunnel/shelter_b2_pod_access_tunnel_5", func_shelter_b2_pod_access_tunnel_80181C2C);
