#include "common.h"

INCLUDE_RODATA("rooms/nonmatchings/dryfield_night_main_street/dryfield_night_main_street", D_dryfield_night_main_street_8017D5C0);

INCLUDE_ASM("rooms/nonmatchings/dryfield_night_main_street/dryfield_night_main_street", func_dryfield_night_main_street_8017D600);

INCLUDE_ASM("rooms/nonmatchings/dryfield_night_main_street/dryfield_night_main_street", func_dryfield_night_main_street_8017D798);

INCLUDE_ASM("rooms/nonmatchings/dryfield_night_main_street/dryfield_night_main_street", func_dryfield_night_main_street_8017D8FC);

INCLUDE_ASM("rooms/nonmatchings/dryfield_night_main_street/dryfield_night_main_street", func_dryfield_night_main_street_8017DA6C);

INCLUDE_RODATA("rooms/nonmatchings/dryfield_night_main_street/dryfield_night_main_street", RoomsShared8017d878Table);
