#ifndef SRC_ROOMS_DRYFIELD_NIGHT_MOTEL_ROOM_5_DRYFIELD_NIGHT_MOTEL_ROOM_5_PRIVATE_H
#define SRC_ROOMS_DRYFIELD_NIGHT_MOTEL_ROOM_5_DRYFIELD_NIGHT_MOTEL_ROOM_5_PRIVATE_H

#include <psyq/sys/types.h>
#include <psyq/libgte.h>

#include "types.h"

#endif // SRC_ROOMS_DRYFIELD_NIGHT_MOTEL_ROOM_5_DRYFIELD_NIGHT_MOTEL_ROOM_5_PRIVATE_H
