#include "common.h"

INCLUDE_ASM("rooms/acropolis_helicopter_landing_pad/nonmatchings/acropolis_helicopter_landing_pad", func_acropolis_helicopter_landing_pad_8017D658);

INCLUDE_ASM("rooms/acropolis_helicopter_landing_pad/nonmatchings/acropolis_helicopter_landing_pad", func_acropolis_helicopter_landing_pad_8017D6E0);

INCLUDE_ASM("rooms/acropolis_helicopter_landing_pad/nonmatchings/acropolis_helicopter_landing_pad", func_acropolis_helicopter_landing_pad_8017D7B0);

INCLUDE_ASM("rooms/acropolis_helicopter_landing_pad/nonmatchings/acropolis_helicopter_landing_pad", func_acropolis_helicopter_landing_pad_8017D824);

INCLUDE_ASM("rooms/acropolis_helicopter_landing_pad/nonmatchings/acropolis_helicopter_landing_pad", func_acropolis_helicopter_landing_pad_8017D8E8);

INCLUDE_RODATA("rooms/acropolis_helicopter_landing_pad/nonmatchings/acropolis_helicopter_landing_pad", D_acropolis_helicopter_landing_pad_8017D5C0);

INCLUDE_ASM("rooms/acropolis_helicopter_landing_pad/nonmatchings/acropolis_helicopter_landing_pad", func_acropolis_helicopter_landing_pad_8017D964);

INCLUDE_ASM("rooms/acropolis_helicopter_landing_pad/nonmatchings/acropolis_helicopter_landing_pad", func_acropolis_helicopter_landing_pad_8017D9BC);

INCLUDE_RODATA("rooms/acropolis_helicopter_landing_pad/nonmatchings/acropolis_helicopter_landing_pad", D_acropolis_helicopter_landing_pad_8017D5E4);

INCLUDE_ASM("rooms/acropolis_helicopter_landing_pad/nonmatchings/acropolis_helicopter_landing_pad", func_acropolis_helicopter_landing_pad_8017DA9C);

INCLUDE_ASM("rooms/acropolis_helicopter_landing_pad/nonmatchings/acropolis_helicopter_landing_pad", func_acropolis_helicopter_landing_pad_8017DE78);

INCLUDE_ASM("rooms/acropolis_helicopter_landing_pad/nonmatchings/acropolis_helicopter_landing_pad", func_acropolis_helicopter_landing_pad_8017DFCC);

INCLUDE_ASM("rooms/acropolis_helicopter_landing_pad/nonmatchings/acropolis_helicopter_landing_pad", func_acropolis_helicopter_landing_pad_8017E0F8);

INCLUDE_ASM("rooms/acropolis_helicopter_landing_pad/nonmatchings/acropolis_helicopter_landing_pad", func_acropolis_helicopter_landing_pad_8017E270);

INCLUDE_ASM("rooms/acropolis_helicopter_landing_pad/nonmatchings/acropolis_helicopter_landing_pad", func_acropolis_helicopter_landing_pad_8017E3F0);

INCLUDE_ASM("rooms/acropolis_helicopter_landing_pad/nonmatchings/acropolis_helicopter_landing_pad", func_acropolis_helicopter_landing_pad_8017E49C);

INCLUDE_ASM("rooms/acropolis_helicopter_landing_pad/nonmatchings/acropolis_helicopter_landing_pad", func_acropolis_helicopter_landing_pad_8017E4A4);

INCLUDE_ASM("rooms/acropolis_helicopter_landing_pad/nonmatchings/acropolis_helicopter_landing_pad", func_acropolis_helicopter_landing_pad_8017E570);

INCLUDE_ASM("rooms/acropolis_helicopter_landing_pad/nonmatchings/acropolis_helicopter_landing_pad", func_acropolis_helicopter_landing_pad_8017E5B8);

INCLUDE_ASM("rooms/acropolis_helicopter_landing_pad/nonmatchings/acropolis_helicopter_landing_pad", func_acropolis_helicopter_landing_pad_8017E5E8);

INCLUDE_ASM("rooms/acropolis_helicopter_landing_pad/nonmatchings/acropolis_helicopter_landing_pad", func_acropolis_helicopter_landing_pad_8017E618);

INCLUDE_ASM("rooms/acropolis_helicopter_landing_pad/nonmatchings/acropolis_helicopter_landing_pad", func_acropolis_helicopter_landing_pad_8017E64C);

INCLUDE_ASM("rooms/acropolis_helicopter_landing_pad/nonmatchings/acropolis_helicopter_landing_pad", func_acropolis_helicopter_landing_pad_8017E67C);

INCLUDE_ASM("rooms/acropolis_helicopter_landing_pad/nonmatchings/acropolis_helicopter_landing_pad", func_acropolis_helicopter_landing_pad_8017E6C0);

INCLUDE_ASM("rooms/acropolis_helicopter_landing_pad/nonmatchings/acropolis_helicopter_landing_pad", func_acropolis_helicopter_landing_pad_8017E6F0);

INCLUDE_ASM("rooms/acropolis_helicopter_landing_pad/nonmatchings/acropolis_helicopter_landing_pad", func_acropolis_helicopter_landing_pad_8017E724);

INCLUDE_ASM("rooms/acropolis_helicopter_landing_pad/nonmatchings/acropolis_helicopter_landing_pad", func_acropolis_helicopter_landing_pad_8017E75C);

INCLUDE_ASM("rooms/acropolis_helicopter_landing_pad/nonmatchings/acropolis_helicopter_landing_pad", func_acropolis_helicopter_landing_pad_8017E76C);

INCLUDE_ASM("rooms/acropolis_helicopter_landing_pad/nonmatchings/acropolis_helicopter_landing_pad", func_acropolis_helicopter_landing_pad_8017E81C);

INCLUDE_ASM("rooms/acropolis_helicopter_landing_pad/nonmatchings/acropolis_helicopter_landing_pad", func_acropolis_helicopter_landing_pad_8017E974);

INCLUDE_ASM("rooms/acropolis_helicopter_landing_pad/nonmatchings/acropolis_helicopter_landing_pad", func_acropolis_helicopter_landing_pad_8017EA6C);

INCLUDE_ASM("rooms/acropolis_helicopter_landing_pad/nonmatchings/acropolis_helicopter_landing_pad", func_acropolis_helicopter_landing_pad_8017EB00);

INCLUDE_ASM("rooms/acropolis_helicopter_landing_pad/nonmatchings/acropolis_helicopter_landing_pad", func_acropolis_helicopter_landing_pad_8017EB58);

INCLUDE_ASM("rooms/acropolis_helicopter_landing_pad/nonmatchings/acropolis_helicopter_landing_pad", func_acropolis_helicopter_landing_pad_8017ED00);

INCLUDE_ASM("rooms/acropolis_helicopter_landing_pad/nonmatchings/acropolis_helicopter_landing_pad", func_acropolis_helicopter_landing_pad_8017ED50);

INCLUDE_ASM("rooms/acropolis_helicopter_landing_pad/nonmatchings/acropolis_helicopter_landing_pad", func_acropolis_helicopter_landing_pad_8017EDD4);

INCLUDE_ASM("rooms/acropolis_helicopter_landing_pad/nonmatchings/acropolis_helicopter_landing_pad", func_acropolis_helicopter_landing_pad_8017EE2C);

INCLUDE_ASM("rooms/acropolis_helicopter_landing_pad/nonmatchings/acropolis_helicopter_landing_pad", func_acropolis_helicopter_landing_pad_8017EE80);

INCLUDE_ASM("rooms/acropolis_helicopter_landing_pad/nonmatchings/acropolis_helicopter_landing_pad", func_acropolis_helicopter_landing_pad_8017EEDC);

INCLUDE_ASM("rooms/acropolis_helicopter_landing_pad/nonmatchings/acropolis_helicopter_landing_pad", func_acropolis_helicopter_landing_pad_8017EF60);

INCLUDE_ASM("rooms/acropolis_helicopter_landing_pad/nonmatchings/acropolis_helicopter_landing_pad", func_acropolis_helicopter_landing_pad_8017EF8C);

INCLUDE_ASM("rooms/acropolis_helicopter_landing_pad/nonmatchings/acropolis_helicopter_landing_pad", func_acropolis_helicopter_landing_pad_8017F010);

INCLUDE_ASM("rooms/acropolis_helicopter_landing_pad/nonmatchings/acropolis_helicopter_landing_pad", func_acropolis_helicopter_landing_pad_8017FA30);

INCLUDE_ASM("rooms/acropolis_helicopter_landing_pad/nonmatchings/acropolis_helicopter_landing_pad", func_acropolis_helicopter_landing_pad_801802E0);

INCLUDE_ASM("rooms/acropolis_helicopter_landing_pad/nonmatchings/acropolis_helicopter_landing_pad", func_acropolis_helicopter_landing_pad_80180664);

INCLUDE_ASM("rooms/acropolis_helicopter_landing_pad/nonmatchings/acropolis_helicopter_landing_pad", func_acropolis_helicopter_landing_pad_80180A64);

INCLUDE_ASM("rooms/acropolis_helicopter_landing_pad/nonmatchings/acropolis_helicopter_landing_pad", func_acropolis_helicopter_landing_pad_80180E40);

INCLUDE_ASM("rooms/acropolis_helicopter_landing_pad/nonmatchings/acropolis_helicopter_landing_pad", func_acropolis_helicopter_landing_pad_80181064);

INCLUDE_ASM("rooms/acropolis_helicopter_landing_pad/nonmatchings/acropolis_helicopter_landing_pad", func_acropolis_helicopter_landing_pad_801818F0);

INCLUDE_ASM("rooms/acropolis_helicopter_landing_pad/nonmatchings/acropolis_helicopter_landing_pad", func_acropolis_helicopter_landing_pad_801819C0);

INCLUDE_ASM("rooms/acropolis_helicopter_landing_pad/nonmatchings/acropolis_helicopter_landing_pad", func_acropolis_helicopter_landing_pad_80181B64);

INCLUDE_ASM("rooms/acropolis_helicopter_landing_pad/nonmatchings/acropolis_helicopter_landing_pad", func_acropolis_helicopter_landing_pad_801822B0);
