#include "common.h"

INCLUDE_ASM("rooms/nonmatchings/dryfield_night_souvenir_shop/dryfield_night_souvenir_shop", func_dryfield_night_souvenir_shop_8017D610);

void func_dryfield_night_souvenir_shop_8017D654(void) {
}

INCLUDE_RODATA("rooms/nonmatchings/dryfield_night_souvenir_shop/dryfield_night_souvenir_shop", D_dryfield_night_souvenir_shop_8017D5C0);

INCLUDE_ASM("rooms/nonmatchings/dryfield_night_souvenir_shop/dryfield_night_souvenir_shop", func_dryfield_night_souvenir_shop_8017D65C);

INCLUDE_ASM("rooms/nonmatchings/dryfield_night_souvenir_shop/dryfield_night_souvenir_shop", func_dryfield_night_souvenir_shop_8017D6B4);

INCLUDE_ASM("rooms/nonmatchings/dryfield_night_souvenir_shop/dryfield_night_souvenir_shop", func_dryfield_night_souvenir_shop_8017DFF4);
