#include "common.h"

INCLUDE_ASM("rooms/nonmatchings/shelter_b2_breeding_room/shelter_b2_breeding_room", func_shelter_b2_breeding_room_8017D5F8);

INCLUDE_ASM("rooms/nonmatchings/shelter_b2_breeding_room/shelter_b2_breeding_room", func_shelter_b2_breeding_room_8017D658);

INCLUDE_RODATA("rooms/nonmatchings/shelter_b2_breeding_room/shelter_b2_breeding_room", D_shelter_b2_breeding_room_8017D5C0);

INCLUDE_RODATA("rooms/nonmatchings/shelter_b2_breeding_room/shelter_b2_breeding_room", D_shelter_b2_breeding_room_8017D5C4);

INCLUDE_RODATA("rooms/nonmatchings/shelter_b2_breeding_room/shelter_b2_breeding_room", jtbl_shelter_b2_breeding_room_8017D5D0);

INCLUDE_RODATA("rooms/nonmatchings/shelter_b2_breeding_room/shelter_b2_breeding_room", jtbl_shelter_b2_breeding_room_8017D5E4);
