#include "common.h"

INCLUDE_ASM("rooms/nonmatchings/dryfield_night_gas_station/dryfield_night_gas_station_6", func_dryfield_night_gas_station_8017FB70);

INCLUDE_ASM("rooms/nonmatchings/dryfield_night_gas_station/dryfield_night_gas_station_6", func_dryfield_night_gas_station_8017FBD4);

INCLUDE_ASM("rooms/nonmatchings/dryfield_night_gas_station/dryfield_night_gas_station_6", func_dryfield_night_gas_station_8017FD80);

INCLUDE_ASM("rooms/nonmatchings/dryfield_night_gas_station/dryfield_night_gas_station_6", func_dryfield_night_gas_station_801802EC);

INCLUDE_ASM("rooms/nonmatchings/dryfield_night_gas_station/dryfield_night_gas_station_6", func_dryfield_night_gas_station_80180604);
