#include "common.h"

INCLUDE_ASM("rooms/nonmatchings/dryfield_night_gas_station/dryfield_night_gas_station_4", func_dryfield_night_gas_station_8017F41C);

INCLUDE_ASM("rooms/nonmatchings/dryfield_night_gas_station/dryfield_night_gas_station_4", func_dryfield_night_gas_station_8017F544);

INCLUDE_ASM("rooms/nonmatchings/dryfield_night_gas_station/dryfield_night_gas_station_4", func_dryfield_night_gas_station_8017F6B8);

INCLUDE_ASM("rooms/nonmatchings/dryfield_night_gas_station/dryfield_night_gas_station_4", func_dryfield_night_gas_station_8017F7E0);

INCLUDE_ASM("rooms/nonmatchings/dryfield_night_gas_station/dryfield_night_gas_station_4", func_dryfield_night_gas_station_8017F89C);

INCLUDE_ASM("rooms/nonmatchings/dryfield_night_gas_station/dryfield_night_gas_station_4", func_dryfield_night_gas_station_8017F990);

INCLUDE_ASM("rooms/nonmatchings/dryfield_night_gas_station/dryfield_night_gas_station_4", func_dryfield_night_gas_station_8017F9E8);

INCLUDE_ASM("rooms/nonmatchings/dryfield_night_gas_station/dryfield_night_gas_station_4", func_dryfield_night_gas_station_8017FA6C);

INCLUDE_ASM("rooms/nonmatchings/dryfield_night_gas_station/dryfield_night_gas_station_4", func_dryfield_night_gas_station_8017FAEC);
