#!/usr/bin/env python3
"""Generate splat configs for the overlay families listed in overlays.toml.

main / gameplay / title stay hand-written: each has quirks a template cannot
express. Every other overlay is a flat `.pe2pkg` with the same shape, and there
are 446 of them, so they are generated instead - from one template plus a
manifest that holds only the decisions a person actually made (the overlay's
name, and what it is).

Everything checkable is derived from the package rather than written down:

``sha1`` / ``size``
    Read off the file, so a config cannot drift from the data it describes.
An overlay **is** an extracted package. The manifest key is the package's name
and the config is built from ``assets/USA/pe2pkg/<key>.pe2pkg``; file ids do not
appear. Several stage-0 ids load one package - the extractor dedups by SHA-1, so
`10500` and `10600` are a single file - but that is the extractor's business,
and naming the package there (``tools/peassets/asset_data.py``) is what makes it
a single thing here. One package, one entry, one split, one set of symbols.

``.text`` span
    Found the same way ``doc/OVERLAYS.md`` §4.3 does - first stack-frame
    prologue through the last ``jr $ra`` plus its delay slot. The detector
    reproduces the known title and gameplay spans exactly. A wrong span shows
    up as a failed build, not as silent corruption, and an overlay can pin it
    with `text = [start, end]` in the manifest if the detector ever misses.
"""

from __future__ import annotations

import argparse
import hashlib
import struct
import sys
import tomllib
from pathlib import Path

MANIFEST = Path("configs/USA/overlays.toml")
PACKAGE_DIR = Path("assets/USA/pe2pkg")
TEMPLATE = Path("configs/USA/overlay.template.yaml")
OUT_DIR = Path("configs/USA/generated")

ADDIU_SP = 0x27BD0000  # addiu $sp, $sp, -N  (negative immediate)
JR_RA = 0x03E00008


def text_span(data: bytes) -> tuple[int, int] | None:
    """Byte range of the code region, or None for a data-only package."""
    n = len(data) // 4
    words = struct.unpack_from(f"<{n}I", data, 0)
    starts = [i for i, w in enumerate(words) if (w & 0xFFFF0000) == ADDIU_SP and w & 0x8000]
    if not starts:
        return None
    ends = [i for i, w in enumerate(words) if w == JR_RA]
    if not ends:
        return None
    return min(starts) * 4, (max(ends) + 2) * 4


def trailing_segment(name: str, data: bytes) -> list[str]:
    """Cover a package whose size is not word-aligned.

    Package sizes are byte counts, not word counts, so a file can end part-way
    through a word. Without this the linker stops at the last whole word and the
    build comes out a couple of bytes short with every other byte identical -
    which is what `title.yaml` spells out by hand for its own 0x14AA size.

    Which segment depends on what those bytes are. `pad` emits zeros, so it is
    only correct when the tail *is* zeros. A tail with content needs `databin`,
    which writes the bytes out and .incbin's them back rather than inventing
    them.

    A unit whose C defines the image through its last byte is marked
    `tail = true` in the manifest, and then no segment is added: the partial
    word is the end of its last object, which the compiler emits itself.
    """
    tail = data[len(data) & ~3 :]
    if not tail:
        return []
    start = f"0x{len(data) & ~3:X}"
    if not any(tail):
        return [f"      - [{start}, pad]"]
    return [f"      - [{start}, databin, {name}_tail]"]


PACKAGE_ID_SRC = """\
/* GENERATED by tools/gen_overlay_configs.py from configs/USA/overlays.toml.
 *
 * Every package opens with its own id, a u16 in a u32 slot. The value reaches
 * the compiler as PKG_ID, from the id the package declares in the manifest, so
 * it is compiled in from the declaration rather than split out of the package:
 * the checksum then tests the declared value, and a manifest naming the wrong
 * id fails the build instead of reproducing whatever the package already said.
 *
 * Passing it as a flag is what lets this unit be identical for every package,
 * including the several load slots one image is issued at: they share every
 * other unit and differ only here.
 *
 * Nothing refers to the word. It is program structure written by the
 * packaging tool, so the unit exists to place the bytes, not to be referenced -
 * which is why it is private.
 *
 * It is `const` because the id belongs to the image's
 * read-only region: without that the compiler places it in `.data`, the rodata
 * run comes out empty, and everything after it shifts.
 */
#include "common.h"

static const s32 packageId = PKG_ID;
"""


def package_id_unit(family: str, package: str) -> str:
    """The unit holding a package's id word.

    One unit name for every overlay, under the package's own directory, so an
    entry covering several load slots names the same unit for each of them and
    still gets that slot's own id: the build keys an object on its source path,
    so a per-package path is what makes a per-package value possible at all.
    """
    return f"{package}/packageid"


def write_package_id(family: str, package: str) -> None:
    src = Path(f"src/{family}/{package}/packageid.c")
    src.parent.mkdir(parents=True, exist_ok=True)
    text = PACKAGE_ID_SRC
    if not src.is_file() or src.read_text(encoding="utf-8") != text:
        src.write_text(text, encoding="utf-8")


def check_model_records(name: str, objects: list[dict], data: bytes, load: int) -> None:
    """Every `model` object is exactly the model its `modelSource` record describes.

    The manifest declares both; this decodes the record at the declared offset
    and requires the model object to be its arrays and stream, from the lowest
    array to the record, so neither boundary can be misplaced.
    """
    sys.path.insert(0, str(Path(__file__).resolve().parent / "peassets"))
    import pkg_model

    kinds = [(obj.get("kind"), int(str(obj["at"]), 16) if "at" in obj else None) for obj in objects]
    # Where each object's runs begin: a run's `at`, and every section a unit owns.
    starts = sorted(int(str(obj[k]), 16) for obj in objects for k in ("at", "rodata", "text", "data") if k in obj)
    for i, (kind, at) in enumerate(kinds):
        if kind == "model":
            nxt = kinds[i + 1] if i + 1 < len(kinds) else (None, None)
            if nxt[0] != "modelSource":
                raise SystemExit(f"{name}: model at 0x{at:X} is not followed by its modelSource")
        elif kind == "modelSource":
            if i == 0 or kinds[i - 1][0] != "model":
                raise SystemExit(f"{name}: modelSource at 0x{at:X} does not follow a model")
            try:
                src = pkg_model.read_source(data, load, at)
            except ValueError as e:
                raise SystemExit(f"{name}: modelSource {e}")
            model_at = kinds[i - 1][1]
            if src["head"] != model_at or src["end"] != at:
                raise SystemExit(
                    f"{name}: the record at 0x{at:X} describes a model at "
                    f"0x{src['head']:X}..0x{src['end']:X}, not the declared 0x{model_at:X}..0x{at:X}")
            end = next((a for a in starts if a > at), len(data))
            if end != at + pkg_model.TMD_SOURCE_SIZE:
                raise SystemExit(f"{name}: modelSource at 0x{at:X} runs to 0x{end:X}, not its record's end")


def declared_models(manifest: dict) -> list[dict]:
    """Every model the manifest declares, with its package, load address and record.

    One row per package, so an object list shared by several slots yields a row
    for each package it describes.
    """
    rows = []
    for family, spec in manifest.items():
        if not isinstance(spec, dict) or "overlays" not in spec:
            continue
        slot_addr = {int(k): int(v) for k, v in (spec.get("slots") or {}).items()}
        entry_names = {id(e): n for n, e in spec["overlays"].items()}
        for name, slot, entry in slot_packages(spec):
            objects = slot.get("objects") or entry["objects"]
            load = slot_addr.get(slot.get("slot"), int(spec["load_addr"]))
            for i, obj in enumerate(objects):
                if obj.get("kind") == "modelSource":
                    rows.append({
                        "family": family,
                        "entry": entry_names[id(entry)],
                        "package": name,
                        "load": load,
                        "model": int(str(objects[i - 1]["at"]), 16),
                        "source": int(str(obj["at"]), 16),
                    })
    return rows


def object_subsegments(
    name: str, family: str, objects: list[dict], data: bytes, load: int, pkg_id: int,
    entry_name: str | None = None, defines: dict | None = None,
) -> str:
    """The package layout as splat subsegment lines, from the manifest's object list.

    An object is one translation unit with runs in whichever sections it owns,
    or a run of assembly nobody has claimed. splat lists an object in the linker
    script at its first subsegment and concatenates a section's contributions in
    that order, so the single ordered list the manifest carries is exactly what
    determines link order - there is nothing left to stitch together here.

    Assembly runs are named for the offset they start at. Naming them by their
    position in the walk meant inserting one renamed every later run, which is
    the defect the object list exists to remove.
    """
    check_model_records(name, objects, data, load)
    lines: list[str] = []
    for obj in objects:
        kind = obj.get("kind")
        if kind == "packageId":
            if pkg_id is None:
                raise SystemExit(
                    f"{name}: has a packageId object but declares no `id`")
            write_package_id(family, name)
            lines.append((0x0, f"      - [0x0, .rodata, {package_id_unit(family, name)}]"))
            continue
        if kind in ("data", "model", "modelSource", "rodata"):
            at = int(str(obj["at"]), 16)
            typ = {"model": "databin", "modelSource": "data", "data": "data", "rodata": "rodata"}[kind]
            lines.append((at, f"      - [0x{at:X}, {typ}, {name}_{kind}_{at:05X}]"))
            continue
        unit = str(obj["unit"])
        lib = obj.get("lib", False)
        if lib is not True and "lib" in obj:
            raise SystemExit(f"{name}: {unit}: `lib` is a flag, write `lib = true`")
        if lib and "text" not in obj:
            # splat gives a unit's .rodata/.data the object of its C sibling.
            # Without one it would imply a source under the family instead.
            raise SystemExit(f"{name}: library unit {unit} has no text run")
        path = f"lib/{unit}" if lib else (
            unit if "/" in unit else f"{name}/{unit}")
        # A variant unit is one source compiled once per package with that
        # package's defines: the object is named per package, the source is the
        # entry's. It only exists where the packages declare what differs.
        variant = obj.get("variant", False)
        if variant:
            if "/" in unit or lib or "text" not in obj:
                raise SystemExit(f"{name}: variant unit {unit} must be a bare, non-library unit with a text run")
            if not defines:
                raise SystemExit(f"{name}: variant unit {unit}, but the slot declares no `defines`")
        # A library unit's source is src/lib/, shared by every family.
        text = "libsrc" if lib else "c"
        for key, sect in (("rodata", ".rodata"), ("text", text), ("data", ".data")):
            if key in obj:
                at = int(str(obj[key]), 16)
                if variant and key == "text":
                    lines.append((at, f"      - {{start: 0x{at:X}, type: variantsrc, name: {path}, "
                                      f"source: {entry_name}/{unit}}}"))
                else:
                    lines.append((at, f"      - [0x{at:X}, {sect}, {path}]"))
    out = [line for _, line in sorted(lines, key=lambda t: t[0])]
    tails = [i for i, obj in enumerate(objects) if obj.get("tail", False)]
    if tails and (tails != [len(objects) - 1] or "data" not in objects[-1]):
        raise SystemExit(f"{name}: only the last object, a unit with data, can be `tail = true`")
    if not tails:
        out.extend(trailing_segment(name, data))
    return "\n".join(out)


def overlay_label(name: str, entry: dict) -> str:
    """Human label for the config's title line.

    Families describe their overlays with different keys - `weapon` names the
    gun, `note` says what an unnamed one is - so the label falls back through
    them to the overlay name rather than requiring any particular field. A
    family that adds a new descriptive key needs it listed here, nothing more.
    """
    for key in ("weapon", "note"):
        value = entry.get(key)
        if value:
            return str(value)
    return name


def slot_packages(spec: dict) -> list[tuple[str, dict, dict]]:
    """(package, slot record, entry) for every package a family declares.

    An entry covers one package, or - where a family loads the same image into
    several slots - all of them at once. Expanding here keeps everything below
    working per package, which is what a config describes.
    """
    out = []
    for name, entry in sorted(spec["overlays"].items()):
        for slot in entry.get("slots") or [{"package": name, "slot": entry.get("slot")}]:
            out.append((str(slot["package"]), slot, entry))
    return out


def generate(family: str, spec: dict, template: str, out_dir: Path) -> list[Path]:
    written: list[Path] = []
    seen: dict[bytes, str] = {}
    slot_addr = {int(k): int(v) for k, v in (spec.get("slots") or {}).items()}
    entry_names = {id(e): n for n, e in spec["overlays"].items()}
    for name, slot, entry in slot_packages(spec):
        entry_name = entry_names[id(entry)]
        target = PACKAGE_DIR / f"{name}.pe2pkg"
        if not target.is_file():
            raise SystemExit(
                f"{family}/{name}: {target} not found.\n"
                f"  Package names come from tools/peassets/asset_data.py. The asset\n"
                f"  tree is incomplete - most often because an extraction is running\n"
                f"  right now, since `ninja_config.py -iso_min` deletes assets/ and\n"
                f"  rom/ before rebuilding them, and every sweep worktree symlinks\n"
                f"  those from the main checkout. Wait for it to finish and retry.\n"
                f"  Do not start an extraction yourself while other sweeps are\n"
                f"  running: that is how one wipe took out 50 of them at once."
            )
        data = target.read_bytes()

        # Two entries on one package would split the same file twice and give
        # its functions two symbol prefixes. Distinct names sharing content mean
        # the extractor's naming disagrees with this manifest.
        digest = hashlib.sha1(data).digest()
        clash = seen.get(digest)
        if clash is not None:
            raise SystemExit(
                f"{family}/{name} is the same package as {family}/{clash}.\n"
                f"  Splitting it again would disassemble the same file twice.\n"
                f"  Keep one entry, and give the package one name in asset_data.py."
            )
        seen[digest] = name

        declared = slot.get("text", entry.get("text"))
        span = tuple(int(str(v), 16) for v in declared) if declared else text_span(data)
        # The title becomes the config's quoted `name:`, so a note containing a
        # quote would still break the yaml.
        label = slot.get("label", entry.get("label")) or name
        title = f"{spec['description']} - {label}".replace('"', "'")

        # A family may span several RAM slots, and a slot is one address, so an
        # overlay's load address - and the vram end that tracks it - follow from
        # the slot it declares rather than being restated per overlay.
        load = slot_addr.get(slot.get("slot"), int(spec["load_addr"]))
        vram_end = load if slot_addr else int(spec["global_vram_end"])

        text = template
        for key, val in {
            "TITLE": title,
            "NAME": name,
            "FAMILY": family,
            "TARGET": target.as_posix(),
            "SHA1": hashlib.sha1(data).hexdigest(),
            "SIZE": str(len(data)),
            "SIZE_HEX": f"0x{len(data):X}",
            "VRAM": f"0x{load:08X}",
            "GLOBAL_VRAM_START": f"0x{spec['global_vram_start']:08X}",
            "GLOBAL_VRAM_END": f"0x{vram_end:08X}",
            "IMPORTS": spec["imports"],
            "RELOCS": (
                f'[{entry.get("relocs", spec.get("relocs", ""))}]'
                if entry.get("relocs", spec.get("relocs"))
                else "[]"
            ),
            "SUBSEGMENTS": object_subsegments(
                # Packages built from one source can still carry different
                # content - their own models and data - so a slot may lay its
                # package out with its own object list.
                name, family, slot.get("objects") or entry["objects"], data, load,
                slot.get("id", entry.get("id")),
                entry_name, slot.get("defines"),
            ),
        }.items():
            text = text.replace(f"@@{key}@@", val)
        if "@@" in text:
            raise SystemExit(f"{family}/{name}: unsubstituted placeholder in template")

        dest = out_dir / f"{name}.yaml"
        # Unchanged configs keep their mtime: ninja_config.py treats a config
        # modified during a split as a reason to split it again.
        if not dest.is_file() or dest.read_text(encoding="utf-8") != text:
            dest.write_text(text, encoding="utf-8")
        written.append(dest)
    return written


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--family", help="only generate this family")
    ap.add_argument("--list", action="store_true", help="print names and exit")
    args = ap.parse_args()

    manifest = tomllib.loads(MANIFEST.read_text(encoding="utf-8"))
    template = TEMPLATE.read_text(encoding="utf-8")
    OUT_DIR.mkdir(parents=True, exist_ok=True)

    total = 0
    produced: set[Path] = set()
    for family, spec in manifest.items():
        if args.family and family != args.family:
            continue
        if args.list:
            for name, e in sorted(spec["overlays"].items()):
                print(f"{family}\t{name}\t{overlay_label(name, e)}")
            continue
        written = generate(family, spec, template, OUT_DIR)
        produced.update(written)
        total += len(written)
        print(f"{family}: wrote {len(written)} config(s) to {OUT_DIR}")

    # Drop configs the manifest no longer produces. Without this, renaming an
    # overlay or marking one as a duplicate leaves its old config behind and the
    # build keeps splitting it.
    if not args.list and not args.family:
        stale = sorted(p for p in OUT_DIR.glob("*.yaml") if p not in produced)
        for path in stale:
            path.unlink()
        if stale:
            print(f"removed {len(stale)} stale config(s): "
                  + ", ".join(p.stem for p in stale))
    return 0 if args.list or total else 1


if __name__ == "__main__":
    sys.exit(main())
