#!/usr/bin/env python3
"""Write include/main/areas.h, the stage and area IDs, from the extractor's tree.

An area is a room folder within its stage, and its ID is the folder's disc id
divided by 100 (`asset_data.TREE`); `GameLocationKey.area` and
`RoomEventMsg.areaId` hold it. The folder names are the extractor's, so the
header is derived rather than written: rename a folder in
`tools/peassets/asset_data.py`, rerun this, and the constant follows.

    python3 tools/gen_area_ids.py           # rewrite the header
    python3 tools/gen_area_ids.py --check   # fail when it is stale (build-and-verify)
"""
import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "tools" / "peassets"))
from asset_data import TREE  # noqa: E402

HEADER = ROOT / "include" / "main" / "areas.h"
# The stages are the disc's stage folders; their names say which rooms each holds.
STAGES = {
    1: ("GAME_STAGE_ACROPOLIS", "Akropolis Tower and the MIST"),
    2: ("GAME_STAGE_DRYFIELD", "Dryfield by day"),
    3: ("GAME_STAGE_DRYFIELD_NIGHT", "Dryfield by night"),
    4: ("GAME_STAGE_MINE_SHELTER", "The mine, and the Shelter from 1F to B4"),
    5: ("GAME_STAGE_SHELTER_NEO_ARK", "The Shelter's 1F and B6, and the Neo Ark"),
}


def render() -> str:
    out = [
        "#ifndef MAIN_AREAS_H",
        "#define MAIN_AREAS_H",
        "",
        "// Generated by tools/gen_area_ids.py from the extractor's tree; do not edit.",
        "",
        "/// Stage IDs, stored in `GameLocationKey.stage`: the disc's stage folders, each",
        "/// loaded as a unit with its own area tables. An area is a folder within one.",
        "enum {",
        "    GAME_STAGE_NONE            = 0, // No active stage",
        *(f"    {label.ljust(26)} = {stage}, // {what}" for stage, (label, what) in STAGES.items()),
        "};",
        "",
        "/// Area IDs, stored in `GameLocationKey.area` and `RoomEventMsg.areaId`.",
        "///",
        "/// An area is a room folder within its stage, numbered by the folder's disc",
        "/// id divided by 100. An ID is meaningful only with its stage: each stage",
        "/// numbers its own folders, so the same value names a different room in",
        "/// another stage. The constant names the room folder it selects.",
        "enum {",
    ]
    for stage, (label, _) in STAGES.items():
        folders = sorted(((v["id"] // 100, name) for name, v in TREE[stage]["folders"].items()))
        out.append(f"    // {label}")
        width = max(len(name) for _, name in folders) + len("GAME_AREA_")
        for area, name in folders:
            out.append(f"    {('GAME_AREA_' + name.upper()).ljust(width)} = {area},")
    out += ["};", "", "#endif // MAIN_AREAS_H", ""]
    return "\n".join(out)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--check", action="store_true", help="fail if the header is out of date")
    args = ap.parse_args()
    text = render()
    current = HEADER.read_text() if HEADER.exists() else ""
    if args.check:
        if current != text:
            print(f"{HEADER.relative_to(ROOT)} is stale; run python3 tools/gen_area_ids.py")
            return 1
        return 0
    if current != text:
        HEADER.write_text(text)
        print(f"wrote {HEADER.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
