#!/usr/bin/env python3
"""Index functions that appear in more than one overlay.

Overlays in a family are separate link outputs that share a lot of code: 56% of
the room functions are copies of another room's, and 60% of the instructions.
Matching each copy separately would be the same work done up to 265 times, so
the first thing needed is to know what is shared.

Equality is decided on splat's **disassembly text**, not on the instruction
words. Comparing words is tempting and wrong: clearing the link-dependent
fields to let two copies at different addresses compare equal also clears every
other I-type immediate, so `lw $v0, 0x4($t0)` and `lw $v0, 0xC($t0)` - a
different struct field, a different function - come out identical. That
overstated room duplication as 56% of functions when the real figure is 17%.

The text is already symbolic where it needs to be, so the canonical form only
has to drop what names a copy's own position:

* the ``/* offset vram encoding */`` column,
* local branch labels, which splat names `.L<overlay>_<vram>`,
* the *identity* of an overlay-local symbol, keeping that it is local - two
  copies of one body reference their own room's data, not each other's.

Two hashes come out of that: ``text`` treats a local reference as a wildcard,
and ``raw`` is the instruction words verbatim - equal only when the copies are
byte-for-byte the same, which happens because every room loads at 0x8017D5C0.

The index is derived from asm/, which is regenerated by every split, so it is
cached under build/ and rebuilt when missing or stale.
"""

from __future__ import annotations

import argparse
import collections
import hashlib
import json
import re
import struct
import sys
from pathlib import Path

ASM_ROOT = Path("asm/USA")
CACHE = Path("build/USA/dup_index.json")
WORD = re.compile(r"^\s*/\* [0-9A-F]+ ([0-9A-F]{8}) ([0-9A-F]{8}) \*/", re.M)
REF = re.compile(r"%(?:hi|lo)\(([A-Za-z_]\w*)\)|\b(?:jal|j)\s+([A-Za-z_]\w*)")


ADDR = re.compile(r"^\s*/\* [0-9A-F]+ [0-9A-F]{8} [0-9A-F]{8} \*/")
LOCAL = re.compile(r"\b(func|D|jtbl)_([A-Za-z0-9_]+?)_([0-9A-F]{8})\b")
# `symbol_name_format` applies to local labels too, so they read
# `.L<overlay>_<vram>` - match any local label, not just a bare address.
BRANCH = re.compile(r"\.L\w+")
SKIP = ("glabel", "endlabel", "nonmatching", ".include", ".set", ".section", "/*")


def scan_function(path: Path, unit: str) -> dict | None:
    text = path.read_text(encoding="utf-8", errors="replace")
    found = WORD.findall(text)
    if not found:
        return None
    # splat writes the encoding big-endian in the comment; the target is little.
    words = [struct.unpack("<I", struct.pack(">I", int(w, 16)))[0] for _v, w in found]

    canon: list[str] = []
    labels: dict[str, str] = {}
    for line in text.splitlines():
        if line.startswith(SKIP):
            continue
        line = ADDR.sub("", line).rstrip()
        if not line:
            continue
        for hit in BRANCH.findall(line):
            labels.setdefault(hit, f".L{len(labels)}")
        line = BRANCH.sub(lambda m: labels[m.group(0)], line)
        line = LOCAL.sub(
            lambda m: f"{m.group(1)}_LOCAL" if m.group(2) == unit else m.group(0), line
        )
        canon.append(line)

    return {
        "name": path.stem,
        "unit": unit,
        "words": len(words),
        "vram": found[0][0],
        "raw": hashlib.sha1(struct.pack(f"<{len(words)}I", *words)).hexdigest(),
        "text": hashlib.sha1("\n".join(canon).encode()).hexdigest(),
        "refs": sorted({a or b for a, b in REF.findall(text)}),
    }


def build(families: list[str] | None) -> dict:
    roots = [ASM_ROOT / f for f in families] if families else [ASM_ROOT]
    out: list[dict] = []
    for root in roots:
        if not root.is_dir():
            continue
        for path in sorted(root.rglob("nonmatchings/**/*.s")):
            if not path.name.startswith("func_"):
                continue
            # asm/<ver>/<family>/nonmatchings/<overlay>/<unit…>/<fn>.s - the
            # overlay is the component after the marker, not before it: asm_path
            # is the family root so several overlays share one asm tree.
            parts = path.parts
            marker = parts.index("nonmatchings")
            overlay = parts[marker + 1]
            rec = scan_function(path, overlay)
            if rec:
                rec["overlay"] = f"{'/'.join(parts[1:marker])}/{overlay}"
                out.append(rec)
    return {"functions": out}


def load(rebuild: bool, families: list[str] | None) -> dict:
    if not rebuild and CACHE.is_file():
        return json.loads(CACHE.read_text())
    data = build(families)
    CACHE.parent.mkdir(parents=True, exist_ok=True)
    CACHE.write_text(json.dumps(data))
    return data


def classes(data: dict, key: str) -> dict[str, list[dict]]:
    out: dict[str, list[dict]] = collections.defaultdict(list)
    for fn in data["functions"]:
        out[fn[key]].append(fn)
    return out


def cmd_stats(data: dict) -> int:
    fns = data["functions"]
    by_family = collections.Counter(f["overlay"].split("/")[0] for f in fns)
    print(f"{len(fns)} functions across {len(by_family)} family/families")
    for key, label in (("text", "same body"), ("raw", "same bytes")):
        cl = classes(data, key)
        red = len(fns) - len(cl)
        wt = sum(f["words"] for f in fns)
        wu = sum(v[0]["words"] for v in cl.values())
        print(f"  {label:12}: {len(cl):5} distinct, {red:5} redundant copies "
              f"({100*red//len(fns)}% of functions, {100*(wt-wu)//wt}% of instructions)")
    cl = classes(data, "text")
    hist = collections.Counter(len(v) for v in cl.values())
    multi = sum(c for n, c in hist.items() if n > 1)
    print(f"\n  bodies appearing more than once: {multi}")
    for n in (2, 3, 5, 10, 20, 50):
        c = sum(v for k, v in hist.items() if k >= n)
        print(f"    in >= {n:3} places: {c}")
    print("\n  biggest wins (copies x instructions saved):")
    ranked = sorted(cl.values(), key=lambda v: -(len(v) - 1) * v[0]["words"])
    for v in ranked[:8]:
        print(f"    {len(v):3} copies x {v[0]['words']:4} = {(len(v)-1)*v[0]['words']:6} saved   {v[0]['name']}")
    return 0


def cmd_find(data: dict, name: str) -> int:
    cl_text, cl_raw = classes(data, "text"), classes(data, "raw")
    hit = next((f for f in data["functions"] if f["name"] == name), None)
    if hit is None:
        print(f"{name}: not found", file=sys.stderr)
        return 1
    same_src = cl_text[hit["text"]]
    same_bytes = cl_raw[hit["raw"]]
    print(f"{name}  ({hit['words']} instructions, {hit['overlay']})")
    print(f"  same body: {len(same_src)} copies   identical bytes: {len(same_bytes)}")
    for f in sorted(same_src, key=lambda f: f["overlay"]):
        mark = "=" if f["raw"] == hit["raw"] else "~"
        print(f"    {mark} {f['overlay']:36} {f['name']}")
    print("\n  = identical bytes, ~ same body at a different link offset")
    return 0


def cmd_shared(data: dict, minimum: int, refs: bool) -> int:
    cl = classes(data, "text")
    ranked = sorted((v for v in cl.values() if len(v) >= minimum),
                    key=lambda v: -(len(v) - 1) * v[0]["words"])
    print(f"{len(ranked)} bodies in >= {minimum} places")
    for v in ranked:
        line = f"  {len(v):3} copies  {v[0]['words']:4} insns  {v[0]['name']}"
        if refs:
            own = {r for f in v for r in f["refs"]
                   if r.startswith((f"func_{f['unit']}_", f"D_{f['unit']}_", f"jtbl_{f['unit']}_"))}
            line += f"   room-local refs: {len(own)}"
        print(line)
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("command", choices=("stats", "find", "shared"))
    ap.add_argument("name", nargs="?")
    ap.add_argument("--family", action="append", help="limit to a family (rooms, weapons, …)")
    ap.add_argument("--min", type=int, default=10, help="`shared`: minimum copies")
    ap.add_argument("--refs", action="store_true", help="`shared`: count overlay-local references")
    ap.add_argument("--rebuild", action="store_true", help="ignore the cached index")
    args = ap.parse_args()

    data = load(args.rebuild, args.family)
    if args.command == "stats":
        return cmd_stats(data)
    if args.command == "shared":
        return cmd_shared(data, args.min, args.refs)
    if not args.name:
        ap.error("find needs a function name")
    return cmd_find(data, args.name)


if __name__ == "__main__":
    sys.exit(main())
