#!/usr/bin/env python3
"""Index functions that appear in more than one overlay.

Overlays in a family are separate link outputs that share a lot of code: 36% of
indexed functions are copies of another overlay's body, and 33% of the
instructions.
Matching each copy separately would be the same work done up to 265 times, so
the first thing needed is to know what is shared.

Equality is decided on splat's **disassembly text**, not on the instruction
words. Comparing words is tempting and wrong: clearing the link-dependent
fields to let two copies at different addresses compare equal also clears every
other I-type immediate, so `lw $v0, 0x4($t0)` and `lw $v0, 0xC($t0)` - a
different struct field, a different function - come out identical. That
overstated duplication badly - it was the source of the old 56% claim. Run
`stats` for the current measured figure rather than quoting one from here.

The text is already symbolic where it needs to be, so the canonical form only
has to drop what names a copy's own position:

* the ``/* offset vram encoding */`` column,
* local branch labels, which splat names `.L<overlay>_<vram>`,
* the *identity* of an overlay-local symbol, keeping that it is local - two
  copies of one body reference their own room's data, not each other's.

Two hashes come out of that: ``text`` treats a local reference as a wildcard,
and ``raw`` is the instruction words verbatim - equal only when the copies are
byte-for-byte the same, which happens because every room loads at 0x8017D5C0.

The index is derived from asm/, which is regenerated by every split, so it is
cached under build/ and rebuilt when missing or stale.
"""

from __future__ import annotations

import argparse
import collections
import difflib
import hashlib
import json
import re
import struct
import sys
from pathlib import Path

ASM_ROOT = Path("asm/USA")
CACHE = Path("build/USA/dup_index.json")
MANIFEST = Path("configs/USA/overlays.toml")
# Families that are one link output, not a set of them. Their asm tree is still
# cut into unit directories, but two identical bodies in two of those units are
# two separate functions - the segment links once, so neither can be served by
# the other. Treating the whole family as one overlay is what keeps `solved`
# and `siblings` from offering to share them.
SINGLE_LINK = frozenset({"main", "gameplay", "title"})
WORD = re.compile(r"^\s*/\* [0-9A-F]+ ([0-9A-F]{8}) ([0-9A-F]{8}) \*/", re.M)
REF = re.compile(r"%(?:hi|lo)\(([A-Za-z_]\w*)\)|\b(?:jal|j)\s+([A-Za-z_]\w*)")


ADDR = re.compile(r"^\s*/\* [0-9A-F]+ [0-9A-F]{8} [0-9A-F]{8} \*/")
LOCAL = re.compile(r"\b(func|D|jtbl)_([A-Za-z0-9_]+?)_([0-9A-F]{8})\b")
# An actor whose slots share one entry names its symbols by offset into the
# image (`Actor01100_Fn0097C`, `_D074E8`, `_Jt…`), since one name has to serve
# every slot. They are the same kind of reference as `LOCAL`: two copies of a
# body point at their own actor's data, and only the owner differs.
OFFSET_LOCAL = re.compile(r"\b(Actor\d{5})_(Fn|D|Jt)([0-9A-F]+)\b")
# `symbol_name_format` applies to local labels too, so they read
# `.L<overlay>_<vram>` - match any local label, not just a bare address. A
# matched copy in an offset-named actor reads `Actor01100_L00BC8` instead.
BRANCH = re.compile(r"\.L\w+|\bActor\d{5}_L[0-9A-F]+\b")
# `.align` says where the block sits, not what it is: splat emits an
# `.align 3` ahead of a jump table that starts a cut rodata subsegment and
# nothing ahead of the same table mid-block, so keeping it would stop a
# matched copy from grouping with the unmatched copies it is meant to serve.
SKIP = ("glabel", "endlabel", "nonmatching", ".include", ".set", ".section",
        ".align", "/*")
# A jump target reads `jlabel .L…` while a jump table referencing it is in
# another file and `.L…:` while the table sits in this one, so the marker says
# where the table ended up rather than what the body is. Both forms fold to the
# bare label for the same reason `.align` is skipped.
LABELDEF = re.compile(r"^\s*(?:jlabel\s+)?(\.L\w+|Actor\d{5}_L[0-9A-F]+):?$")
# Similarity features. These are deliberately *lossier* than `text`: they answer
# "is there a matched body shaped like this one", which is a candidate question,
# never an equality one. Comparing operand-stripped opcodes equates
# `lw $v0,0x4($t0)` with `lw $v0,0xC($t0)` - a different field of a different
# struct - which is exactly the error that produced the old 56% duplication
# claim. Used to rank a reference implementation for an agent to read, that is
# fine; used to decide two functions are the same, it is not.
MNEMONIC = re.compile(r"^\s*/\* [0-9A-F]+ [0-9A-F]{8} [0-9A-F]{8} \*/\s+(\S+)", re.M)
DISPL = re.compile(r"\b(?:lw|lh|lhu|lb|lbu|sw|sh|sb)\s+\S+,\s*(-?(?:0x)?[0-9a-fA-F]+)\(")
CALLS = re.compile(r"^\s*/\* [0-9A-F]+ [0-9A-F]{8} [0-9A-F]{8} \*/\s+jal\s+(\S+)", re.M)
CACHE_VERSION = 2


def is_local_ref(ref: str, unit: str) -> bool:
    """Whether `ref` names code or data defined in `unit`'s own overlay."""
    if ref.startswith((f"func_{unit}_", f"D_{unit}_", f"jtbl_{unit}_")):
        return True
    m = OFFSET_LOCAL.fullmatch(ref)
    return bool(m) and m.group(1) == "Actor" + unit.removeprefix("actor_")


def declaration(path: Path, text: str) -> re.Match | None:
    """Where this file's body starts, or None if the file is not code.

    Splat gives a unit three shapes and only the name says which is which:

    * ``glabel`` - a function, whatever it is called. Requiring a ``func_``
      prefix here used to drop 3,035 ``Actor…_L…`` and 626 ``Actor…_Fn…``
      bodies, which is most of what the actor overlays still have left.
    * ``jlabel`` - a basic block a jump table branches into. Real code, matched
      like any other unit, and duplicated across overlays for the same reasons.
    * ``dlabel`` - data. Except when a `.text` span comes up short and splat
      files code into `.rodata` as ``.word``; that only happens to functions,
      which carry the ``func_`` name, so data tables with names of their own
      (``Display_TaskStates``, ``Boot_BuildStamp``) stay out.
    """
    kinds = "glabel|jlabel|dlabel" if path.stem.startswith("func_") else "glabel|jlabel"
    return re.search(rf"^(?:{kinds}) {re.escape(path.stem)}\b", text, re.M)


def scan_function(path: Path, unit: str) -> dict | None:
    text = path.read_text(encoding="utf-8", errors="replace")
    found = WORD.findall(text)
    if not found:
        return None
    body = declaration(path, text)
    if body is None:
        return None
    # splat prepends the `.rodata` a function owns - its jump table - ahead of
    # the code, so the first word in the file is not the function's. `vram` and
    # `words` describe the body alone, because promotion turns them into a
    # `.text` span and a jump table is not part of it.
    # From `body.end()`, so the declaration line itself never reaches the hash:
    # it carries the unit's own name (`jlabel Actor03800_L01EA8`), which differs
    # in every copy. `glabel` used to be dropped by SKIP instead; doing it here
    # covers all three kinds and leaves the existing hashes unchanged.
    code = WORD.findall(text[body.end():])
    # splat writes the encoding big-endian in the comment; the target is little.
    words = [struct.unpack("<I", struct.pack(">I", int(w, 16)))[0] for _v, w in found]

    canon: list[str] = []
    labels: dict[str, str] = {}
    own = "Actor" + unit.removeprefix("actor_")
    # Canonicalise the body alone, for the same reason `vram` and `words` do:
    # migrating a jump table into the function that owns it prepends a whole
    # `dlabel` block here, and only in the copy whose rodata has been cut.
    for line in text[body.end():].splitlines():
        if line.startswith(SKIP):
            continue
        line = ADDR.sub("", line).rstrip()
        if not line:
            continue
        line = LABELDEF.sub(r"\1:", line)
        for hit in BRANCH.findall(line):
            labels.setdefault(hit, f".L{len(labels)}")
        line = BRANCH.sub(lambda m: labels[m.group(0)], line)
        line = LOCAL.sub(
            lambda m: f"{m.group(1)}_LOCAL" if m.group(2) == unit else m.group(0), line
        )
        line = OFFSET_LOCAL.sub(
            lambda m: f"{m.group(2)}_LOCAL" if m.group(1) == own else m.group(0), line
        )
        canon.append(line)

    return {
        "name": path.stem,
        "unit": unit,
        "words": len(code),
        "vram": code[0][0],
        "raw": hashlib.sha1(struct.pack(f"<{len(words)}I", *words)).hexdigest(),
        "text": hashlib.sha1("\n".join(canon).encode()).hexdigest(),
        "refs": sorted({a or b for a, b in REF.findall(text)}),
        # Body only, for the same reason the hashes are: a migrated jump table
        # would otherwise show up as extra "instructions" in one copy.
        "ops": MNEMONIC.findall(text[body.end():]),
        "disp": DISPL.findall(text[body.end():]),
        "calls": CALLS.findall(text[body.end():]),
    }


def encode_shapes(records: list[dict]) -> list[str]:
    """Rewrite each record's `ops` list as a string, one character per opcode.

    difflib on 100-token lists across ~1600 candidates is slow enough to notice
    in a bootstrap; on strings it is not. The vocabulary is stored with the
    cache so the encoding is stable and exact rather than a hash with
    collisions.
    """
    vocab: dict[str, int] = {}
    for r in records:
        for op in r["ops"]:
            vocab.setdefault(op, len(vocab))
    for r in records:
        r["shape"] = "".join(chr(0x4E00 + vocab[op]) for op in r["ops"])
        del r["ops"]
    return [op for op, _ in sorted(vocab.items(), key=lambda kv: kv[1])]


def build(families: list[str] | None) -> dict:
    roots = [ASM_ROOT / f for f in families] if families else [ASM_ROOT]
    out: list[dict] = []
    for root in roots:
        if not root.is_dir():
            continue
        for marker in ("nonmatchings", "matchings"):
          for path in sorted(root.rglob(f"{marker}/**/*.s")):
            # `scan_function` decides what is code; skip splat's data units by
            # name first so 1,300 tables are not read to find that out.
            if path.name.startswith(("D_", "jtbl_")):
                continue
            # asm/<ver>/<family>/nonmatchings/<overlay>/<unit…>/<fn>.s - the
            # overlay is the component after the marker, not before it: asm_path
            # is the family root so several overlays share one asm tree.
            parts = path.parts
            at = parts.index(marker)
            family = parts[at - 1]
            overlay = family if family in SINGLE_LINK else parts[at + 1]
            rec = scan_function(path, overlay)
            if rec:
                rec["overlay"] = f"{'/'.join(parts[1:at])}/{overlay}"
                # A body already decompiled somewhere is solved: its remaining
                # copies want promoting into the shared library, not matching.
                rec["state"] = "matched" if marker == "matchings" else "todo"
                out.append(rec)
    return {"functions": out, "vocab": encode_shapes(out), "version": CACHE_VERSION}


def family_keys(families: list[str] | None) -> set[str]:
    """`rooms`, `USA/rooms` and `asm/USA/rooms` all name the same family."""
    return {f.strip("/").split("/")[-1] for f in families} if families else set()


def filter_families(data: dict, families: list[str] | None) -> dict:
    keys = family_keys(families)
    if not keys:
        return data
    fns = [f for f in data["functions"] if f["overlay"].split("/")[1] in keys]
    return {**data, "functions": fns}


def load(rebuild: bool, families: list[str] | None) -> dict:
    """The index, restricted to `families`.

    The filter has to be applied to whatever comes back, not only to a fresh
    build: the cached index was returned verbatim, so --family was accepted and
    silently ignored on every run that did not also pass --rebuild, and
    `stats --family rooms` reported the whole tree.

    The cache also records which families produced it. Without that, one
    `--rebuild --family rooms` leaves a rooms-only cache that every later
    unfiltered run reads as though it were the whole tree - the same bug
    inverted, and quieter.
    """
    keys = family_keys(families)
    if not rebuild and CACHE.is_file():
        cached = json.loads(CACHE.read_text())
        covered = set(cached.get("families") or [])
        # A cache written before the similarity features exist has no `shape`,
        # and `similar` would silently rank nothing. Version it rather than
        # letting that fail quietly.
        if cached.get("version") == CACHE_VERSION and (
                not covered or (keys and keys <= covered)):
            return filter_families(cached, families)
    data = build(families)
    data["families"] = sorted(keys)
    CACHE.parent.mkdir(parents=True, exist_ok=True)
    CACHE.write_text(json.dumps(data))
    return filter_families(data, families)


def classes(data: dict, key: str) -> dict[str, list[dict]]:
    out: dict[str, list[dict]] = collections.defaultdict(list)
    for fn in data["functions"]:
        out[fn[key]].append(fn)
    return out


def family_of(f: dict) -> str:
    return f["overlay"].split("/")[1]


def library_families() -> frozenset[str]:
    """Families whose packages can link a unit from src/lib.

    Those are the families the manifest generates: an object there is a line in
    a package's object list, and a library unit is one more. main, gameplay and
    title have hand-written configs and link once, so a copy there can never be
    served by the library and is not a sibling of anything.
    """
    import tomllib

    manifest = tomllib.loads(MANIFEST.read_text(encoding="utf-8"))
    return frozenset(k for k, v in manifest.items() if isinstance(v, dict) and "overlays" in v)


def cmd_siblings(data: dict, name: str, min_words: int) -> int:
    """Copies of this body in *other overlays* that can link the library.

    That is the set promotion can serve, in any family the manifest generates:
    an overlay links once, so a second copy inside the same overlay is a
    separate function. Empty output means nothing to promote, which is the
    common case and is not an error.
    """
    hit = next((f for f in data["functions"] if f["name"] == name), None)
    if hit is None or hit["words"] < min_words:
        return 0
    families = library_families()
    if family_of(hit) not in families:
        return 0
    for f in sorted(classes(data, "text")[hit["text"]], key=lambda f: f["overlay"]):
        if f["overlay"] != hit["overlay"] and family_of(f) in families:
            print(f"{f['overlay']}\t{f['name']}")
    return 0


def _entry_of(manifest: dict, family: str, package: str) -> tuple[str, dict, int] | None:
    """(entry name, entry, this package's load address) for one package.

    An entry names one package, or - where a family loads the same image into
    several slots - all of them at once, in which case several packages share
    the entry and differ only by the slot they declare.
    """
    spec = manifest[family]
    slots = {int(k): int(v) for k, v in (spec.get("slots") or {}).items()}
    for name, entry in spec["overlays"].items():
        for slot in entry.get("slots") or [{"package": name, "slot": entry.get("slot")}]:
            if slot["package"] == package:
                return name, entry, slots.get(slot.get("slot"), int(spec["load_addr"]))
    return None


_OBJ = re.compile(r'^(\s*)\{ (.*) \},?$')


def _objects_block(text: str, family: str, entry: str) -> tuple[int, int, list[str]]:
    """Span of an entry's `objects = [...]` list, and its lines."""
    head = text.index(f"[{family}.overlays.{entry}]")
    start = text.index("objects = [", head) + len("objects = [\n")
    end = text.index("\n]", start)
    return start, end + 1, text[start:end].splitlines()


def _offset_of(line: str) -> int | None:
    """The offset an object's first subsegment starts at."""
    offs = [int(v, 16) for v in re.findall(r'(?:rodata|text|data|at) = "(0x[0-9A-F]+)"', line)]
    return min(offs) if offs else None


def _text_start(line: str) -> int | None:
    """Where an object's text run starts, or None if it owns no text."""
    m = re.search(r'text = "(0x[0-9A-F]+)"', line)
    return int(m.group(1), 16) if m else None


def _rodata_start(line: str) -> int | None:
    """Where an object's rodata run starts: its `rodata` key, or an asm run's `at`."""
    m = re.search(r'rodata = "(0x[0-9A-F]+)"', line) or (
        re.search(r'at = "(0x[0-9A-F]+)"', line) if 'kind = "rodata"' in line else None)
    return int(m.group(1), 16) if m else None


def _insert_shared_rodata(text: str, family: str, entry: str, at: int, size: int,
                          unit: str, remainder: str | None,
                          text_owner: str | None = None) -> tuple[str | None, str]:
    """Give a shared unit the rodata run [at, at+size) in one entry.

    The run is carved out of the object whose rodata holds it, with the same
    rules as text: at the start of that run the owner moves past it; mid-run
    what follows goes to the unit that took the code after the body - the
    remainder - since rodata follows its functions; an asm rodata run is simply
    cut in two.
    """
    start, end, lines = _objects_block(text, family, entry)
    me = next((i for i, l in enumerate(lines) if f'lib = true, unit = "{unit}",' in l), None)
    if me is None:
        return None, f"{unit} has no object in {entry}"
    runs = [(i, _rodata_start(l)) for i, l in enumerate(lines) if i != me and _rodata_start(l) is not None]
    held = [(i, s) for i, s in runs if s <= at]
    if not held:
        return None, "no object's rodata holds it"
    owner, owner_start = max(held, key=lambda r: r[1])
    bounds = [s for _i, s in runs if s > at] + [s for l in lines if (s := _text_start(l)) is not None and s > at]
    nxt = min(bounds, default=None)
    if nxt is not None and at + size > nxt:
        return None, "it runs past the next object's"
    rest = nxt is None or at + size < nxt
    note = ""
    lines[me] = lines[me].replace(f'unit = "{unit}", ', f'unit = "{unit}", rodata = "0x{at:X}", ', 1)
    line = lines[owner]
    asm = 'kind = "rodata"' in line
    if owner_start == at:
        if rest:
            lines[owner] = line.replace(f'"0x{at:X}"', f'"0x{at + size:X}"', 1)
        elif asm:
            del lines[owner]
        else:
            stripped = re.sub(r',\s*rodata = "0x[0-9A-F]+"|rodata = "0x[0-9A-F]+",\s*', "", line, count=1)
            if re.search(r'(text|data) = "', stripped):
                lines[owner] = stripped
            else:
                # the body was all the unit had left: it goes, source and all
                del lines[owner]
                gone = re.search(r'unit = "([^"]*)"', line)
                note = f"{gone.group(1) if gone else 'owner'} (no run left; its source goes)"
    elif rest:
        owner_unit = re.search(r'unit = "([^"]*)"', line)
        foreign = owner_unit is not None and owner_unit.group(1) != text_owner
        if asm or foreign:
            # Rodata that follows it but belongs to another unit's block - the
            # leading block the first unit owns holds many units' tables -
            # cannot stay with that owner, which would then own two runs. It
            # is asm-backed, so it becomes an assembly run of its own.
            lines.append(f'  {{ kind = "rodata", at = "0x{at + size:X}" }},')
            if foreign:
                note = (f"assembly from 0x{at + size:X} to 0x{nxt:X} "
                        f"(was {owner_unit.group(1)}'s)")
        elif remainder:
            r = next((i for i, l in enumerate(lines) if f'unit = "{remainder}",' in l), None)
            if r is None or "rodata =" in lines[r]:
                return None, f"the rodata after it has no owner ({remainder})"
            lines[r] = lines[r].replace(f'unit = "{remainder}", ', f'unit = "{remainder}", rodata = "0x{at + size:X}", ', 1)
        else:
            return None, "the rodata after it belongs to code before the body"
    lines.sort(key=lambda l: (_offset_of(l) if _offset_of(l) is not None else 0))
    return text[:start] + "\n".join(lines) + "\n" + text[end:], note


def _insert_shared(text: str, family: str, entry: str, at: int, size: int,
                   unit: str, overlay: str) -> tuple[str | None, str | None]:
    """Give one run to a shared unit, handing the remainder back to its owner.

    An object list has no holes: an object's text runs from its offset to the
    next object's, so the body is carved out of whichever object's *text* run
    holds it. Ownership is by text, not by an object's first offset: a unit's
    rodata can sit far ahead of its code, and taking the earliest offset once
    handed a body to a unit whose text started 0x4000 later.

    What follows the body stays with its owner. At the start of the run the
    owner's text simply moves past the body, keeping its name and its rodata,
    which belongs to the functions still in it. Mid-run the rest goes to a new
    unit, since one object cannot own two runs. A body that ends its run leaves
    nothing to hand on.
    """
    start, end, lines = _objects_block(text, family, entry)
    runs = [(i, _text_start(l)) for i, l in enumerate(lines) if _text_start(l) is not None]
    held = [(i, s) for i, s in runs if s <= at]
    if not held:
        return None, None
    owner, owner_start = max(held, key=lambda r: r[1])
    owned = re.search(r'unit = "([^"]*)"', lines[owner])
    _insert_shared.text_owner = owned.group(1) if owned else None
    # The run ends where the next object begins: more code, or the trailing
    # data and models after the code.
    bounds = [s for _i, s in runs if s > at]
    bounds += [int(v, 16) for l in lines if "kind" in l and "rodata" not in l
               for v in re.findall(r'at = "(0x[0-9A-F]+)"', l) if int(v, 16) > at]
    nxt = min(bounds, default=None)
    if nxt is not None and at + size > nxt:
        return None, None
    rest = nxt is None or at + size < nxt
    new = [f'  {{ lib = true, unit = "{unit}", text = "0x{at:X}" }},']
    tail = None
    if owner_start == at:
        line = lines[owner]
        if rest:
            lines[owner] = line.replace(f'text = "0x{at:X}"', f'text = "0x{at + size:X}"')
        else:
            # The body was the whole run: the owner keeps only what else it
            # owns, or goes if that is nothing.
            stripped = re.sub(r',\s*text = "0x[0-9A-F]+"', "", line)
            if re.search(r'(rodata|data) = "', stripped):
                lines[owner] = stripped
            else:
                del lines[owner]
                m = re.search(r'unit = "([^"]*)"', line)
                tail = f"{m.group(1) if m else 'owner'} (no run left; its source goes)"
    elif rest:
        n = 2
        taken = set(re.findall(r'unit = "[^"]*?([^/"]+)"', "\n".join(lines)))
        while f"{overlay}_{n}" in taken:
            n += 1
        tail = f"{overlay}_{n}"
        new.append(f'  {{ unit = "{overlay}/{tail}", text = "0x{at + size:X}" }},')
    lines.extend(new)
    lines.sort(key=lambda l: (_offset_of(l) if _offset_of(l) is not None else 0))
    return text[:start] + "\n".join(lines) + "\n" + text[end:], tail


def cmd_promote(data: dict, name: str, unit: str | None, run: bool = False) -> int:
    """Move a body into the shared library, src/lib.

    Does the plumbing that is identical either way - the span in
    configs/USA/overlays.toml for every overlay that carries the body, and the
    shared symbol in each of their symbol maps - so the caller only has to deal
    with the body itself.

    Carriers come from every family the manifest generates, since one library
    object links into any of them; each is edited in its own family's entry and
    symbol map, at its own load address. main, gameplay and title link once and
    are never carriers. Code that is identical across families is not thereby
    the same routine, so a promotion that spans families says so and leaves the
    judgement to the caller.

    An overlay that contains the body twice is left out: ld includes an input
    object once, so the second slot would go unfilled.

    A body that calls its own overlay's code is promoted together with its
    callees when every carrier's callees are themselves one shared body: they
    are promoted first, under shared names, and the report lists the calls the
    moved C has to rename. Two things still refuse a promotion. A reference to
    the overlay's own *data* does, because each carrier's copy of the data sits
    at its own address and nothing yet resolves one shared name to all of them;
    and so does a call whose target differs between carriers.
    """
    import tomllib

    hit = next((f for f in data["functions"] if f["name"] == name), None)
    if hit is None:
        print(f"{name}: not found", file=sys.stderr)
        return 1
    families = library_families()
    if run:
        plan, members, why = _run_plan(data, hit, families)
    else:
        (plan, why), members = _promotion_plan(data, hit, families), []
    if why:
        print(f"{name}: {why}")
        return 1
    # A run is one unit: named once, for its first function.
    run_texts = {f["text"] for f in members}
    if members:
        first = members[0]
        fams = sorted({family_of(f) for f in _carriers(classes(data, "text")[first["text"]], families)[0]})
        unit = unit or f"{fams[0] + '_shared' if len(fams) == 1 else 'shared'}_{first['name'].split('_')[-1].lower()}"

    cl = classes(data, "text")
    text_of = {(f["overlay"], f["name"]): f["text"] for f in data["functions"]}
    manifest = tomllib.loads(MANIFEST.read_text(encoding="utf-8"))
    text = MANIFEST.read_text(encoding="utf-8")
    syms: dict[Path, str] = {}
    spans: list[tuple] = []
    staged = []
    shared_name: dict[str, str] = {}   # body text hash -> its shared symbol
    for body in plan:
        # Only the body that was asked for takes an explicit unit name - or,
        # promoting a run, every function of it takes the run's.
        in_run = body["text"] in run_texts
        wanted = unit if (in_run or body["text"] == hit["text"]) else None
        result = _stage_promotion(body, cl[body["text"]], wanted, manifest, spans, syms,
                                  own_sym=in_run)
        if result is None:
            return 1
        shared_name[body["text"]] = result["sym"]
        staged.append(result)

    # A run stages each function on its own; one unit owns one run per section
    # in each entry, so the pieces must meet end to end and are joined here.
    joined: dict[tuple, list] = {}
    for s in spans:
        joined.setdefault((s[0], s[1], s[2], s[5]), []).append(s)
    spans = []
    for (kind, fam, entry, u), parts in joined.items():
        parts.sort(key=lambda s: s[3])
        for a, b in zip(parts, parts[1:]):
            if a[3] + a[4] != b[3]:
                print(f"{entry}: {u}'s {kind} is not one run (0x{a[3]:X}+0x{a[4]:X}, "
                      f"then 0x{b[3]:X}); aborting", file=sys.stderr)
                return 1
        spans.append((kind, fam, entry, parts[0][3], sum(s[4] for s in parts), u, parts[0][6]))

    # Carve every body out of its entry in address order. Inserting a later
    # body first cuts its owner's run mid-way and strands the earlier code in a
    # new unit, away from the rodata its owner keeps.
    tails = []
    made: dict[tuple[str, str, str], str] = {}   # (family, entry, unit) -> remainder unit
    owners: dict[tuple[str, str, str], str | None] = {}   # ... -> unit whose text held it
    for _k, family, entry_name, start, size, u, room in sorted(
            (s for s in spans if s[0] == "text"), key=lambda s: s[1:4]):
        new_text, tail = _insert_shared(text, family, entry_name, start, size, u, room)
        if new_text is None:
            print(f"{entry_name}: no object's text run holds 0x{start:X}+0x{size:X}; "
                  f"aborting", file=sys.stderr)
            return 1
        text = new_text
        owners[(family, entry_name, u)] = _insert_shared.text_owner
        if tail:
            tails.append(f"{entry_name}: remainder after 0x{start:X} goes to {tail}")
            if "(" not in tail:
                made[(family, entry_name, u)] = f"{room}/{tail}"
    # Then each body's own jump tables: the unit takes that rodata in every
    # carrier, carved out of the run that held it the way the text was.
    for _k, family, entry_name, start, size, u, room in sorted(
            (s for s in spans if s[0] == "rodata"), key=lambda s: s[1:4]):
        new_text, why = _insert_shared_rodata(text, family, entry_name, start, size, u,
                                              made.get((family, entry_name, u)),
                                              owners.get((family, entry_name, u)))
        if new_text is None:
            print(f"{entry_name}: cannot give {u} the rodata at 0x{start:X}: {why}; "
                  f"aborting", file=sys.stderr)
            return 1
        text = new_text
        tails.append(f"{entry_name}: {u} takes the rodata at 0x{start:X}+0x{size:X}")
        if why.startswith("assembly"):
            tails.append(f"{entry_name}: rodata {why}")
        elif why:
            tails.append(f"{entry_name}: remainder after 0x{start:X} goes to {why}")

    # Nothing is written until every body of the plan has validated: a partial
    # write would leave a caller shared with a callee that is not.
    for path, sym_text in syms.items():
        path.write_text(sym_text, encoding="utf-8")
    MANIFEST.write_text(text, encoding="utf-8")

    callees = len(staged) - max(len(members), 1)
    if members:
        print(f"{name}: promoted with its neighbours as one unit of "
              f"{len(members)} function(s)"
              + (f", after {callees} callee body/bodies its carriers share:" if callees else ":"))
    elif callees:
        print(f"{name}: calls {callees} body/bodies its carriers share, promoted first:")
    for result in staged:
        _report_promotion(result, shared_name, text_of)
    for tail in tails:
        print(f"  {tail}")
    print("  run: python3 ninja_config.py && ./tools/build-and-verify.sh")
    return 0


def _carriers(cls: list[dict], families: frozenset[str]) -> tuple[list[dict], list[dict], set[str], list[str]]:
    """(carriers, promoted copies, overlays holding it twice, overlays outside).

    A copy under `<family>/lib` is the shared body itself, already promoted -
    not a carrier; it has no manifest entry. An overlay that contains the body
    twice is left out: ld includes an input object once, so the second slot
    would go unfilled. A copy in a family that links once (main, gameplay,
    title) cannot carry a library unit.
    """
    outside = sorted({f["overlay"] for f in cls if family_of(f) not in families})
    copies = [f for f in cls if family_of(f) in families]
    promoted = [f for f in copies if f["overlay"].split("/")[-1] == "lib"]
    copies = [f for f in copies if f["overlay"].split("/")[-1] != "lib"]
    twice = {u for u, n in collections.Counter(f["overlay"] for f in copies).items() if n > 1}
    keep = [f for f in copies if f["overlay"] not in twice]
    return keep, promoted, twice, outside


_LIB_ITEM = re.compile(r"^INCLUDE_ASM\([^,]+,\s*(\w+)\)|^[A-Za-z_][\w \t*]*\b(\w+)\s*\([^;{]*\)\s*\n?\{", re.M)


def _lib_unit_of(name: str) -> tuple[str, int] | None:
    """(library unit, functions it holds) for a promoted body, from src/lib.

    The index files every promoted copy under a bare `lib`, so the unit that
    holds one is found by the definition or stub that names it. The count
    matters because a unit is linked whole: a body that already sits in a
    multi-function unit cannot be shared by reusing that unit.
    """
    for c in sorted(Path("src/lib").glob("*.c")):
        text = c.read_text(errors="ignore")
        items = [a or b for a, b in _LIB_ITEM.findall(text)]
        if name in items:
            return c.stem, len(set(items))
    return None


def _is_jump_table(ref: str) -> bool:
    return ref.startswith("jtbl_") or bool(re.fullmatch(r"Actor\d{5}_Jt[0-9A-F]+", ref))


def _table_extent(family: str, overlay: str, func: str, table: str) -> int | None:
    """Bytes the jump table occupies, from its definition in the carrier's asm.

    splat migrates a table into the file of the function that owns it, so it is
    looked up there first and then anywhere under the carrier's directory.
    """
    base = ASM_ROOT / family
    files = list(base.glob(f"*/{overlay}/*/{func}.s")) + list(base.glob(f"*/{overlay}/**/{table}.s"))
    for path in files:
        text = path.read_text(errors="replace")
        m = re.search(rf"^dlabel {re.escape(table)}$(.*?)^enddlabel {re.escape(table)}$", text, re.M | re.S)
        if m:
            return 4 * len(WORD.findall(m.group(1)))
    return None


def _promotion_plan(data: dict, hit: dict, families: frozenset[str],
                    internal: frozenset[str] = frozenset()) -> tuple[list[dict], str | None]:
    """The bodies to promote for `hit`, callees before callers, or why not.

    A body that references its own overlay can still be shared when every such
    reference is a call to a function whose body is itself shared by the same
    carriers: promote the callee first, under a shared name every carrier
    defines, and the caller's reference is no longer overlay-local. That walks
    down the call graph until it reaches bodies with no local references. A
    local reference to *data* still blocks it - each carrier's data sits at its
    own address, and nothing yet resolves one shared name to all of them - and
    so does a call whose target differs between carriers.

    Each returned body is a representative record of its class.
    """
    cl = classes(data, "text")
    by = {(f["overlay"], f["name"]): f for f in data["functions"]}
    refd: dict[tuple[str, str], set[str]] = collections.defaultdict(set)
    for f in data["functions"]:
        for r in f["refs"]:
            refd[(f["overlay"], r)].add(f["text"])
    order: list[dict] = []
    state: dict[str, str] = {}

    def visit(body: dict, reach: set[str] | None) -> str | None:
        if state.get(body["text"]) in ("active", "done"):
            return None           # already planned, or a cycle that will be
        state[body["text"]] = "active"
        keep, promoted, _twice, _outside = _carriers(cl[body["text"]], families)
        if promoted:
            held = _lib_unit_of(promoted[0]["name"])
            if held is None:
                return (f"{body['name']} is already shared as {promoted[0]['name']}, "
                        f"but no file in src/lib defines it")
            if held[1] > 1:
                return (f"{body['name']} is already in the library as part of "
                        f"{held[0]}, a unit of {held[1]} functions, and a unit is "
                        f"linked whole - that is a consolidation, not a promotion")
        if promoted and len(keep) == 0:
            state[body["text"]] = "done"
            return None           # served by the library already
        if reach is not None and not reach <= {f["overlay"] for f in keep}:
            missing = sorted(reach - {f["overlay"] for f in keep})
            return (f"calls {body['name']}, which cannot be shared into "
                    f"{', '.join(missing)} (held twice there, or not carried)")
        if reach is None and len(keep) < 2 and not promoted:
            return "only one copy the library can reach, nothing to share"
        if len(keep) < (1 if promoted else 2):
            return "every overlay carrying it contains it twice; cannot share"
        callees: list[list[str]] = []
        for f in keep:
            own = []
            for r in f["refs"]:
                if not is_local_ref(r, f["unit"]):
                    continue
                g = by.get((f["overlay"], r))
                if g is None:
                    # A jump table only this body's copies use is the body's
                    # own: the compiler regenerates it from the C switch, and
                    # promotion carries its rodata along.
                    if _is_jump_table(r) and refd[(f["overlay"], r)] <= {body["text"]}:
                        continue
                    return (f"references its own overlay's data "
                            f"({f['overlay'].split('/', 1)[1]}: {r})")
                if g["text"] in internal:
                    continue      # another function of the same unit
                own.append(g["text"])
            callees.append(sorted(own))
        if any(c != callees[0] for c in callees):
            return "calls its own overlay's code, and the carriers' callees differ"
        overlays = {f["overlay"] for f in keep}
        for t in dict.fromkeys(callees[0]):
            callee = next(g for g in cl[t] if g["overlay"] in overlays)
            why = visit(callee, overlays)
            if why:
                return why
        state[body["text"]] = "done"
        order.append(body)
        return None

    why = visit(hit, None)
    return (order, None) if why is None else ([], why)


def _grow_run(data: dict, hit: dict, families: frozenset[str]) -> list[dict]:
    """The functions around `hit` that every carrier holds in the same order.

    A source file holds several functions, and a unit of one is an artifact of
    promoting one body at a time. A neighbour joins the run when, in every
    carrier, it sits directly against the run, its body is the same in all of
    them, exactly the same overlays carry it, and some copy is matched - so its
    C exists to move. Returned in address order, as the hit carrier's copies.
    """
    cl = classes(data, "text")
    keep = _carriers(cl[hit["text"]], families)[0]
    ovs = {f["overlay"] for f in keep}
    seq: dict[str, list[dict]] = {}
    for f in data["functions"]:
        if f["overlay"] in ovs:
            seq.setdefault(f["overlay"], []).append(f)
    for ov in seq:
        seq[ov].sort(key=lambda f: int(f["vram"], 16))
    at = {ov: next(i for i, f in enumerate(seq[ov]) if f["text"] == hit["text"]) for ov in ovs}
    home = hit["overlay"] if hit["overlay"] in ovs else sorted(ovs)[0]
    lo = hi = 0
    for step in (-1, 1):
        k = 0
        while True:
            nb = {}
            for ov in ovs:
                i, j = at[ov] + (k if step == 1 else -k), at[ov] + (k + 1 if step == 1 else -k - 1)
                if not (0 <= j < len(seq[ov])):
                    nb = None
                    break
                a, b = sorted((seq[ov][i], seq[ov][j]), key=lambda f: int(f["vram"], 16))
                if int(a["vram"], 16) + 4 * a["words"] != int(b["vram"], 16):
                    nb = None
                    break
                nb[ov] = seq[ov][j]
            if not nb or len({g["text"] for g in nb.values()}) != 1:
                break
            t = next(iter(nb.values()))["text"]
            if {f["overlay"] for f in _carriers(cl[t], families)[0]} != ovs:
                break
            if not any(g.get("state") == "matched" for g in cl[t]):
                break
            k += 1
        if step == -1:
            lo = k
        else:
            hi = k
    i = at[home]
    return seq[home][i - lo:i + hi + 1]


def _run_plan(data: dict, hit: dict, families: frozenset[str]) -> tuple[list[dict], list[dict], str | None]:
    """(plan, run members) for promoting `hit` with its neighbours as one unit.

    The run is trimmed to the longest stretch around `hit` whose members all
    plan: a member that references its own overlay's data ends it on that side.
    """
    members = _grow_run(data, hit, families)
    k = next(i for i, f in enumerate(members) if f["text"] == hit["text"])
    lo, hi = 0, len(members) - 1
    while True:
        run = members[lo:hi + 1]
        internal = frozenset(f["text"] for f in run)
        plans = [_promotion_plan(data, f, families, internal) for f in run]
        bad = [i for i, (_p, why) in enumerate(plans) if why]
        if not bad:
            break
        if any(lo + i == k for i in bad):
            return [], [], plans[k - lo][1]
        # drop the failing member and everything beyond it on its side
        worst = bad[0] + lo
        if worst < k:
            lo = worst + 1
        else:
            hi = worst - 1
    texts = {f["text"] for f in run}
    order, seen = [], set()
    for plan, _why in plans:
        for b in plan:
            if b["text"] not in texts and b["text"] not in seen:
                seen.add(b["text"])
                order.append(b)
    return order + run, run, None


def _stage_promotion(body: dict, cls: list[dict], unit: str | None, manifest: dict,
                     spans: list[tuple], syms: dict[Path, str], own_sym: bool = False) -> dict | None:
    """Give one body its unit: spans onto `spans`, symbols into `syms`.

    Returns what was done, or None after printing why the body cannot be
    shared. Nothing is written to disk here, and the manifest is edited later,
    all spans at once: the order they go in changes the result.
    """
    name = body["name"]
    keep, promoted, twice, outside = _carriers(cls, library_families())
    if promoted and unit is None:
        # Reuse the unit only when it holds this body alone: a unit is linked
        # whole, so reusing a multi-function one would drop all of it in here.
        held = _lib_unit_of(promoted[0]["name"])
        if held is None or held[1] > 1:
            print(f"{name}: already in the library, but not as a unit of its own "
                  f"({held[0] + ', ' + str(held[1]) + ' functions' if held else 'no file defines it'})",
                  file=sys.stderr)
            return None
        unit = held[0]
    if not keep:
        print(f"{name}: every copy is already served by the shared body")
        return None
    # An unmatched body is shared as one disassembly file, and every overlay
    # writes it, so that file is only well-defined when the copies are
    # byte-identical. A matched body has no such limit: the compiler
    # regenerates it for each link address.
    if not any(f.get("state") == "matched" for f in keep + promoted):
        images = len({f["raw"] for f in keep})
        if images > 1:
            print(f"{name}: cannot be shared while unmatched - "
                  f"{images} different byte images.")
            print("  Match it first, then promote: the compiler regenerates the body")
            print("  per link address, which is what makes the differing copies one source.")
            return None

    # A unit one family carries is named for it; one that several carry
    # belongs to none of them.
    carriers = sorted({family_of(f) for f in keep})
    owner = f"{carriers[0]}_shared" if len(carriers) == 1 else "shared"
    unit = unit or f"{owner}_{name.split('_')[-1].lower()}"
    # In a run each function keeps a symbol of its own inside the one unit.
    sym = "".join(w.capitalize() for w in
                  (f"{owner}_{name.split('_')[-1].lower()}" if own_sym else unit).split("_"))
    size = body["words"] * 4

    edited: set[tuple[str, str]] = set()
    for f in sorted(keep, key=lambda f: f["overlay"]):
        room = f["overlay"].split("/")[-1]
        family = family_of(f)
        targets = _carrier_targets(manifest, family, room, f)
        if targets is None:
            print(f"{room}: cannot place {name} in every package it stands for; "
                  f"aborting", file=sys.stderr)
            return None
        for entry_name, package, start, addr in targets:
            # Several packages can share one entry - the slots of one actor -
            # and the entry describes the image once, so it is edited once.
            # Each package still needs the symbol in its own map, since the
            # address differs per slot.
            if (family, entry_name) not in edited:
                edited.add((family, entry_name))
                spans.append(("text", family, entry_name, start, size, unit, room))
                tables = _own_tables(f, family, room, addr - start)
                if tables is None:
                    print(f"{name}: its jump tables in {room} are not one contiguous run; "
                          f"aborting", file=sys.stderr)
                    return None
                if tables:
                    spans.append(("rodata", family, entry_name, tables[0], tables[1], unit, room))
            sym_path = Path(f"configs/USA/sym/{family}/{package}.txt")
            sym_text = syms.get(sym_path) or sym_path.read_text(encoding="utf-8")
            syms[sym_path] = _add_shared_symbol(sym_text, sym, addr, f["name"])

    return {"name": name, "sym": sym, "unit": unit, "keep": keep,
            "copies": len(keep) + len(twice), "twice": twice,
            "outside": outside, "carriers": carriers, "promoted": promoted}


def _own_tables(f: dict, family: str, overlay: str,
                load: int) -> tuple[int, int] | tuple[()] | None:
    """(offset, size) of the jump-table run a copy owns, () if none, None if split.

    `load` is the package's load address. A table named by offset
    (`Actor01100_Jt0004C`) gives it directly; `jtbl_<unit>_<VRAM>` gives the
    address. Several tables must sit back to back: the unit's rodata is one run.
    """
    runs = []
    for r in f["refs"]:
        if not (_is_jump_table(r) and is_local_ref(r, f["unit"])):
            continue
        m = re.fullmatch(r"Actor\d{5}_Jt([0-9A-F]+)", r)
        off = int(m.group(1), 16) if m else int(r.rsplit("_", 1)[1], 16) - load
        size = _table_extent(family, overlay, f["name"], r)
        if size is None:
            return None
        runs.append((off, size))
    if not runs:
        return ()
    runs.sort()
    for (a, n), (b, _m) in zip(runs, runs[1:]):
        if a + n != b:
            return None
    return runs[0][0], runs[-1][0] + runs[-1][1] - runs[0][0]


def _carrier_targets(manifest: dict, family: str, overlay: str,
                     f: dict) -> list[tuple[str, str, int, int]] | None:
    """(entry, package, file offset, address) for each package a copy stands for.

    A copy is one overlay in the index, but a merged entry is several packages -
    the slots of one image - and each needs the shared symbol in its own map at
    its own address. The index keeps one address per function, from whichever
    slot was split last, so each package's address is read from its own symbol
    map instead, where the merged actors name every function. The offset has to
    agree across the packages, or they are not one image.
    """
    spec = manifest[family]
    slots = {int(k): int(v) for k, v in (spec.get("slots") or {}).items()}
    entry = spec["overlays"].get(overlay)
    if entry is not None and entry.get("slots"):
        out = []
        for slot in entry["slots"]:
            load = slots.get(slot.get("slot"), int(spec["load_addr"]))
            sym_text = Path(f"configs/USA/sym/{family}/{slot['package']}.txt").read_text(
                encoding="utf-8")
            m = re.search(rf"^{re.escape(f['name'])} = (0x[0-9A-Fa-f]+);", sym_text, re.M)
            if m is None:
                return None
            addr = int(m.group(1), 16)
            out.append((overlay, slot["package"], addr - load, addr))
        return out if len({o for _, _, o, _ in out}) == 1 else None
    found = _entry_of(manifest, family, overlay)
    if found is None:
        return None
    entry_name, _entry, load = found
    addr = int(f["vram"], 16)
    return [(entry_name, overlay, addr - load, addr)]


def _add_shared_symbol(sym_text: str, sym: str, addr: int, local: str) -> str:
    """`sym_text` with the shared symbol defined at `addr`.

    Match the whole assignment, not the bare name: a carrier that already
    aliases a body's overlay-local callees holds `<Sym>Sub0`, which contains
    `<Sym>` as a substring - so a plain `in` test decided the shared symbol was
    already there and the body went undefined at link.

    The carrier keeps the name it knew the body by as an absolute alias, the
    way actor_401000 keeps func_actor_401000_80132EF0 beside its shared
    driver: its own sources still call it by that name, and the alias makes
    the reference resolve to the shared body at link. A name the map already
    defines - the merged actors name every function by offset - is marked
    absolute; a generated `func_` name, which no map lists, is added.
    """
    if re.search(rf"^{re.escape(sym)} = ", sym_text, re.M):
        return sym_text
    # splat refuses two names at one address unless the later one is absolute,
    # so every existing name for the address moves after the shared symbol.
    lines, aliases = [], []
    for line in sym_text.rstrip().split("\n"):
        m = re.match(r"^(\w+) = (0x[0-9A-Fa-f]+);(.*)$", line)
        if m and int(m.group(2), 16) == addr and "type:label" not in m.group(3):
            if "absolute:True" not in m.group(3):
                line += " absolute:True" if "//" in m.group(3) else " // absolute:True"
            aliases.append(line)
        else:
            lines.append(line)
    lines.append(f"{sym} = 0x{addr:08X}; // shared body, see src/lib/")
    lines += aliases
    if not re.search(rf"^{re.escape(local)} = ", sym_text, re.M):
        lines.append(f"{local} = 0x{addr:08X}; // type:func absolute:True")
    return "\n".join(lines) + "\n"


def _report_promotion(r: dict, shared_name: dict[str, str],
                      text_of: dict[tuple[str, str], str]) -> None:
    print(f"{r['sym']}: {len(r['keep'])} of {r['copies']} copies share src/lib/{r['unit']}.c")
    if r["twice"]:
        print(f"  left alone (contains it twice): {', '.join(sorted(r['twice']))}")
    if r["outside"]:
        print(f"  left alone (links once, cannot carry a library unit): "
              f"{', '.join(r['outside'])}")
    if len(r["carriers"]) > 1:
        print(f"  carriers span families ({', '.join(r['carriers'])}): identical code is not")
        print("  the same routine - check the copies are one routine before building on it.")
    # A moved body runs in every carrier, so it must call its callees by the
    # shared name: one carrier's local name does not exist in the others.
    renames = sorted({(ref, shared_name[t]) for f in r["keep"] for ref in f["refs"]
                      for t in [text_of.get((f["overlay"], ref))]
                      if t in shared_name and is_local_ref(ref, f["unit"])})
    matched = [f for f in r["keep"] if f.get("state") == "matched"]
    if matched:
        # Name the copy that has the C, which need not be the one asked about.
        src = matched[0]
        print(f"  {src['name']} ({src['overlay'].split('/', 1)[1]}) is already "
              f"decompiled - move its C body into src/lib/{r['unit']}.c as "
              f"{r['sym']}(), remove it from that overlay's .c, delete the other "
              f"carriers' INCLUDE_ASM for it, then rebuild.")
    elif r["promoted"]:
        print("  the shared unit already exists; its new carriers link it.")
    else:
        print("  splat will write the shared stub on the next split.")
    if renames:
        print("  in the moved body, call its callees by their shared names: "
              + ", ".join(f"{a} -> {b}" for a, b in renames))


def cmd_solved(data: dict, min_words: int) -> int:
    """Unmatched functions whose body is already matched in **another** overlay.

    The other-overlay part is the whole point. Two copies inside one overlay are
    two separate functions that each have to be matched - they cannot share an
    object, because the overlay links once. Only a copy in a different overlay
    is work already done, reachable by promoting the body into the shared
    library instead of matching it again.
    """
    cl = classes(data, "text")
    families = library_families()
    out: set[int] = set()
    for v in cl.values():
        if v[0]["words"] < min_words:
            continue  # a stub is cheaper to match than to plumb into lib/
        for f in v:
            if f.get("state") == "matched" or family_of(f) not in families:
                continue
            # A match is reachable from any family the library links into -
            # the same set `promote` serves. One in main, gameplay or title
            # is not: they link once, so their copy cannot become the shared
            # unit, and a room's copy of a gameplay body still needs matching.
            if any(
                o.get("state") == "matched"
                and o["overlay"] != f["overlay"]
                and family_of(o) in families
                for o in v
            ):
                out.add(id(f))
    for name in names_wholly_in(data, out):
        print(name)
    return 0


def names_wholly_in(data: dict, chosen: set[int]) -> list[str]:
    """Names every one of whose unmatched functions is in `chosen` (by id()).

    `solved` and `ceded` feed a pick that excludes by *name*, and names repeat
    across overlays - alias symbols such as ActorsShared80131f9cSub1 name four
    different bodies. Emitting a name because one of its functions qualifies
    would skip the others with it. A matched function is never picked, so it
    does not hold a name back.
    """
    wholly: dict[str, bool] = {}
    for f in data["functions"]:
        if f.get("state") == "matched":
            continue
        wholly[f["name"]] = wholly.get(f["name"], True) and id(f) in chosen
    return sorted(n for n, ok in wholly.items() if ok)


def owner_rank(order: list[str]):
    """Sort key choosing which carrier of a body owns it, for a sweep list.

    A promoted copy in `<family>/lib` owns outright: matching it serves every
    carrier. Otherwise the first carrier in list order owns, which for a cover
    order (local/actors_sweep_order.txt) is the overlay the list meant to take
    the body from. Unlisted carriers rank after every listed one, so ownership
    never lands on an overlay the sweep will not reach while a listed carrier
    exists; ties break on the overlay path so every lane computes the same owner.
    """
    pos = {}
    for i, entry in enumerate(order):
        pos.setdefault(entry.split("/")[-1], i)

    def key(f: dict) -> tuple:
        if f["overlay"].split("/")[-1] == "lib":
            return (-1, f["overlay"])
        return (pos.get(f["overlay"].split("/")[-1], len(order)), f["overlay"])

    return key


def cmd_ceded(data: dict, min_words: int, order: list[str]) -> int:
    """Unmatched functions whose body another overlay owns under a sweep list.

    `solved` only skips a body once some copy is *matched*, and only as far as
    the tree it runs in knows. Lanes working sibling overlays at the same time,
    or from worktrees cut before a sibling's match landed, each match the body
    again - and a body that gives up is not solved at all, so every carrier
    fights it separately. Giving each body one owner closes both without any
    live coordination: every lane using the same list computes the same owner,
    and the rest skip it. A skipped copy is parked exactly as a solved one is,
    for promotion or a later match of its own.
    """
    key = owner_rank(order)
    listed = {entry.split("/")[-1] for entry in order}
    ceded: set[int] = set()   # id() of each ceded function record
    for v in classes(data, "text").values():
        if v[0]["words"] < min_words:
            continue  # a stub is matched per overlay, like `solved`
        by_family: dict[str, list[dict]] = collections.defaultdict(list)
        for f in v:
            by_family[f["overlay"].split("/")[1]].append(f)
        for copies in by_family.values():
            if len({f["overlay"] for f in copies}) < 2:
                continue
            if any(f.get("state") == "matched" for f in copies):
                continue  # `solved` already covers it
            # A list only decides bodies it can reach: with no listed carrier
            # (another family, or overlays the cover order left out) the owner
            # would be an arbitrary name that no lane of this list sweeps.
            if not any(f["overlay"].split("/")[-1] in listed or f["overlay"].endswith("/lib")
                       for f in copies):
                continue
            owner = min(copies, key=key)["overlay"]
            ceded.update(id(f) for f in copies if f["overlay"] != owner)
    for name in names_wholly_in(data, ceded):
        print(name)
    return 0


def cmd_stats(data: dict) -> int:
    fns = [f for f in data["functions"] if f.get("state") != "matched"]
    by_family = collections.Counter(f["overlay"].split("/")[1] for f in fns)
    print(f"{len(fns)} functions across {len(by_family)} family/families")
    # Class over the same set `fns` counts, not over everything: mixing an
    # unmatched population with classes that include the matched ones makes
    # "redundant copies" a difference between two different totals, and it goes
    # negative as soon as more bodies are matched than are duplicated.
    todo = {"functions": fns}
    for key, label in (("text", "same body"), ("raw", "same bytes")):
        cl = classes(todo, key)
        red = len(fns) - len(cl)
        wt = sum(f["words"] for f in fns)
        wu = sum(v[0]["words"] for v in cl.values())
        print(f"  {label:12}: {len(cl):5} distinct, {red:5} redundant copies "
              f"({100*red//len(fns)}% of functions, {100*(wt-wu)//wt}% of instructions)")
    cl = classes(todo, "text")
    hist = collections.Counter(len(v) for v in cl.values())
    multi = sum(c for n, c in hist.items() if n > 1)
    print(f"\n  bodies appearing more than once: {multi}")
    for n in (2, 3, 5, 10, 20, 50):
        c = sum(v for k, v in hist.items() if k >= n)
        print(f"    in >= {n:3} places: {c}")
    print("\n  biggest wins (copies x instructions saved):")
    ranked = sorted(cl.values(), key=lambda v: -(len(v) - 1) * v[0]["words"])
    for v in ranked[:8]:
        print(f"    {len(v):3} copies x {v[0]['words']:4} = {(len(v)-1)*v[0]['words']:6} saved   {v[0]['name']}")
    return 0


def cmd_find(data: dict, name: str) -> int:
    cl_text, cl_raw = classes(data, "text"), classes(data, "raw")
    hit = next((f for f in data["functions"] if f["name"] == name), None)
    if hit is None:
        print(f"{name}: not found", file=sys.stderr)
        return 1
    same_src = cl_text[hit["text"]]
    same_bytes = cl_raw[hit["raw"]]
    print(f"{name}  ({hit['words']} instructions, {hit['overlay']})")
    print(f"  same body: {len(same_src)} copies   identical bytes: {len(same_bytes)}")
    for f in sorted(same_src, key=lambda f: f["overlay"]):
        mark = "=" if f["raw"] == hit["raw"] else "~"
        state = "matched" if f.get("state") == "matched" else ""
        print(f"    {mark} {f['overlay']:36} {f['name']} {state}")
    print("\n  = identical bytes, ~ same body at a different link offset")
    return 0


def cmd_shared(data: dict, minimum: int, refs: bool) -> int:
    cl = classes(data, "text")
    ranked = sorted((v for v in cl.values() if len(v) >= minimum),
                    key=lambda v: -(len(v) - 1) * v[0]["words"])
    print(f"{len(ranked)} bodies in >= {minimum} places")
    for v in ranked:
        line = f"  {len(v):3} copies  {v[0]['words']:4} insns  {v[0]['name']}"
        if refs:
            own = {r for f in v for r in f["refs"] if is_local_ref(r, f["unit"])}
            line += f"   room-local refs: {len(own)}"
        print(line)
    return 0


def cmd_similar(data: dict, name: str, topn: int, floor: float) -> int:
    """Rank already-matched bodies that resemble `name`, in four classes.

    One blended score would hide what the caller needs, because a candidate can
    be strong in one class and useless in the others:

      shape   opcode order, operands dropped - "the same code against different
              struct offsets". Port the body and re-field it.
      fields  the multiset of load/store displacements - "touches the same
              offsets", so the type it needs may already exist.
      calls   the jal target sequence - "same helpers in the same order", the
              most specific signal of shared purpose, and it carries argument
              types.
      cflow   branch opcodes alone. Reported last and gated on length: on a
              short function every branch skeleton looks alike, and it will
              happily rank a weapon body against a room one.

    Only matched functions are offered - a candidate earns its place precisely
    because its C body can be read - and the file holding that body is printed,
    since hunting for it is the cost this is meant to remove.
    """
    fns = {f["name"]: f for f in data["functions"]}
    tgt = fns.get(name)
    if tgt is None:
        print(f"{name}: not in the index")
        return 1
    pool = [f for f in data["functions"]
            if f["state"] == "matched" and f["name"] != name and f["words"] >= 10]
    tshape, tdisp = tgt.get("shape", ""), collections.Counter(tgt.get("disp") or [])
    cfc = cflow_chars(data)
    tcalls, tcflow = tgt.get("calls") or [], cflow_of(tgt, cfc)

    def rank(score):
        out = []
        for f in pool:
            if not (0.6 * tgt["words"] <= f["words"] <= 1.6 * tgt["words"]):
                continue
            s = score(f)
            if s >= floor:
                out.append((s, f))
        return sorted(out, key=lambda kv: (-kv[0], kv[1]["name"]))[:topn]

    def seq(a, b):
        return difflib.SequenceMatcher(None, a, b, autojunk=False).ratio() if a and b else 0.0

    def jac(a, b):
        if not a or not b:
            return 0.0
        return sum((a & b).values()) / sum((a | b).values())

    classes_ = [
        ("shape",  lambda f: seq(tshape, f.get("shape", ""))),
        ("fields", lambda f: jac(tdisp, collections.Counter(f.get("disp") or []))),
    ]
    # A one-call sequence matches every other one-call sequence at 1.00, which
    # is not a signal. Two is the shortest sequence whose *order* means anything.
    if len(tcalls) >= 2:
        classes_.append(("calls", lambda f: seq(tcalls, f.get("calls") or [])))
    if tgt["words"] >= 40:
        classes_.append(("cflow", lambda f: seq(tcflow, cflow_of(f, cfc))))

    agree = collections.Counter()
    results = {}
    for cls, score in classes_:
        results[cls] = rank(score)
        for _s, f in results[cls]:
            agree[f["name"]] += 1
    # cflow is corroboration, never a finding on its own. A branch skeleton is
    # generic even well past the length gate: an actor task function scored 1.00
    # against four memory-card state machines in src/main/mc.c, and a brief
    # showing only that sends the reader somewhere useless. Keep it when another
    # class also found something; otherwise say nothing.
    if not any(results.get(c) for c in ("shape", "fields", "calls")):
        results["cflow"] = []

    print(f"{name}: {tgt['words']} instructions, {len(tcalls)} call(s)")
    any_hit = False
    for cls, _ in classes_:
        if not results[cls]:
            continue
        any_hit = True
        print(f"  {cls}:")
        for s, f in results[cls]:
            star = " *" if agree[f["name"]] > 1 else ""
            print(f"    {s:5.2f}  {f['name']:<44} {f['overlay']}{star}")
            src = body_file(f)
            if src:
                print(f"           body: {src}")
    if not any_hit:
        print(f"  no matched body scores >= {floor:.2f}")
    elif any(n > 1 for n in agree.values()):
        print("  * appears in more than one class - the strongest signal here")
    return 0


BRANCH_OPS = frozenset({"beq", "bne", "blez", "bgtz", "bltz", "bgez", "beqz",
                        "bnez", "bgtzl", "beql", "bnel", "b", "j", "jr", "jal"})


def cflow_chars(data: dict) -> frozenset[str]:
    """Which encoded characters stand for a branch, for this cache's vocab."""
    vocab = data.get("vocab") or []
    return frozenset(chr(0x4E00 + i) for i, op in enumerate(vocab) if op in BRANCH_OPS)


def cflow_of(f: dict, chars: frozenset[str]) -> str:
    """The branch-only projection of a shape string."""
    return "".join(c for c in f.get("shape", "") if c in chars)


def body_file(f: dict) -> str | None:
    """Where the matched C body lives, so the caller can read it."""
    # overlay is "<ver>/<family>/<name>"; src/ has no version component.
    rel = f["overlay"].split("/", 1)[1] if "/" in f["overlay"] else f["overlay"]
    fam = rel.split("/")[0]
    for pat in (f"src/{rel}", "src/lib", f"src/{fam}"):
        d = Path(pat)
        if not d.is_dir():
            continue
        for c in sorted(d.glob("*.c")):
            if re.search(rf"^[A-Za-z_][\w \t*]*\b{re.escape(f['name'])}\s*\(",
                         c.read_text(errors="replace"), re.M):
                return str(c)
    return None


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("command", choices=("stats", "find", "shared", "solved", "ceded",
                                        "promote", "siblings", "similar"))
    ap.add_argument("name", nargs="?")
    ap.add_argument("--family", action="append", help="limit to a family (rooms, weapons, …)")
    ap.add_argument("--min", type=int, default=10, help="`shared`: minimum copies")
    ap.add_argument("--refs", action="store_true", help="`shared`: count overlay-local references")
    ap.add_argument("--unit", help="`promote`: name for the shared unit")
    ap.add_argument("--run", action="store_true",
                    help="`promote`: take the neighbours every carrier shares too, as one unit")
    ap.add_argument("--min-words", type=int, default=8, dest="min_words",
                    help="`solved`, `ceded`: ignore bodies shorter than this (default 8)")
    ap.add_argument("--list", dest="order_list",
                    help="`ceded`: the sweep list whose order decides each body's owner")
    ap.add_argument("--rebuild", action="store_true", help="ignore the cached index")
    ap.add_argument("--top", type=int, default=5, help="`similar`: candidates per class")
    ap.add_argument("--floor", type=float, default=0.80,
                    help="`similar`: ignore candidates below this score (default 0.80)")
    args = ap.parse_args()

    data = load(args.rebuild, args.family)
    if args.command == "solved":
        return cmd_solved(data, args.min_words)
    if args.command == "ceded":
        if not args.order_list:
            ap.error("ceded needs --list FILE")
        order = [line.split()[0] for line in Path(args.order_list).read_text().splitlines()
                 if line.strip() and not line.lstrip().startswith("#")]
        return cmd_ceded(data, args.min_words, order)
    if args.command == "siblings":
        if not args.name:
            ap.error("siblings needs a function name")
        return cmd_siblings(data, args.name, args.min_words)
    if args.command == "promote":
        if not args.name:
            ap.error("promote needs a function name")
        return cmd_promote(data, args.name, args.unit, run=args.run)
    if args.command == "similar":
        if not args.name:
            ap.error("similar needs a function name")
        return cmd_similar(data, args.name, args.top, args.floor)
    if args.command == "stats":
        return cmd_stats(data)
    if args.command == "shared":
        return cmd_shared(data, args.min, args.refs)
    if not args.name:
        ap.error("find needs a function name")
    return cmd_find(data, args.name)


if __name__ == "__main__":
    sys.exit(main())
