#!/usr/bin/env python3
"""Index functions that appear in more than one overlay.

Overlays in a family are separate link outputs that share a lot of code: 56% of
the room functions are copies of another room's, and 60% of the instructions.
Matching each copy separately would be the same work done up to 265 times, so
the first thing needed is to know what is shared.

Equality is decided on splat's **disassembly text**, not on the instruction
words. Comparing words is tempting and wrong: clearing the link-dependent
fields to let two copies at different addresses compare equal also clears every
other I-type immediate, so `lw $v0, 0x4($t0)` and `lw $v0, 0xC($t0)` - a
different struct field, a different function - come out identical. That
overstated room duplication as 56% of functions when the real figure is 17%.

The text is already symbolic where it needs to be, so the canonical form only
has to drop what names a copy's own position:

* the ``/* offset vram encoding */`` column,
* local branch labels, which splat names `.L<overlay>_<vram>`,
* the *identity* of an overlay-local symbol, keeping that it is local - two
  copies of one body reference their own room's data, not each other's.

Two hashes come out of that: ``text`` treats a local reference as a wildcard,
and ``raw`` is the instruction words verbatim - equal only when the copies are
byte-for-byte the same, which happens because every room loads at 0x8017D5C0.

The index is derived from asm/, which is regenerated by every split, so it is
cached under build/ and rebuilt when missing or stale.
"""

from __future__ import annotations

import argparse
import collections
import hashlib
import json
import re
import struct
import sys
from pathlib import Path

ASM_ROOT = Path("asm/USA")
CACHE = Path("build/USA/dup_index.json")
WORD = re.compile(r"^\s*/\* [0-9A-F]+ ([0-9A-F]{8}) ([0-9A-F]{8}) \*/", re.M)
REF = re.compile(r"%(?:hi|lo)\(([A-Za-z_]\w*)\)|\b(?:jal|j)\s+([A-Za-z_]\w*)")


ADDR = re.compile(r"^\s*/\* [0-9A-F]+ [0-9A-F]{8} [0-9A-F]{8} \*/")
LOCAL = re.compile(r"\b(func|D|jtbl)_([A-Za-z0-9_]+?)_([0-9A-F]{8})\b")
# `symbol_name_format` applies to local labels too, so they read
# `.L<overlay>_<vram>` - match any local label, not just a bare address.
BRANCH = re.compile(r"\.L\w+")
SKIP = ("glabel", "endlabel", "nonmatching", ".include", ".set", ".section", "/*")


def scan_function(path: Path, unit: str) -> dict | None:
    text = path.read_text(encoding="utf-8", errors="replace")
    found = WORD.findall(text)
    if not found:
        return None
    # splat writes the encoding big-endian in the comment; the target is little.
    words = [struct.unpack("<I", struct.pack(">I", int(w, 16)))[0] for _v, w in found]

    canon: list[str] = []
    labels: dict[str, str] = {}
    for line in text.splitlines():
        if line.startswith(SKIP):
            continue
        line = ADDR.sub("", line).rstrip()
        if not line:
            continue
        for hit in BRANCH.findall(line):
            labels.setdefault(hit, f".L{len(labels)}")
        line = BRANCH.sub(lambda m: labels[m.group(0)], line)
        line = LOCAL.sub(
            lambda m: f"{m.group(1)}_LOCAL" if m.group(2) == unit else m.group(0), line
        )
        canon.append(line)

    return {
        "name": path.stem,
        "unit": unit,
        "words": len(words),
        "vram": found[0][0],
        "raw": hashlib.sha1(struct.pack(f"<{len(words)}I", *words)).hexdigest(),
        "text": hashlib.sha1("\n".join(canon).encode()).hexdigest(),
        "refs": sorted({a or b for a, b in REF.findall(text)}),
    }


def build(families: list[str] | None) -> dict:
    roots = [ASM_ROOT / f for f in families] if families else [ASM_ROOT]
    out: list[dict] = []
    for root in roots:
        if not root.is_dir():
            continue
        for marker in ("nonmatchings", "matchings"):
          for path in sorted(root.rglob(f"{marker}/**/*.s")):
            if not path.name.startswith("func_"):
                continue
            # asm/<ver>/<family>/nonmatchings/<overlay>/<unit…>/<fn>.s - the
            # overlay is the component after the marker, not before it: asm_path
            # is the family root so several overlays share one asm tree.
            parts = path.parts
            at = parts.index(marker)
            overlay = parts[at + 1]
            rec = scan_function(path, overlay)
            if rec:
                rec["overlay"] = f"{'/'.join(parts[1:at])}/{overlay}"
                # A body already decompiled somewhere is solved: its remaining
                # copies want promoting into the shared library, not matching.
                rec["state"] = "matched" if marker == "matchings" else "todo"
                out.append(rec)
    return {"functions": out}


def load(rebuild: bool, families: list[str] | None) -> dict:
    if not rebuild and CACHE.is_file():
        return json.loads(CACHE.read_text())
    data = build(families)
    CACHE.parent.mkdir(parents=True, exist_ok=True)
    CACHE.write_text(json.dumps(data))
    return data


def classes(data: dict, key: str) -> dict[str, list[dict]]:
    out: dict[str, list[dict]] = collections.defaultdict(list)
    for fn in data["functions"]:
        out[fn[key]].append(fn)
    return out


def cmd_promote(data: dict, name: str, unit: str | None) -> int:
    """Move a body into the family's shared library.

    Does the plumbing that is identical either way - the span in
    configs/USA/overlays.toml for every overlay that carries the body, and the
    shared symbol in each of their symbol maps - so the caller only has to deal
    with the body itself.

    An overlay that contains the body twice is left out: ld includes an input
    object once, so the second slot would go unfilled.
    """
    import tomllib

    cl = classes(data, "text")
    hit = next((f for f in data["functions"] if f["name"] == name), None)
    if hit is None:
        print(f"{name}: not found", file=sys.stderr)
        return 1
    copies = cl[hit["text"]]
    if len(copies) < 2:
        print(f"{name}: only one copy, nothing to share")
        return 1

    family = hit["overlay"].split("/")[1]
    twice = {u for u, n in collections.Counter(f["overlay"] for f in copies).items() if n > 1}
    keep = [f for f in copies if f["overlay"] not in twice]
    if len(keep) < 2:
        print(f"{name}: every overlay carrying it contains it twice; cannot share")
        return 1
    # An unmatched body is shared as one disassembly file, and every overlay
    # writes it, so that file is only well-defined when the copies are
    # byte-identical and reference nothing overlay-local. A matched body has no
    # such limit: the compiler regenerates it for each link address.
    if hit.get("state") != "matched":
        images = len({f["raw"] for f in keep})
        localref = [f for f in keep
                    if any(r.startswith((f"func_{f['unit']}_", f"D_{f['unit']}_",
                                         f"jtbl_{f['unit']}_")) for r in f["refs"])]
        if images > 1 or localref:
            why = []
            if images > 1:
                why.append(f"{images} different byte images")
            if localref:
                why.append("references its own overlay's code or data")
            print(f"{name}: cannot be shared while unmatched - " + " and ".join(why) + ".")
            print("  Match it first, then promote: the compiler regenerates the body")
            print("  per link address, which is what makes the differing copies one source.")
            return 1

    unit = unit or f"{family}_shared_{hit['name'].split('_')[-1].lower()}"
    sym = "".join(w.capitalize() for w in unit.split("_"))

    manifest_path = Path("configs/USA/overlays.toml")
    manifest = tomllib.loads(manifest_path.read_text(encoding="utf-8"))
    overlays = manifest[family]["overlays"]
    load = manifest[family]["load_addr"]
    text = manifest_path.read_text(encoding="utf-8")
    size = hit["words"] * 4

    for f in sorted(keep, key=lambda f: f["overlay"]):
        room = f["overlay"].split("/")[-1]
        start = int(f["vram"], 16) - load
        spans = [(int(str(s["start"]), 16), int(str(s["end"]), 16), s["unit"])
                 for s in overlays[room].get("shared", [])]
        spans.append((start, start + size, unit))
        spans.sort()
        for (_a1, b1, _u1), (a2, _b2, _u2) in zip(spans, spans[1:]):
            if b1 > a2:
                print(f"{room}: shared spans overlap; aborting", file=sys.stderr)
                return 1
        items = ", ".join(
            f'{{ start = "0x{a:X}", end = "0x{b:X}", unit = "{u}" }}' for a, b, u in spans
        )
        m = re.search(rf"^{re.escape(room)} = \{{(.*)\}}$", text, re.M)
        body = re.sub(r",?\s*shared = \[.*?\](?=,|$)", "", m.group(1).strip()).strip().rstrip(",")
        body = f"{body}, shared = [{items}]" if body else f"shared = [{items}]"
        text = text[: m.start()] + f"{room} = {{ {body} }}" + text[m.end() :]

        sym_path = Path(f"configs/USA/sym/{family}/{room}.txt")
        sym_text = sym_path.read_text(encoding="utf-8")
        if sym not in sym_text:
            sym_path.write_text(
                sym_text.rstrip() + f"\n{sym} = 0x{int(f['vram'], 16):08X};"
                f" // shared body, see src/{family}/lib/\n", encoding="utf-8"
            )
    manifest_path.write_text(text, encoding="utf-8")

    print(f"{sym}: {len(keep)} of {len(copies)} copies share src/{family}/lib/{unit}.c")
    if twice:
        print(f"  left alone (contains it twice): {', '.join(sorted(twice))}")
    matched = [f for f in keep if f.get("state") == "matched"]
    if matched:
        print(f"  {name} is already decompiled - move its C body into "
              f"src/{family}/lib/{unit}.c as {sym}(), remove it from its own "
              f"overlay's .c, then rebuild.")
    else:
        print("  splat will write the shared stub on the next split.")
    print("  run: python3 ninja_config.py && ./tools/build-and-verify.sh")
    return 0


def cmd_solved(data: dict, min_words: int) -> int:
    """Unmatched functions whose body is already matched in **another** overlay.

    The other-overlay part is the whole point. Two copies inside one overlay are
    two separate functions that each have to be matched - they cannot share an
    object, because the overlay links once. Only a copy in a different overlay
    is work already done, reachable by promoting the body into the shared
    library instead of matching it again.
    """
    cl = classes(data, "text")
    out = []
    for v in cl.values():
        if v[0]["words"] < min_words:
            continue  # a stub is cheaper to match than to plumb into lib/
        for f in v:
            if f.get("state") == "matched":
                continue
            # Only a match in the *same family* is reachable: the shared unit
            # lives in src/<family>/lib/, so a body matched in gameplay says
            # nothing about a room's copy of it.
            family = f["overlay"].split("/")[1]
            if any(
                o.get("state") == "matched"
                and o["overlay"] != f["overlay"]
                and o["overlay"].split("/")[1] == family
                for o in v
            ):
                out.append(f["name"])
    for name in sorted(out):
        print(name)
    return 0


def cmd_stats(data: dict) -> int:
    fns = [f for f in data["functions"] if f.get("state") != "matched"]
    by_family = collections.Counter(f["overlay"].split("/")[0] for f in fns)
    print(f"{len(fns)} functions across {len(by_family)} family/families")
    for key, label in (("text", "same body"), ("raw", "same bytes")):
        cl = classes(data, key)
        red = len(fns) - len(cl)
        wt = sum(f["words"] for f in fns)
        wu = sum(v[0]["words"] for v in cl.values())
        print(f"  {label:12}: {len(cl):5} distinct, {red:5} redundant copies "
              f"({100*red//len(fns)}% of functions, {100*(wt-wu)//wt}% of instructions)")
    cl = classes(data, "text")
    hist = collections.Counter(len(v) for v in cl.values())
    multi = sum(c for n, c in hist.items() if n > 1)
    print(f"\n  bodies appearing more than once: {multi}")
    for n in (2, 3, 5, 10, 20, 50):
        c = sum(v for k, v in hist.items() if k >= n)
        print(f"    in >= {n:3} places: {c}")
    print("\n  biggest wins (copies x instructions saved):")
    ranked = sorted(cl.values(), key=lambda v: -(len(v) - 1) * v[0]["words"])
    for v in ranked[:8]:
        print(f"    {len(v):3} copies x {v[0]['words']:4} = {(len(v)-1)*v[0]['words']:6} saved   {v[0]['name']}")
    return 0


def cmd_find(data: dict, name: str) -> int:
    cl_text, cl_raw = classes(data, "text"), classes(data, "raw")
    hit = next((f for f in data["functions"] if f["name"] == name), None)
    if hit is None:
        print(f"{name}: not found", file=sys.stderr)
        return 1
    same_src = cl_text[hit["text"]]
    same_bytes = cl_raw[hit["raw"]]
    print(f"{name}  ({hit['words']} instructions, {hit['overlay']})")
    print(f"  same body: {len(same_src)} copies   identical bytes: {len(same_bytes)}")
    for f in sorted(same_src, key=lambda f: f["overlay"]):
        mark = "=" if f["raw"] == hit["raw"] else "~"
        state = "matched" if f.get("state") == "matched" else ""
        print(f"    {mark} {f['overlay']:36} {f['name']} {state}")
    print("\n  = identical bytes, ~ same body at a different link offset")
    return 0


def cmd_shared(data: dict, minimum: int, refs: bool) -> int:
    cl = classes(data, "text")
    ranked = sorted((v for v in cl.values() if len(v) >= minimum),
                    key=lambda v: -(len(v) - 1) * v[0]["words"])
    print(f"{len(ranked)} bodies in >= {minimum} places")
    for v in ranked:
        line = f"  {len(v):3} copies  {v[0]['words']:4} insns  {v[0]['name']}"
        if refs:
            own = {r for f in v for r in f["refs"]
                   if r.startswith((f"func_{f['unit']}_", f"D_{f['unit']}_", f"jtbl_{f['unit']}_"))}
            line += f"   room-local refs: {len(own)}"
        print(line)
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("command", choices=("stats", "find", "shared", "solved", "promote"))
    ap.add_argument("name", nargs="?")
    ap.add_argument("--family", action="append", help="limit to a family (rooms, weapons, …)")
    ap.add_argument("--min", type=int, default=10, help="`shared`: minimum copies")
    ap.add_argument("--refs", action="store_true", help="`shared`: count overlay-local references")
    ap.add_argument("--unit", help="`promote`: name for the shared unit")
    ap.add_argument("--min-words", type=int, default=8, dest="min_words",
                    help="`solved`: ignore bodies shorter than this (default 8)")
    ap.add_argument("--rebuild", action="store_true", help="ignore the cached index")
    args = ap.parse_args()

    data = load(args.rebuild, args.family)
    if args.command == "solved":
        return cmd_solved(data, args.min_words)
    if args.command == "promote":
        if not args.name:
            ap.error("promote needs a function name")
        return cmd_promote(data, args.name, args.unit)
    if args.command == "stats":
        return cmd_stats(data)
    if args.command == "shared":
        return cmd_shared(data, args.min, args.refs)
    if not args.name:
        ap.error("find needs a function name")
    return cmd_find(data, args.name)


if __name__ == "__main__":
    sys.exit(main())
