#include "common.h"

INCLUDE_ASM("rooms/nonmatchings/dryfield_night_motel_room_3/dryfield_night_motel_room_3", func_dryfield_night_motel_room_3_8017D684);

INCLUDE_ASM("rooms/nonmatchings/dryfield_night_motel_room_3/dryfield_night_motel_room_3", func_dryfield_night_motel_room_3_8017D68C);

INCLUDE_ASM("rooms/nonmatchings/dryfield_night_motel_room_3/dryfield_night_motel_room_3", func_dryfield_night_motel_room_3_8017D694);

void func_dryfield_night_motel_room_3_8017D6D8(void)
{
}

INCLUDE_RODATA("rooms/nonmatchings/dryfield_night_motel_room_3/dryfield_night_motel_room_3", D_dryfield_night_motel_room_3_8017D5C0);

INCLUDE_ASM("rooms/nonmatchings/dryfield_night_motel_room_3/dryfield_night_motel_room_3", func_dryfield_night_motel_room_3_8017D6E0);

INCLUDE_RODATA("rooms/nonmatchings/dryfield_night_motel_room_3/dryfield_night_motel_room_3", jtbl_dryfield_night_motel_room_3_8017D5D0);

INCLUDE_RODATA("rooms/nonmatchings/dryfield_night_motel_room_3/dryfield_night_motel_room_3", D_dryfield_night_motel_room_3_8017D5F4);
