#include "common.h"

INCLUDE_ASM("rooms/nonmatchings/shelter_b1_sterilization_room/shelter_b1_sterilization_room_2", func_shelter_b1_sterilization_room_8017EEF0);

INCLUDE_ASM("rooms/nonmatchings/shelter_b1_sterilization_room/shelter_b1_sterilization_room_2", func_shelter_b1_sterilization_room_8017EFE4);
